### PR TITLE
refactor!: replaced None with nil in lua-generator

### LINKED ISSUE #6720: Lua generators use None instead of nil
This causes
image
this generates `list = {None, None, None} print(#list)` printing 0

Expected Behavior:
The generator should produce `list = {nil, nil, nil} print(#list)` printing 3

## To Fix

1) In the [list block-code generators](https://github.com/google/blockly/blob/develop/generators/lua/lists.ts). Change references to `'None'` to `'nil'`.
2) Update the [block-code generator tests](https://github.com/google/blockly/blob/develop/tests/generators/golden/generated.lua) if they are failing.

### PR DESCRIPTION
**Pull request by neerajkumarc**
Fixes #6720 
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes

### CODE REVIEW

**Review by BeksOmega — APPROVED** [review]
LGTM! Thank you for the fix :D

**Comment by BeksOmega** [comment]
@neerajkumarc since this is a breaking change, we're going to hold this for a bit so we can release non-breaking changes in mid Februrary. So I'm going to convert this to a draft to make sure it doesn't get merged accidentally!

But it has been approved and will go in once we're set up to accept it =)

**Comment by BeksOmega** [comment]
Heya @neerajkumarc Would you have time to rebase this against the `v11-breaks` branch? If not I can make a dupe of your branch and rebase it =)

**Comment by neerajkumarc** [comment]
I tried rebasing it, but somehow, I messed up my local Git repo and pushed some weird commits. I rolled back those changes and want to apologize for any inconvenience caused.🙏

**Comment by BeksOmega** [comment]
It's all good! Git is really tricky. But it looks like you might have actually dropped your original changes :/ If you're still interested inworking on this, the easiest thing to do is probably to branch from `v11-breaks` and make your changes again.

**Comment by BeksOmega** [comment]
@neerajkumarc I'm going to go ahead and close this! Thank you for your work on it =)

**Pull request closed without merging**
