### PR TITLE
Move parseBlockColour into Blockly.utils

### PR DESCRIPTION
**Pull request by samelhusseini**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

@NeilFraser I chased the problem you're running into to a missing require in colours.

Fixes https://github.com/google/blockly/issues/3397

### Proposed Changes

https://github.com/google/blockly/blob/develop/core/utils/colour.js#L232 depends on ``Blockly.HSV_SATURATION`` which comes from ``Blockly.constants``. Even though this is required in ``blockly.js``, the Theme object [runs through and validates](https://github.com/google/blockly/blob/develop/core/theme.js#L164) all of the colours in the theme during initialization which in turn calls this method. 

This doesn't show up if you require `Blockly` first, but in the case of Blockly games, Blockly isn't the first thing that's required, which is why you end up in with the Theme object calling the validate method without ``Blockly.constants`` available.

Add missing require in colour utils.

### Test Coverage

Tested on:

### CODE REVIEW

**Comment by NeilFraser** [comment]
Just to expand on why having that function here is a bad idea, the single call to `Blockly.utils.replaceMessageReferences` means we must also require `Blockly.utils` in this file, which implicitly requires:
```
goog.require('Blockly.Msg');
goog.require('Blockly.utils.Coordinate');
goog.require('Blockly.utils.global');
goog.require('Blockly.utils.string');
goog.require('Blockly.utils.style');
goog.require('Blockly.utils.userAgent');
```
Which chains on to require:
```
goog.require('Blockly.utils.Size');
```

It happens to work out at the moment, but this is how one gets recursive dependencies.

**Comment by samelhusseini** [comment]
I agree in moving this to ``Blockly.utils``. It was actually originally in [block.js](https://github.com/google/blockly/blob/23a78c89e4c0f2801768b5c55c7f91ac261f4bc6/core/block.js#L963).

**Comment by samelhusseini** [comment]
@NeilFraser updated.

**Comment by samelhusseini** [comment]
No worries :)

**Comment by rachel-fenichel** [comment]
Makes sense.  Thanks for the explanations.

**Pull request merged**
