### PR TITLE
fix: remove vestigial dependency

### PR DESCRIPTION
**Pull request by BeksOmega**
## The basics

- [X] I branched from develop
- [X] My pull request is against develop
- [X] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [X] I ran `npm run format` and `npm run lint`

### Resolves

Hopefully fixes problems with message dependencies we ran into in samples.

### Proposed Changes

Removes the vestigially Blockly dependency from the message wrappers.

#### Behavior Before Change

The Blockly module could not be resolved.

#### Behavior After Change

No need to resolve any modules hopefully.

### Reason for Changes

Getting the messages to actually work.

### Test Coverage

I tested manually removing the dependencies in the node_modules of some plugins in samples, and that seemed to fix things.

I also tried linking to `field-bitmap` and running `npm run predeploy` before and after this change, and the changes in this PR seemed to fix the problem.

### CODE REVIEW

**Review by cpcallen — APPROVED** [review]
This should be fine:

* The AMD and CJS wrapper entry points (and the body of the wrapped message files) do not depend on `Blockly` so have no need to `require` it.
* While the browser entry point _does_ depends on `Blockly`, it expect it to have been pre-loaded via `<script>`, so removing it here has no effect on the generated stanza.

I am interested in in what the problem you encountered in blockly-samples was, though.  Was it somehow caused by #6210?  It looks to me like the real issue here is that `'Blockly'` is not the name of a file that can be loaded, that changing it to `'./blockly_compressed.js'` (or one of the wrappers thereof) would have worked equally well (albeit being, as noted above, unnecessary).

**Comment by BeksOmega** [comment]
> I am interested in in what the problem you encountered in blockly-samples was, though.

Oh yeah whoops, forgot to post. I was getting this error when running `npm run predeploy`

```
ERROR in ./node_modules/blockly/msg/en.js 
Module not found: Error: Can't resolve 'Blockly' in '/usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/typed-variable-modal/node_modules/blockly/msg'
resolve 'Blockly' in '/usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/typed-variable-modal/node_modules/blockly/msg'
  Parsed request is a module
  using description file: /usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/typed-variable-modal/node_modules/blockly/package.json (relative path: ./msg)
    resolve as module
      /usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/typed-variable-modal/node_modules/blockly/msg/node_modules doesn't exist or is not a directory
      looking for modules in /usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/typed-variable-modal/node_modules/blockly/node_modules
        single file module
          using description file: /usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/typed-variable-modal/node_modules/blockly/package.json (relative path: ./node_modules/Blockly)
            no extension
              /usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/typed-variable-modal/node_modules/blockly/node_modules/Blockly doesn't exist
            .js
              /usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/typed-variable-modal/node_modules/blockly/node_modules/Blockly.js doesn't exist
        /usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/typed-variable-modal/node_modules/blockly/node_modules/Blockly doesn't exist
      /usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/typed-variable-modal/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/typed-variable-modal/node_modules
        single file module
          using description file: /usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/typed-variable-modal/package.json (relative path: ./node_modules/Blockly)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/typed-variable-modal/node_modules/Blockly doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/typed-variable-modal/node_modules/Blockly.js doesn't exist
        /usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/typed-variable-modal/node_modules/Blockly doesn't exist
      /usr/local/google/home/bwestberg/Dev/blockly-samples/plugins/node_modules doesn't exist or is not a directory
      looking for modules in /usr/local/google/home/bwestberg/Dev/blockly-samples/node_modules
        single file module
          using description file: /usr/local/google/home/bwestberg/Dev/blockly-samples/package.json (relative path: ./node_modules/Blockly)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /usr/local/google/home/bwestberg/Dev/blockly-samples/node_modules/Blockly doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /usr/local/google/home/bwestberg/Dev/blockly-samples/node_modules/Blockly.js doesn't exist
        /usr/local/google/home/bwestberg/Dev/blockly-samples/node_modules/Blockly doesn't exist
      /usr/local/google/home/bwestberg/Dev/node_modules doesn't exist or is not a directory
      /usr/local/google/home/bwestberg/node_modules doesn't exist or is not a directory
      /usr/local/google/home/node_modules doesn't exist or is not a directory
      /usr/local/google/node_modules doesn't exist or is not a directory
      /usr/local/node_modules doesn't exist or is not a directory
      /usr/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./node_modules/blockly/browser.js
 @ ./node_modules/blockly/index.js
 @ ./test/index.js 11:0-35 34:20-65 40:18-32
```

> Was it somehow caused by https://github.com/google/blockly/pull/6210?

I'm honestly not sure. I tried to manually change the message wrappers to use `define(['Blockly', '../core'], factory())` as well, which is what I imagine they looked like previously, and I got the same error. So this makes me think it was broken before.

However, [Johnny just got a similar error](https://github.com/google/blockly/issues/4369#issuecomment-1157242721), which was not happening before. Which makes me think it was working before.

But also, he's making a React app, so the AMD section of the wrapper shouldn't be affecting what he's doing. So I want to dig into that more before merging this.

**Comment by cpcallen** [comment]
> So I want to dig into that more before merging this.

Sensible enough, but just to be clear: I think this PR is fine on its own merits and can be merged whenever you like; I just think it's worth understanding what was broken (and for how long, and if for long how we avoided noticing until now) for the purposes of avoiding the same mistake(s) in future.

**Comment by BeksOmega** [comment]
So I checked out the v8.0.0 tag and before the amd definition would be `define(['../core'], factory())`, not `define(['Blockly', '../core'], factory())` so that explains why my manual test failed.

I tested manually adding this fix (`define([], factory())`) to the react-demo and that fixed the problem that Johnny found. I still don't understand why React hits the amd module definition, but I guess it does.

So I'm cool putting this in now.

**Comment by cpcallen** [comment]
> I still don't understand why React hits the amd module definition, but I guess it does.

React probably (depends on something that)* depends on an AMD loader like RequireJS.

**Pull request merged**
