### PR TITLE
Validation

### PR DESCRIPTION
**Pull request by jano42**
I modified Blockly to add a validation process.

The aim is to ensure that all blocks are correctly connected.

It take into account a maximum number of allowed top blocks.

See "playground.html"

### CODE REVIEW

**Comment by jano42** [comment]
Two samples : 

2015-03-15 08_58_42-yadoms

2015-03-15 09_00_21-yadoms

**Comment by ensonic** [comment]
Are you only flagging open connections  that don't have anythign conencted or are you also checking for 'dangling' items on the workspace that are not attached (e.g. a number block)?

**Comment by jano42** [comment]
The process of validation is to check if any block have empty connections.

Then it is also configurable to allow a maximum number of "TopBlock". 
By default only 1 top block is allowed, but can be easily extended.

**Comment by rachel-fenichel** [comment]
Closing as very old.

We now have a function that I think does a lot of what you want: [Blockly.Block.prototype.allInputsFilled](https://github.com/google/blockly/blame/develop/core/block.js#L1532).

**Pull request closed without merging**
