### PR TITLE
Blockly Factory: Added Blockly Factory to demos directory

### PR DESCRIPTION
**Pull request by evd2014**
Added Blockly Factory to the demos directory, updating the demos index.html and adding an icon.

Also removed the workspace factory index.html, which is no longer necessary now that the tabs have been unified, and is not usable (throws errors because as UI changes have been made in the blockly factory index.html, they have not also been made in the workspace factory index.html).

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/611)

### CODE REVIEW

**Comment by evd2014** [comment]
@picklesrus @vicng @quachtina96

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/611#-:-KQS9MLNJal5LNb6uhvk:bvyui8)*

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/611#-:-KQT2BLVKdeQXDtGhq0L:bnfp4nl)*

**Comment by quachtina96** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/611#-:-KQWf4wryxmyDsHd1SJB:bnfp4nl)*

**Comment by quachtina96** [comment]
@picklesrus do you think we could get this merged before develop gets pulled into master on Tuesday?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/611#-:-KQbu2yKYmHKGCugL119:b6er2rz)*

**Comment by TechplexEngineer** [comment]
@evd2014 It looks like they need a CLA from you to merge this change.

**Comment by rachel-fenichel** [comment]
@TechplexEngineer we're aware of this, but holding off on merging for a bit.

**Comment by picklesrus** [comment]
We ended up merging into block factory instead of keeping blockly factory a separate thing.  All done as of last week!

**Pull request closed without merging**
