### PR TITLE
Add a new FieldDate input type

### PR DESCRIPTION
**Pull request by pkendall64**
Add a datepicker field type.
This was done in a fashion similar to that of the colour picker field by using the datepicker from the google closure project and including the CSS from there.

### CODE REVIEW

**Comment by NeilFraser** [comment]
I've just pushed an update that adds internationalization to the date picker.  Also added it to the Block Factory.  I've removed the 'None' option from the picker since that didn't seem to be supported by the initialization API (which treats null as today).  Let me know what you think.
https://github.com/google/blockly/commit/cbb7204c270f97a491984a77898cf52c2163f2a6

**Comment by pkendall64** [comment]
Yeah, that's awesome. I was going to get onto that next week, but you've saved me a job.

**Comment by NeilFraser** [comment]
The datepicker pulls in a ton of Closure files that we were not otherwise using.  As a result, blockly-compressed.js has jumped from 556K to 885K.  That's a 60% increase just for the date picker (of which you are the only user).

Tomorrow I intend to comment out goog.require('Blockly.FieldDate'); from blockly.js and comment out the date picker block from the Block Factory.  Can you work around this?  Maybe add goog.require('Blockly.FieldDate'); to some file in your build process?

**Comment by pkendall64** [comment]
On Wed, Feb 25, 2015 at 3:14 PM, Neil Fraser <notifications@github.com>
wrote:

> The datepicker pulls in a ton of Closure files that we were not otherwise
> using. As a result, blockly-compressed.js has jumped from 556K to 885K.
> That's a 60% increase just for the date picker (of which you are the only
> user).
>
> Tomorrow I intend to comment out goog.require('Blockly.FieldDate'); from
> blockly.js and comment out the date picker block from the Block Factory.
> Can you work around this? Maybe add goog.require('Blockly.FieldDate'); to
> some file in your build process?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/blockly/pull/60#issuecomment-75892854>.
>
Wow, I didn't realize it was that big! I'll add it into our build process
instead then.

**Pull request merged**
