### PR TITLE
feat: Add a blocklyCollapsed CSS class to collapsed blocks' root SVG (#8264)

### PR DESCRIPTION
**Pull request by ga-fleury**
Fixes: #8264 

**feat: Add a blocklyCollapsed CSS class to collapsed blocks' root SVG (#8264)**

### CODE REVIEW

**Review by BeksOmega — APPROVED** [review]
This looks great! Thank you for the fix =)

Once this passes CI I'll get it merged!

**Comment by BeksOmega** [comment]
Looks like this is failing formatting. Please fix the same way I suggested on the other PR!

**Review by BeksOmega — CHANGES_REQUESTED** [review]
Marking this as changes requested

**Comment by BeksOmega** [comment]
Heya @ga-fleury Are you still interested in working on this?

**Comment by ga-fleury** [comment]
@BeksOmega format changes pushed

**Review by BeksOmega — APPROVED** [review]
This looks great =) Thanks for your work on this!

**Pull request merged**
