### PR TITLE
Blockly Factory: Improve Import Block Library

### PR DESCRIPTION
**Pull request by quachtina96**
More robustly handles spacing in the imported xml files and maintains the pretty format of the xml upon saving each block type and its xml to the block library.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/555)

### CODE REVIEW

**Comment by quachtina96** [comment]
@vicng @picklesrus @evd2014

**Comment by picklesrus** [comment]
This is probably something I should have noticed before, but technically the files generated aren't valid xml since they have multiple root elements.  Would it be easier if the thing you were parsing was valid? Could you then just parse it into a list rather than having to deal with this?  I'm worried that this is a bit fragile.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[demos/blocklyfactory/factory_utils.js, line 738 \[r1\]](https://reviewable.io:443/reviews/google/blockly/555#-KPKaka6IB9ZoaSZ6FBR:-KPKaka6IB9ZoaSZ6FBS:bqe35a8) ([raw file](https://github.com/google/blockly/blob/67fa5e154ed305eeaa8b840241a315f0d1be7b8c/demos/blocklyfactory/factory_utils.js#L738)):*
> ```JavaScript
>  *
>  * @param {!string} stringOfXmls - Single string of xml texts.
>  * @return {!Array.<strint>} the Blockly.Block of desired type.
> ```

typo: string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/555#-:-KPKdhv-dQNrE2W6xuP5:b-hi55n2)*

**Comment by quachtina96** [comment]
Could we meet to talk about this?

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[demos/blocklyfactory/factory_utils.js, line 738 \[r1\]](https://reviewable.io:443/reviews/google/blockly/555#-KPKaka6IB9ZoaSZ6FBR:-KPOW15EypQhTLv_Yva4:b-896fix) ([raw file](https://github.com/google/blockly/blob/67fa5e154ed305eeaa8b840241a315f0d1be7b8c/demos/blocklyfactory/factory_utils.js#L738)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> typo: string
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/555#-:-KPOWG-vUnndmb7diSP4:b-mrb4lo)*

**Comment by picklesrus** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/app_controller.js, line 136 \[r4\]](https://reviewable.io:443/reviews/google/blockly/555#-KPPoNlR_AzP_cNvOVGl:-KPPoNlSqcCQheiv-Asv:b-1vm3zz) ([raw file](https://github.com/google/blockly/blob/53b5f91627429f347c6bee28c7bc1e04a9dafac0/demos/blocklyfactory/app_controller.js#L136)):*
> ```JavaScript
>  *
>  * @param {!Object} blockXmlMap - object mapping block type to xml
>  * @return {string} String of each block's xml separated by a new line.
> ```

update comment.  

---

*[demos/blocklyfactory/factory_utils.js, line 738 \[r1\]](https://reviewable.io:443/reviews/google/blockly/555#-KPKaka6IB9ZoaSZ6FBR:-KPPnophITnGcKpuFp_t:b3690k8) ([raw file](https://github.com/google/blockly/blob/67fa5e154ed305eeaa8b840241a315f0d1be7b8c/demos/blocklyfactory/factory_utils.js#L738)):*
<details><summary><i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>
> Done.
</details>
You can just revert this file now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/555)*

**Comment by picklesrus** [comment]
Also, conflicts need to be resolved before it can be merged

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/555#-:-KPPpBy9xObyItCrJ9XG:bmtwpfk)*

**Comment by quachtina96** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[demos/blocklyfactory/app_controller.js, line 136 \[r4\]](https://reviewable.io:443/reviews/google/blockly/555#-KPPoNlR_AzP_cNvOVGl:-KPQ5DQ2KIpctCtmSMjW:b-896fix) ([raw file](https://github.com/google/blockly/blob/53b5f91627429f347c6bee28c7bc1e04a9dafac0/demos/blocklyfactory/app_controller.js#L136)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> update comment.  
</details>
Done.

---

*[demos/blocklyfactory/factory_utils.js, line 738 \[r1\]](https://reviewable.io:443/reviews/google/blockly/555#-KPKaka6IB9ZoaSZ6FBR:-KPQ5GGCgk2OZ3dA8d_Z:b-8dmh0s) ([raw file](https://github.com/google/blockly/blob/67fa5e154ed305eeaa8b840241a315f0d1be7b8c/demos/blocklyfactory/factory_utils.js#L738)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> You can just revert this file now.
</details>
I added a new line at the end of the file  which is required according to the linter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/555)*

**Comment by quachtina96** [comment]
Resolved merge conflicts!

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/555#-:-KPQ8VS4wRfl01ONhHiQ:bjvh7mz)*

**Comment by evd2014** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/555#-:-KPTR28NcsM_qW5NttpN:bnfp4nl)*

**Comment by picklesrus** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/555#-:-KPTRm24ebcvi21ZrFX4:bnfp4nl)*

**Pull request merged**
