### PR TITLE
Blockly Factory: Select Used Blocks for Export

### PR DESCRIPTION
**Pull request by quachtina96**
User may now select blocks that are used in the workspace factory for export as long as they are in the block library. 

screen shot 2016-08-17 at 5 28 37 pm

### app_controller
- added missing click handler for export button
- added click handler for add all used blocks
- edited onTab to save state from workspace when leaving the tab.

### block_exporter_controller 
-  added ivar to store usedBlocks
- added function to set usedBlocks
- added function to add used blocks to selector workspace

### factory_utils
- helper function for getting the blocktypes in common between those used in workspace factory and those stored in block library

### wfactory_controller
- wrapper function for model's getAllUsedBlockTypes

### wfactory_model
- called fixed bug in calling pushBlockTypesToList

### block_library_controller
- nit spacing

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/565)

### CODE REVIEW

**Comment by quachtina96** [comment]
@vicng @picklesrus @evd2014

**Comment by evd2014** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[demos/blocklyfactory/app_controller.js, line 288 \[r1\]](https://reviewable.io:443/reviews/google/blockly/565#-KPTRKJSA7T8Tq9DJETG:-KPTRKJSA7T8Tq9DJETH:btd5lt2) ([raw file](https://github.com/google/blockly/blob/93d7ca5a1b97e0da875cc919ef5dd2321f2460ea/demos/blocklyfactory/app_controller.js#L288)):*
> ```JavaScript
>   } else if (this.selectedTab ==  'BLOCK_FACTORY') {
>     // Save state in case you are switching from workspace factory tab.
>     this.workspaceFactoryController.saveStateFromWorkspace();
> ```

I know we talked about saving the state when switching to either tab, but looking at it now, because workspace factory is just hidden, you should only need to call saveStateFromWorkspace() when switching to the exporter, and so you can remove this call to saveStateFromWorkspace()

---

*[demos/blocklyfactory/block_exporter_controller.js, line 347 \[r1\]](https://reviewable.io:443/reviews/google/blockly/565#-KPTTyQ45XYBZMetZYGY:-KPTTyQ59k-m5buGV6yc:b4fpyqo) ([raw file](https://github.com/google/blockly/blob/93d7ca5a1b97e0da875cc919ef5dd2321f2460ea/demos/blocklyfactory/block_exporter_controller.js#L347)):*
> ```JavaScript
>   var blockXmlMap = this.blockLibStorage.getBlockXmlMap(sharedTypes);
>   this.tools.addBlockDefinitions(blockXmlMap);
> ```

It would be nice if there was some alert or message if a used block was not contained in the Block Library. To do that, it might make sense to move the code for getSharedTypes out of FactoryUtils and put it here directly, and then loop through the used blocks, and then if the block library doesn't have one of the blocks, alert the user (either with the name at that time or just once at the end, possibly with a list of all the blocks). That could also be saved for another CL, but it doesn't seem like a long and involved change (depending on how you want to do it, up to you).

---

*[demos/blocklyfactory/block_library_controller.js, line 1 \[r1\]](https://reviewable.io:443/reviews/google/blockly/565#-KPTS-Uhv09imv_cUw28:-KPTS-Uhv09imv_cUw29:b-807afe) ([raw file](https://github.com/google/blockly/blob/93d7ca5a1b97e0da875cc919ef5dd2321f2460ea/demos/blocklyfactory/block_library_controller.js#L1)):*
> ```JavaScript
> get/**
> ```

Typo?

---

*[demos/blocklyfactory/factory_utils.js, line 881 \[r1\]](https://reviewable.io:443/reviews/google/blockly/565#-KPTTF86uL7QFue3GNk0:-KPTTF86uL7QFue3GNk1:b-9u9h78) ([raw file](https://github.com/google/blockly/blob/93d7ca5a1b97e0da875cc919ef5dd2321f2460ea/demos/blocklyfactory/factory_utils.js#L881)):*
> ```JavaScript
>  *
>  * @param {!Array.<string>} blockTypesOne - Array of block types.
>  * @param {!Array.<string>} blockTypesTwo - Array of block types.
> ```

Add @return

---

*[demos/blocklyfactory/factory_utils.js, line 884 \[r1\]](https://reviewable.io:443/reviews/google/blockly/565#-KPTSxMGFIh3IsE3IoCu:-KPTSxMGFIh3IsE3IoCv:b-2nxt9j) ([raw file](https://github.com/google/blockly/blob/93d7ca5a1b97e0da875cc919ef5dd2321f2460ea/demos/blocklyfactory/factory_utils.js#L884)):*
> ```JavaScript
>  */
> FactoryUtils.getSharedTypes = function(blockTypesOne, blockTypesTwo) {
>     var referenceSet = new Set(blockTypesTwo);
> ```

I thought IE didn't support creating a Set from an Array? Instead of using a Set, you could just use indexOf != -1 instead of .has()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/565)*

**Comment by quachtina96** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[demos/blocklyfactory/app_controller.js, line 288 \[r1\]](https://reviewable.io:443/reviews/google/blockly/565#-KPTRKJSA7T8Tq9DJETG:-KPTglfZdZDGjbVxDcdQ:b-896fix) ([raw file](https://github.com/google/blockly/blob/93d7ca5a1b97e0da875cc919ef5dd2321f2460ea/demos/blocklyfactory/app_controller.js#L288)):*
<details><summary><i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>
> I know we talked about saving the state when switching to either tab, but looking at it now, because workspace factory is just hidden, you should only need to call saveStateFromWorkspace() when switching to the exporter, and so you can remove this call to saveStateFromWorkspace()
</details>
Done.

---

*[demos/blocklyfactory/block_exporter_controller.js, line 347 \[r1\]](https://reviewable.io:443/reviews/google/blockly/565#-KPTTyQ45XYBZMetZYGY:-KPUII6Up5NRMxj9xaj0:b-yiox8h) ([raw file](https://github.com/google/blockly/blob/93d7ca5a1b97e0da875cc919ef5dd2321f2460ea/demos/blocklyfactory/block_exporter_controller.js#L347)):*
<details><summary><i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>
> It would be nice if there was some alert or message if a used block was not contained in the Block Library. To do that, it might make sense to move the code for getSharedTypes out of FactoryUtils and put it here directly, and then loop through the used blocks, and then if the block library doesn't have one of the blocks, alert the user (either with the name at that time or just once at the end, possibly with a list of all the blocks). That could also be saved for another CL, but it doesn't seem like a long and involved change (depending on how you want to do it, up to you).
</details>
Done!  alert for when a used block is a standard block. different alert for when a used block is a custom block not stored in lib.

---

*[demos/blocklyfactory/block_library_controller.js, line 1 \[r1\]](https://reviewable.io:443/reviews/google/blockly/565#-KPTS-Uhv09imv_cUw28:-KPTgq36KskVSPl5hMms:b-8stz43) ([raw file](https://github.com/google/blockly/blob/93d7ca5a1b97e0da875cc919ef5dd2321f2460ea/demos/blocklyfactory/block_library_controller.js#L1)):*
<details><summary><i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>
> Typo?
</details>
good catch! removed!

---

*[demos/blocklyfactory/factory_utils.js, line 881 \[r1\]](https://reviewable.io:443/reviews/google/blockly/565#-KPTTF86uL7QFue3GNk0:-KPThKip9L7oVTJPXex8:b-896fix) ([raw file](https://github.com/google/blockly/blob/93d7ca5a1b97e0da875cc919ef5dd2321f2460ea/demos/blocklyfactory/factory_utils.js#L881)):*
<details><summary><i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>
> Add @return
</details>
Done.

---

*[demos/blocklyfactory/factory_utils.js, line 884 \[r1\]](https://reviewable.io:443/reviews/google/blockly/565#-KPTSxMGFIh3IsE3IoCu:-KPTh8FIKQKlTvnwN9Of:b-896fix) ([raw file](https://github.com/google/blockly/blob/93d7ca5a1b97e0da875cc919ef5dd2321f2460ea/demos/blocklyfactory/factory_utils.js#L884)):*
<details><summary><i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>
> I thought IE didn't support creating a Set from an Array? Instead of using a Set, you could just use indexOf != -1 instead of .has()
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/565)*

**Comment by vicng** [comment]
Review status: 0 of 7 files reviewed at latest revision, 11 unresolved discussions.

---

*[demos/blocklyfactory/app_controller.js, line 301 \[r3\]](https://reviewable.io:443/reviews/google/blockly/565#-KPUg89z_ch2xmbhUmmw:-KPUg89z_ch2xmbhUmmx:bxd3zvn) ([raw file](https://github.com/google/blockly/blob/80edc19af46e27aef6c9095aaad6bc5396c9207d/demos/blocklyfactory/app_controller.js#L301)):*
> ```JavaScript
>     this.workspaceFactoryController.saveStateFromWorkspace();
> 
>     // Udpate exporter's list of the types of blocks used in workspace factory.
> ```

Update udpate

---

*[demos/blocklyfactory/block_exporter_controller.js, line 348 \[r3\]](https://reviewable.io:443/reviews/google/blockly/565#-KPUgR_7oDy7bspPmC7x:-KPUgR_7oDy7bspPmC7y:b9ywx9j) ([raw file](https://github.com/google/blockly/blob/80edc19af46e27aef6c9095aaad6bc5396c9207d/demos/blocklyfactory/block_exporter_controller.js#L348)):*
> ```JavaScript
>   var warnForStandardBlockTypes = false;
> 
>   for (var i = 0; i < this.usedBlockTypes.length; i++) {
> ```

Shouldn't this be the fancy `for` loop syntax?

---

*[demos/blocklyfactory/block_exporter_controller.js, line 353 \[r3\]](https://reviewable.io:443/reviews/google/blockly/565#-KPUkr_dIZn7ZN-cOLxl:-KPUkr_dIZn7ZN-cOLxm:b-sf5srn) ([raw file](https://github.com/google/blockly/blob/80edc19af46e27aef6c9095aaad6bc5396c9207d/demos/blocklyfactory/block_exporter_controller.js#L353)):*
> ```JavaScript
>       sharedBlockTypes.push(blockType);
>     } else if (
>         !(warnForStandardBlockTypes && unstoredCustomBlockTypes.length > 0)) {
> ```

This `else if` will only let the following code pass through once. Is that intended?

---

*[demos/blocklyfactory/block_exporter_controller.js, line 378 \[r3\]](https://reviewable.io:443/reviews/google/blockly/565#-KPUlMIqLktpi7RbO0sl:-KPUlMIqLktpi7RbO0sm:b-3przna) ([raw file](https://github.com/google/blockly/blob/80edc19af46e27aef6c9095aaad6bc5396c9207d/demos/blocklyfactory/block_exporter_controller.js#L378)):*
> ```JavaScript
>   // Warn user to import blocks_compressed.js if they are using block(s)
>   // Blockly's standard library.
>   if (warnForStandardBlockTypes){
> ```

Would these alerts make more sense when the user clicks export rather than when adding blocks to the workspace?

---

*[demos/blocklyfactory/block_exporter_controller.js, line 381 \[r3\]](https://reviewable.io:443/reviews/google/blockly/565#-KPUkNoomH7XHV9L2Acf:-KPUkNoomH7XHV9L2Acg:b-6sdhkt) ([raw file](https://github.com/google/blockly/blob/80edc19af46e27aef6c9095aaad6bc5396c9207d/demos/blocklyfactory/block_exporter_controller.js#L381)):*
> ```JavaScript
>     alert('You are using one or more blocks from ' +
>         'Blockly\'s standard library. Remember to import blocks_compressed.js');
> ```

Remove line.

---

*[demos/blocklyfactory/block_exporter_controller.js, line 383 \[r3\]](https://reviewable.io:443/reviews/google/blockly/565#-KPUkPlZXs1BJiML_6Cu:-KPUkPlZXs1BJiML_6Cv:bb39usl) ([raw file](https://github.com/google/blockly/blob/80edc19af46e27aef6c9095aaad6bc5396c9207d/demos/blocklyfactory/block_exporter_controller.js#L383)):*
> ```JavaScript
> 
>   }
>   if (unstoredCustomBlockTypes.length > 0){
> ```

Add line above this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/565)*

**Comment by quachtina96** [comment]
Review status: 0 of 7 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/app_controller.js, line 301 \[r3\]](https://reviewable.io:443/reviews/google/blockly/565#-KPUg89z_ch2xmbhUmmw:-KPWR8UKu2aiVhpJyPgT:b-896fix) ([raw file](https://github.com/google/blockly/blob/80edc19af46e27aef6c9095aaad6bc5396c9207d/demos/blocklyfactory/app_controller.js#L301)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Update udpate
</details>
Done.

---

*[demos/blocklyfactory/block_exporter_controller.js, line 348 \[r3\]](https://reviewable.io:443/reviews/google/blockly/565#-KPUgR_7oDy7bspPmC7x:-KPWQYdhNbS_NmJV_JeE:b-896fix) ([raw file](https://github.com/google/blockly/blob/80edc19af46e27aef6c9095aaad6bc5396c9207d/demos/blocklyfactory/block_exporter_controller.js#L348)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Shouldn't this be the fancy `for` loop syntax?
</details>
Done.

---

*[demos/blocklyfactory/block_exporter_controller.js, line 353 \[r3\]](https://reviewable.io:443/reviews/google/blockly/565#-KPUkr_dIZn7ZN-cOLxl:-KPWQZT8abLzPgNJZw9Y:b-6vo6aw) ([raw file](https://github.com/google/blockly/blob/80edc19af46e27aef6c9095aaad6bc5396c9207d/demos/blocklyfactory/block_exporter_controller.js#L353)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> This `else if` will only let the following code pass through once. Is that intended?
</details>
completely removed the warning for standard block types and this line. Now I am only checking for blocks that aren't in lib and are not standard blocks and am storing each of these unstored custom blocks in an array.

---

*[demos/blocklyfactory/block_exporter_controller.js, line 378 \[r3\]](https://reviewable.io:443/reviews/google/blockly/565#-KPUlMIqLktpi7RbO0sl:-KPWR9o08is3sa0S0H2o:bof00ly) ([raw file](https://github.com/google/blockly/blob/80edc19af46e27aef6c9095aaad6bc5396c9207d/demos/blocklyfactory/block_exporter_controller.js#L378)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Would these alerts make more sense when the user clicks export rather than when adding blocks to the workspace?
</details>
Discussed this--no longer warning for standard block types, still have one warning for unstored custom blocks.

---

*[demos/blocklyfactory/block_exporter_controller.js, line 381 \[r3\]](https://reviewable.io:443/reviews/google/blockly/565#-KPUkNoomH7XHV9L2Acf:-KPWQw68Znz6Scpd1jxZ:b-896fix) ([raw file](https://github.com/google/blockly/blob/80edc19af46e27aef6c9095aaad6bc5396c9207d/demos/blocklyfactory/block_exporter_controller.js#L381)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Remove line.
</details>
Done.

---

*[demos/blocklyfactory/block_exporter_controller.js, line 383 \[r3\]](https://reviewable.io:443/reviews/google/blockly/565#-KPUkPlZXs1BJiML_6Cu:-KPWR2x9mp0CG3n4rIzB:b-896fix) ([raw file](https://github.com/google/blockly/blob/80edc19af46e27aef6c9095aaad6bc5396c9207d/demos/blocklyfactory/block_exporter_controller.js#L383)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Add line above this.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/565)*

**Comment by evd2014** [comment]
:lgtm: with one nit 

---

Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[demos/blocklyfactory/block_library_storage.js, line 178 \[r5\]](https://reviewable.io:443/reviews/google/blockly/565#-KPn7Bu8l0mxnAqxlfQy:-KPn7Bu9BhnOu9LEzIzb:bd1geo0) ([raw file](https://github.com/google/blockly/blob/6ca4a61f7e7f75b24be9710efde8cf2493df7beb/demos/blocklyfactory/block_library_storage.js#L178)):*
> ```JavaScript
> BlockLibraryStorage.prototype.has = function(blockType) {
>   return this.blocks[blockType] ? true : false;
> };
> ```

Nit extra line here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/565#-:-KPn7Fgxj827ULb8zkK0:b2dc52k)*

**Comment by quachtina96** [comment]
Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[demos/blocklyfactory/block_library_storage.js, line 178 \[r5\]](https://reviewable.io:443/reviews/google/blockly/565#-KPn7Bu8l0mxnAqxlfQy:-KPnMNiWLd6yhPdPa1uy:b-896fix) ([raw file](https://github.com/google/blockly/blob/6ca4a61f7e7f75b24be9710efde8cf2493df7beb/demos/blocklyfactory/block_library_storage.js#L178)):*
<details><summary><i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>
> Nit extra line here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/565)*

**Comment by picklesrus** [comment]
One quick question. See below

---

Review status: 0 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[demos/blocklyfactory/block_exporter_controller.js, line 351 \[r5\]](https://reviewable.io:443/reviews/google/blockly/565#-KPnRwdKLsFjkfVNwxwL:-KPnRwdLPBgyVU2nlFmk:b-pnm3m4) ([raw file](https://github.com/google/blockly/blob/6ca4a61f7e7f75b24be9710efde8cf2493df7beb/demos/blocklyfactory/block_exporter_controller.js#L351)):*
> ```JavaScript
>     if (storedBlockTypes.indexOf(blockType) != -1) {
>       sharedBlockTypes.push(blockType);
>     } else if (BlockFactory.standardBlockTypes.indexOf(blockType) == -1) {
> ```

I forget, do you warn if someone tries to make a block with the same name as one of the standard blocks?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/565#-:-KPnSm3KEDWXyy91Hv3X:b-hv8yyu)*

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/565#-:-KPoJymbwYCMHdL26G6q:bnfp4nl)*

**Comment by quachtina96** [comment]
Review status: 0 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[demos/blocklyfactory/block_exporter_controller.js, line 351 \[r5\]](https://reviewable.io:443/reviews/google/blockly/565#-KPnRwdKLsFjkfVNwxwL:-KPoitw4eS6t26154Nuj:b-fxm77r) ([raw file](https://github.com/google/blockly/blob/6ca4a61f7e7f75b24be9710efde8cf2493df7beb/demos/blocklyfactory/block_exporter_controller.js#L351)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> I forget, do you warn if someone tries to make a block with the same name as one of the standard blocks?
</details>
yes i do! this warning was for if someone wants to add all used blocks but they've used standard blocks that cant be selected for exporter. I got rid of this warning though because it doesn't seem necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/565)*

**Comment by picklesrus** [comment]
One last question, otherwise LGTM

---

Review status: 0 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[demos/blocklyfactory/block_exporter_controller.js, line 351 \[r5\]](https://reviewable.io:443/reviews/google/blockly/565#-KPnRwdKLsFjkfVNwxwL:-KPom8ZDWJnukU8hHoW0:bxpgo65) ([raw file](https://github.com/google/blockly/blob/6ca4a61f7e7f75b24be9710efde8cf2493df7beb/demos/blocklyfactory/block_exporter_controller.js#L351)):*
<details><summary><i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>
> yes i do! this warning was for if someone wants to add all used blocks but they've used standard blocks that cant be selected for exporter. I got rid of this warning though because it doesn't seem necessary.
</details>
Do you allow it? I was more thinking of this in the context of your if/else if and if it was possible for the block to be in both lists.  If so, would it be better for this to be 2 sequential if statements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/565#-:-KPonIp-M6-CaPA7TafM:b-ok83f)*

**Pull request merged**
