### PR TITLE
Restore Translations

### PR DESCRIPTION
**Pull request by NeilFraser**
This PR restores 2/3rds of the translations destroyed by PR #1163.

### CODE REVIEW

**Comment by NeilFraser** [comment]
When this lands, Wikitranslate should be informed of the incoming changes.

**Comment by RoboErikG** [comment]
#1163 added all of those Strings. I think we lost the translations more recently.

**Comment by RoboErikG** [comment]
It looks like the last merge to master accidentally used the wrong set of strings for these files. #1243 should be reviewed for more bad string merges.

**Comment by rachel-fenichel** [comment]
"translations destroyed by #1163":

Before #1163, the append text block had two separate messages:
`Blockly.Msg.TEXT_APPEND_TO = "to";`
`Blockly.Msg.TEXT_APPEND_APPENDTEXT = "append text"; `

After #1163, this is one message:
`Blockly.Msg.TEXT_APPEND_TITLE = "to %1 append text %2"; `

As far as the translation framework is concerned, these are completely different things.  So it chucked all previous translations and went back to using english for the append text block.

For this change (#1396) Neil went through and combined the old translations of TEXT_APPEND_TO and TEXT_APPENDTEXT to make approximations of TEXT_APPEND_TITLE.  They may not be 100% correct, but at least we're not just throwing out work done by translators before.

@translatewiki @Nikerabbit I will let you know when this change hits master, since it's a bigger-than-usual change to the JSON from our side.

------------------
This change also gets rid of a bunch of English that made it into Tagalog by accident, which gives it a chance to be retranslated.  The Tagalog blocks will look the same, since by default we use English if there was no translation.

**Comment by rachel-fenichel** [comment]
LG, and I'll merge into develop when travis is happy.  Leave the branch open and I'll see about cherry-picking it into master next week.

**Comment by NeilFraser** [comment]
> They may not be 100% correct, but at least we're not just throwing out work done by translators before.

Just to clarify, they do display *exactly* what was there before.  So at no point is this a regression.

**Pull request merged**
