### PR TITLE
Validate newValue parameter in setValue

### PR DESCRIPTION
**Pull request by asunwoo98**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

#2169 

### Proposed Changes

Validates the input value in setValue of field.js by using callValidator function

### Reason for Changes

Proposed change in #2169 

### Test Coverage

Tested on:

### Additional Information

Might potentially introduce redundancies in subclasses?

### CODE REVIEW

**Comment by RoboErikG** [comment]
Hrmm...it looks like the test failures are because Math.min returns NaN if one of the inputs is undefined, and field_number doesn't set min_ and max_ until after the initial value is set, which causes the value to be set as NaN and the test to fail.

To fix, either FieldNumber needs to set min_ to -Infinity and max_ to Infinity before doing anything else or setConstraints needs to be called before the super's constructor is called.

**Comment by asunwoo98** [comment]
Hi,

Sorry for the slow fix. I made the constructor set the constraints before doing any calls as you suggested, but it came out with new errors with 2 similar traces, one copied below. 

`10:21:04.993  ERROR in test_fieldnumber_constructor
this.size_ is undefined
Blockly.Field.prototype.forceRerender@file:///Users/antonysunwoo/blockly/core/field.js:550:3
Blockly.Field.prototype.setText@file:///Users/antonysunwoo/blockly/core/field.js:538:3
Blockly.FieldTextInput.prototype.setText@file:///Users/antonysunwoo/blockly/core/field_textinput.js:141:3
Blockly.Field.prototype.setValue@file:///Users/antonysunwoo/blockly/core/field.js:591:3
Blockly.FieldTextInput.prototype.setValue@file:///Users/antonysunwoo/blockly/core/field_textinput.js:119:5
Blockly.FieldNumber.prototype.setConstraints@file:///Users/antonysunwoo/blockly/core/field_number.js:87:3
Blockly.FieldNumber@file:///Users/antonysunwoo/blockly/core/field_number.js:49:3
test_fieldnumber_constructor@file:///Users/antonysunwoo/blockly/tests/jsunit/field_number_test.js:29:15
10:21:04.993  test_fieldnumber_constructor : FAILED (run individually)`

I fixed this by defining this.size_ in FieldNumber's constructor like it is defined in Field, but maybe this could be refactored as well?

I also noticed that item in setValue are validated in FieldTextInput now as well as Field.js, that may be redundant as well?

Thank you for the help with debugging! Wasn't really sure what I was looking at.

**Comment by RoboErikG** [comment]
I played around with it too and it looks like my second fix suggestion worked without breaking anything (defining min and max to -Infinity/Infinity). I updated the comment to remove the suggestion that doesn't work about 20 minutes after first making it, but it sounds like I should have sent an additional update. 

Could you go with just the min_/max_ fix instead? I'm not sure what other side effects there might be from requesting a rendering update before the field is fully initialized.

**Comment by asunwoo98** [comment]
I implemented that change like you suggested and it works, but this seems very redundant. 

I found the issue with just using setConstraint first. Right now setConstraint revalidates the current value since currently the constraints are set after the value is set. However if that line is taken out from setConstraints, it never calls setValue and therefore never requests a render update before the field is fully initialized. What do you think?

**Comment by RoboErikG** [comment]
Ditto. I'm trying to figure out why Travis is failing but locally the test is fine.

**Comment by RoboErikG** [comment]
huh...after updating my local copy it now fails locally as well.

**Comment by RoboErikG** [comment]
Oh, this PR added a new property dependency in the validator: https://github.com/google/blockly/pull/2384

Alright, time for a less brittle approach. Let's add a private constraintsSet_ property to field_number, make setConstraints set that property to true, and change classValidator to return if (text === null || !constrantsSet_)

**Comment by asunwoo98** [comment]
Wanted to test out my idea

**Comment by asunwoo98** [comment]
Seems to work as well. Should I implement your solution anyway?

**Comment by RoboErikG** [comment]
Oh, that makes sense. I think I misunderstood your proposed solution. Your way is fine, just remove the commented lines. =)

**Comment by asunwoo98** [comment]
Nice. Sorry I find explaining hard sometimes. Thanks for taking a look!

**Comment by RoboErikG** [comment]
Small note, this will cause the current value to not be re-validated if the constraints change, but that seems like a less common issue so I went ahead and merged it.

**Pull request merged**
