### PR TITLE
feat: Added blocklyTrashcanFlyout CSS class

### PR DESCRIPTION
**Pull request by ChaitanyaYeole02**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Feature Request #8342

### Proposed Changes
Add a blocklyTrashcanFlyout CSS class to the flyout if it is used by the trashcan

### CODE REVIEW

**Review by BeksOmega — APPROVED** [review]
This looks great! Thank you for the fix. Once CI passes I'll get this merged =)

**Comment by ChaitanyaYeole02** [comment]
@BeksOmega When I am running `npm run format:check`
image
I am receving no errors.

What am I missing?

**Comment by BeksOmega** [comment]
Hello, when I pull down your branch and run the command I get the same error as we're seeing on CI. Perhaps you have a different version of prettier installed? Can you run `npn ci` in the console and then `npm run format`?

**Comment by ChaitanyaYeole02** [comment]
> Hello, when I pull down your branch and run the command I get the same error as we're seeing on CI. Perhaps you have a different version of prettier installed? Can you run `npn ci` in the console and then `npm run format`?

`npm ci` gives me few deprecated warning and few vulnerabilities.
`npm run format` this still gives me no errors

**Comment by BeksOmega** [comment]
Thank you again!

**Pull request merged**
