### PR TITLE
Workspace Factory

### PR DESCRIPTION
**Pull request by evd2014**
Workspace factory helps developers configure their workspace by allowing them to drag blocks into the workspace to add them to their toolbox. 
Current features:
-  supports categories or a single flyout of blocks
- updates a preview workspace automatically
- imports toolbox XML already written
- exports toolbox XML to a file
- prints toolbox XML to the console
- imports a standard Blockly category
- supports shadow blocks (allowing the user to move shadow blocks and toggle between shadow blocks and normal blocks), disabled blocks, block groups
- allows the user to add/move/delete/rename/color categories and separators.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/522)

### CODE REVIEW

**Comment by evd2014** [comment]
I signed it!

**Comment by rachel-fenichel** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[demos/blocklyfactory/workspacefactory/standard_categories.js, line 1 \[r1\]](https://reviewable.io:443/reviews/google/blockly/522#-KOlynNImCbmEfZcogfF:-KOlynNImCbmEfZcogfG:bfqg1g2) ([raw file](https://github.com/google/blockly/blob/8d46da553c6bf7490df24048c3027040cb187bc1/demos/blocklyfactory/workspacefactory/standard_categories.js#L1)):*
> ```JavaScript
> /**
> ```

Add @license block to all js files (see my comment on tina's pr)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/522)*

**Comment by evd2014** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[demos/blocklyfactory/workspacefactory/standard_categories.js, line 1 \[r1\]](https://reviewable.io:443/reviews/google/blockly/522#-KOlynNImCbmEfZcogfF:-KOpJzD77tIwdfm0zz2o:b-896fja) ([raw file](https://github.com/google/blockly/blob/8d46da553c6bf7490df24048c3027040cb187bc1/demos/blocklyfactory/workspacefactory/standard_categories.js#L1)):*
<details><summary><i>Previously, rachel-fenichel wrote…</i></summary>
> Add @license block to all js files (see my comment on tina's pr)
</details>
Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/522)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/522#-:-KOpbTInculaQRB7jB6h:bnfp4nl)*

**Pull request merged**
