### PR TITLE
Skc memory leaks pr

### PR DESCRIPTION
**Pull request by winstonwolff**
Hello Neil & other contributors—

I believe I've found a few more memory leaks.

—Winston

### CODE REVIEW

**Comment by NeilFraser** [comment]
Looks great.  I'm going to wait a couple of days (I hope) for PR 125 to land, since that changes a lot of stuff and I don't want anything to fall between the cracks.

**Comment by winstonwolff** [comment]
I have a few more changes coming too. I'll take a look at PR 125 to see if we are duplicating effort.

**Comment by NeilFraser** [comment]
The zooming code has landed and I've merged this PR manually.  Took a different approach in a few cases.

**Comment by winstonwolff** [comment]
Great, thanks.

I'm curious why you use push.apply instead of push directly, e.g. `Array.prototype.push.apply(this.eventWrappers_, wrapper)`?

**Comment by NeilFraser** [comment]
wrapper is a list of event blobs (usually just one, but several on multitouch devices).  eventWrappers_.push(wrapper) would result in a list of list of event blobs.  By using push.apply, the result is a list of event blobs.

var a = [];
a.push([1, 2, 3]);
a.push([4, 5, 6]);
a -> [[1, 2, 3], [4, 5, 6]]

var a = [];
Array.prototype.push.apply(a, [1, 2, 3]);
Array.prototype.push.apply(a, [4, 5, 6]);
a -> [1, 2, 3, 4, 5, 6]

**Pull request closed without merging**
