### PR TITLE
#1142 Replace tests/generator/*.xml with .js

### PR DESCRIPTION
**Pull request by moogacs**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Test Coverage

Tested on:

### CODE REVIEW

**Comment by moogacs** [comment]
I signed it!

**Comment by rachel-fenichel** [comment]
Hi @moogacs,

It looks like the generator tests no longer pass (see Travis, above).   Please fix those and ping when you're ready for review.

**Comment by moogacs** [comment]
@rachel-fenichel  the last PR it's working fine locally, but what travis i think  need to rebuild !

**Comment by rachel-fenichel** [comment]
The generator test are also failing locally.  And travis would not need a rebuild for this change.

**Comment by moogacs** [comment]
@rachel-fenichel  I miss understand it now! I have tested it locally and it's working

**Comment by rachel-fenichel** [comment]
I tested it locally and it's failing, as well as on Travis.  It looks like you just replaced every use of 'xml' with 'js' without checking what they're for.

**Pull request closed without merging**
