### PR TITLE
fix: incorrect blockchange firing

### PR DESCRIPTION
**Pull request by devbysn**
## The basics

- [ x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes : https://github.com/google/blockly/issues/7448

### Proposed Changes

Removes the unwanted BlockChange event during jsonInit.

Screenshot from 2023-09-15 11-09-45

### Reason for Changes

```
    if (json['inputsInline'] !== undefined) {
      eventUtils.disable();
      this.setInputsInline(json['inputsInline']);
      eventUtils.enable();
    }
```

disabling the event while creating will fix it.

### CODE REVIEW

**Comment by devbysn** [comment]
Hello @BeksOmega ,

can you check, i've disabled the BlockChange event and verified it.

**Comment by BeksOmega** [comment]
Hello @devbysn I still need to manually test, but this change LGTM =) Can you sign the CLA so I can get this merged? Thank you for your work on this!

**Comment by devbysn** [comment]
Hey @BeksOmega ,

i've signed the CLA.

but idk why some tests are failing.

can you guide?
thanks :)

**Comment by BeksOmega** [comment]
Hiya @devbysn You need to run `npm run format` in the root `blockly` directory, and then commit those changes! After that this change should be good to go =)

**Review by BeksOmega — APPROVED** [review]
Manually verified this change looks good.

**Comment by devbysn** [comment]
I've done the```npm run format```, can you check now @BeksOmega ?

**Comment by BeksOmega** [comment]
This looks great @devbysn :D Thank you so much for your contribution! If you'd like to continue contributing let me know and I can recommend something! Or you can pick whatever you find interesting out of the backlog =)

**Pull request merged**
