### PR TITLE
Renamed Blockly.connectionTypes to Blockly.ConnectionType for consistency

### PR DESCRIPTION
**Pull request by himanshujaidka**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

#### Behavior Before Change
 Blockly.connectionTypes

Additional context

#### Behavior After Change
Blockly.ConnectionType

Additional context

### Reason for Changes
Renamed Blockly.connectionTypes to Blockly.ConnectionType for consistency.

Additional context

issue linked #5156

### CODE REVIEW

**Comment by himanshujaidka** [comment]
@googlebot I consent.

**Comment by himanshujaidka** [comment]
@googlebot I consent

**Comment by BeksOmega** [comment]
Hi @himanshujaidka thank you so much for putting up this PR! This issue is actually part of a larger refactor we're doing, so I'm not sure which branch this is supposed to go into, or if we want to wait to put this in.

I've put it on the internal meeting docs to discuss next week. So it may be a bit before I have info on this =)

If you want something else to work on in the mean time, https://github.com/google/blockly/issues/4993 looks like a good starter issue.

Sorry about the wait :/ If there's anything I can help you with don't hesitate to ask! Thank you again :D

**Comment by himanshujaidka** [comment]
@BeksOmega, Thanks mam for your support I am looking into the mentioned issue, but please guide me that how to set up this app on the local system 😅 I have tried and read all the documentation related to this but am unable to setup this on my local machine.

**Comment by BeksOmega** [comment]
> And I think to test the #4993 issue we need macOS but I have windows

Oh whoops my bad! Yeah that is not going to work haha. If you're on Windows we would actually love help with #5000. Or if you want to do some more coding #4784 might be fun. Just so you know, anything marked [help wanted](https://github.com/google/blockly/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) is fair game to work on =)

---

But I also have good news with regard to this PR! The team talked it over yesterday, and we would love to merge this PR... but into the `goog_module` branch :/ So if you still want to work on this issue, you have two options:
1) Attempt to `git rebase` your `UpperCamelCase` branch onto `goog_module`. But you'll probably get a lot of merge conflicts if you try this method :/
2) Redo your work off of the `goog_module` branch instead of `develop`. This means you won't get merge conflicts, but it sucks because you'll be redoing work :/

I'm happy to help with either method if you run into any trouble! But if it sounds like a pain, feel free to just close this PR and work on a different issue as well =)

Sorry changing things on you again haha. But we do really appreciate you contributing! Getting bugs like this fixed is so helpful =)

**Comment by himanshujaidka** [comment]
> Sorry changing things on you again haha. But we do really appreciate you contributing! Getting bugs like this fixed is so helpful =)

@BeksOmega okay I will create a new pr against `goog_module`

**Pull request closed without merging**
