### PR TITLE
feat: Add a blocklyShadow class

### LINKED ISSUE #8262: Add a `blocklyShadow` CSS class to shadow blocks' root SVG
In the [common PathObject's `updateShadow_` method](https://github.com/google/blockly/blob/17dfa462a357b553523393145c9d5045023e627b/core/renderers/common/path_object.ts#L187), call setClass to add a `blocklyShadow` class to the svgRoot, or remove the class.

The PR to fix this should be made against the rc/v12.0.0 branch.

To work on this issue, please comment below asking to be assigned.

### PR DESCRIPTION
**Pull request by devesh-2002**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #8262,
### Proposed Changes
Added a blocklyShadow CSS class to shadow blocks' root SVG

### Additional Information
Please let me know, if any changes are needed. 
Also, I am not sure why is it showing 4 commits, I only added in the `path_object.ts`

### CODE REVIEW

**Review by BeksOmega — CHANGES_REQUESTED** [review]
Hello! To remove the commits that aren't yours, you can rebase your branch on top of the latest `rc/v12.0.0` branch.  This will remove any commits that were added to `rc/v12.0.0` since you created your branch.

Here are the steps to do that:

1. **Fetch the latest changes from `rc/v12.0.0`:**

   ```bash
   git fetch upstream rc/v12.0.0
   ```

2. **Checkout your branch:**

   ```bash
   git checkout [your-branch-name]
   ```

3. **Start an interactive rebase:**

   ```bash
   git rebase -i upstream/rc/v12.0.0
   ```

4. **In the editor that opens, identify the commits that aren't yours.** These are likely the ones at the top of the list. 

5. **Change the word `pick` to `drop` for each commit you want to remove.** 

6. **Save and close the editor.**

8. **Force push your changes to your branch:** Note that force pushing is a dangerous operation because it overwrites commit history, so if you dropped the wrong commits you could lose work.

   ```bash
   git push -f origin [your-branch-name]
   ```

Once you've done this, the PR should only contain your commits.

Let me know if you have any questions or run into any issues!

**Comment by devesh-2002** [comment]
@BeksOmega Thanks a lot for the suggestion. It worked!
Please let me know if there are any further changes

**Comment by devesh-2002** [comment]
> Hiya @devesh-2002 Can you run `npm run format` in the root directory of `blockly` to fix the formatting failure?

Done. `npm run format` seems to have made changes in many other files, should I push those also? (I have pushed only 1 file right now, where I had made the changes)

**Review by BeksOmega — APPROVED** [review]
Just pushing the changes to your files is perfect! Thank you for the fix this looks great =)

**Pull request merged**
