### PR TITLE
fix: update setShadow TSDoc for Block and BlockSvg

### PR DESCRIPTION
**Pull request by systemc12ashe**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes https://github.com/google/blockly/issues/7636

### Proposed Changes

Updates TSDocs for `setShadow` according to issue.

### CODE REVIEW

**Comment by BeksOmega** [comment]
Sweet thank you for the fix! Just one thing before merging: Can you change the docs to line wrap at column 80?

I'm surprised the linter didn't catch this, @maribethb as a heads up.

**Comment by systemc12ashe** [comment]
I forgot the space at the end of the line, and Prettier didn't like that, haha! Just fixed that.

**Review by BeksOmega — APPROVED** [review]
Sweet, this looks perfect thank you so much!

**Comment by maribethb** [comment]
> I'm surprised the linter didn't catch this,

The linter no longer cares about line length; it's prettier's job to care about that. running the formatter should autofix this.

**Comment by systemc12ashe** [comment]
> The linter no longer cares about line length; it's prettier's job to care about that. running the formatter should autofix this.

Even when I did run Prettier on the files, it didn't catch my line length issue. Not sure if I did something incorrectly, but I made sure it was using the prettier config

**Pull request merged**
