### PR TITLE
fix: Multiline field not correctly size in parent block when copy/paste or load.

### PR DESCRIPTION
**Pull request by yamadayutaka**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [x] I ran `npm run format` and `npm run lint`

### Resolves

- #6165 
- #6071 

### Proposed Changes

When loading a block with input blocks or next blocks, render the blocks last.

#### Behavior Before Change

Multiline field not correctly size in parent block when copy/paste or load.

#### Behavior After Change

Multiline field correctly size in parent block when copy/paste or load.

### Reason for Changes

These issues are from v7.
So I modified the processing order to be similar for v6.

https://github.com/google/blockly/blob/6.20210701.0/core/xml.js#L564-L569

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
@BeksOmega can you take a look at the serialization changes?

**Comment by rachel-fenichel** [comment]
Hi @yamadayutaka--sorry for the delay, but the person who knows the serialization code best is currently out of office. We haven't forgotten about your change.

**Comment by BeksOmega** [comment]
Hi @yamadayutaka ! Thank you so much for looking into this :D Sorry it took me so long to get back to you!

I was wondering, instead of refactoring the serialization order, could we try using [getFastTextWidth](https://github.com/google/blockly/blob/55a707662409a8829416e38e7655bb5d009aca39/core/utils/dom.js#L333) in [updateSize_](https://github.com/google/blockly/blob/55a707662409a8829416e38e7655bb5d009aca39/core/field_multilineinput.js#L286) for the FieldMultilineInput? This is what the [FieldTextInput uses](https://github.com/google/blockly/blob/55a707662409a8829416e38e7655bb5d009aca39/core/field.js#L739) (via Field), which is why it doesn't run into the same problem.

I haven't looked at the serialization-based solution in depth, but I would like to try fixing the field itself first if possible.

**Comment by yamadayutaka** [comment]
Hi @BeksOmega,
Thank you for reviewing my PR.
I will try it.

**Comment by yamadayutaka** [comment]
I've confirmed that what you suggested works as expected, so I created another PR.
#6461

**Comment by BeksOmega** [comment]
Closing in favor of #6461

**Pull request closed without merging**
