### PR TITLE
Simplify RTL handling of '<' and '>'.

### PR DESCRIPTION
**Pull request by NeilFraser**
Tested in Playground and RTL demo.

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
I'd rather see a `Blockly.Msg` entry for the label. I know this adds four string to the string table for all languages, but it seems like the more appropriate solution.

**Comment by NeilFraser** [comment]
Tested on Firefox and Chrome for Mac.

Adding these strings to the string table would solve the problem from an engineering point of view.  Then it just becomes an issue of educating non-technical translators when to type [right-to-left marks](https://en.wikipedia.org/wiki/Right-to-left_mark) in the translation console.  Oh, and we also need to get the Iraqi translators to agree with the Iranian translators about how math works.

This is a rabbit hole I don't think we want to go down.

**Comment by NeilFraser** [comment]
BTW, here's a fun read if one does want to peek down the rabbit hole:
  https://www.w3.org/TR/arabic-math/

**Comment by AnmAtAnm** [comment]
Issues such as Arabic variants are exactly why I think this should be a localization issue. It appears we already support regional variants (e.g., [be](https://github.com/google/blockly/blob/master/msg/json/be.json) vs [be-tarask](https://github.com/google/blockly/blob/master/msg/json/be-tarask.json)).

While your solution is simpler than the previous code, it still encodes a preference into the code that we shouldn't dictating.

Thankfully, we're not attempting to translate mathematical equations in whole, the way MathML is.

**Comment by AnmAtAnm** [comment]
Staging site for testing other browsers and devices: http://anmatanm.github.io/blockly/demos/code/index.html?lang=fa

Expected rendering (screenshot of previous version):
screen shot 2018-05-07 at 2 36 18 pm
screen shot 2018-05-07 at 2 37 33 pm

**Comment by AnmAtAnm** [comment]
Tested in Android Oreo Chrome, iOS 9.3.5 Safari, Windows 10 Edge.

**Pull request merged**
