### PR TITLE
style -> categorystyle change

### PR DESCRIPTION
**Pull request by amber-cd**
## The basics

- [ x ] I branched from develop
- [ x ] My pull request is against develop
- [ x ] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

https://groups.google.com/forum/?pli=1#!topic/blockly/Vsi9UVxKRRQ
### Proposed Changes

Changes the category 'style' prop to 'categorystyle'.

### Reason for Changes

This was done to avoid issues with validation for HTML style props and style prop validation when nested in React environments

### Test Coverage

I updated playground.html with the changes and verified that it worked.

Tested on:
* Desktop Chrome

### CODE REVIEW

**Comment by alschmiedt** [comment]
I don't think the files added from the build are necessary. If you could remove those so that it is just the toolbox and playground files then lgtm.

**Comment by amber-cd** [comment]
Oh, I thought it was standard procedure to include the build files. I need official go-ahead from my workplace to sign the CLA (I don't anticipate any problem with it; it's just bureaucratic stuff to make it official) but I'll go ahead and make that update so it'll be good to go at that point.

**Comment by amber-cd** [comment]
Done. Should be good to go as soon as the CLA is ready. Sorry about the messy commit history there... I was having a bit of weirdness with blockly_compressed refusing to reset to the version from develop and had to try a few things.

**Comment by amber-cd** [comment]
Just signed the CLA! Sorry for the delay. This should be good to go now.

**Comment by alschmiedt** [comment]
I think we generally only include build files if we have added or changed one of the dependencies : ) LGTM and congrats on your first PR!

**Comment by rachel-fenichel** [comment]
When to change build files:
1. When doing a rebuild for release
2. When adding or removing `goog.require` and `goog.provide` calls
3. When changing/testing compressed code specifically
4. When travis breaks because blockly_uncompressed is out of date (usually related to item 2)

**Pull request merged**
