### PR TITLE
fix: change assertFieldValue in test helpers to use deepEqual

### LINKED ISSUE #6180: Change assertFieldValue in test helpers to use deepEqual
**Describe the bug**

[assertFieldValue](https://github.com/google/blockly/blob/b92cbd3b915ad99659ed2ad58adf1a4950fbbf79/tests/mocha/test_helpers/fields.js#L72) doesn't work for fields that return object values (including arrays).

**Expected behavior**

The test helper should work with fields that return objects/arrays.

**Additional context**

Should be able to fix this by changing it to use [chai.assert.deepEquals](https://www.chaijs.com/api/assert/#method_deepequal)

### PR DESCRIPTION
**Pull request by Samridhi-98**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [x] I ran `npm run format` and `npm run lint`

### Resolves

Fixes #6180 

#### Changes Done

- Updated `tests/mocha/test_helpers/elds.js`

### CODE REVIEW

**Comment by Samridhi-98** [comment]
Hey @BeksOmega, I got stuck with the following error, please help me out. 

Screenshot 2023-01-05 at 7 28 22 PM

**Comment by BeksOmega** [comment]
Hiya @Samridhi-98! `deepEqual` uses an `===` check, so numbers and stringified numbers are no longer equivalent :/ So to get this working, you'll need to update the individual tests that are failing.

**Comment by BeksOmega** [comment]
@Samridhi-98 I'm a bit confused why the CLA is failing, because you've contributed before. Did you use a dif email for these commits?

**Comment by Samridhi-98** [comment]
> @Samridhi-98 I'm a bit confused why the CLA is failing, because you've contributed before. Did you use a dif email for these commits?

I recently changed my laptop, so I guess its failing because of that, Though I set the git configuration. Should I open new PR?

**Pull request closed without merging**
