### PR TITLE
Complete revision of German translation

### PR DESCRIPTION
**Pull request by zgtm**
We want to use Blockly for a new learning program we are setting up here in Germany for young programming-beginners.

We found that the German translation was mostly imprecise, inconsistent and sometimes misleading. Thus, I revised it completely. This pull request contains all the suggested improvements we are going to use for our learning program.

If a CLA is necessary for translation work, I will be able to provide that as well …

### CODE REVIEW

**Comment by zgtm** [comment]
I signed it!

**Comment by RoboErikG** [comment]
Hi zgtm,

Thanks for doing a pass on this. We pull all of our translations through [translate wiki](https://developers.google.com/blockly/hacking/translating) and we don't have a good way to maintain changes directly. If you have the time we'd really appreciate submitting there.

We'll also leave this open as a reference for other translators, thanks!

**Comment by RoboErikG** [comment]
Comments from someone who used to write German translations for apps. My apologies if I've copied them to the wrong spot anywhere.

<details><summary><i>Previously, RoboErikG wrote…</i></summary>
> Hi zgtm,
> 
> 
> 
> Thanks for doing a pass on this. We pull all of our translations through [translate wiki](https://developers.google.com/blockly/hacking/translating) and we don't have a good way to maintain changes directly. If you have the time we'd really appreciate submitting there.
> 
> 
> 
> We'll also leave this open as a reference for other translators, thanks!
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 40 unresolved discussions.

---

*[msg/json/de.json, line 14 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQfnuZ5coVSgAUqbDe:-KKQfnuZ5coVSgAUqbDf:2100407179) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L14)):*
> ```JSON
> 	},
> 	"VARIABLES_DEFAULT_NAME": "etwas",
> 	"TODAY": "Heute",
> ```

Only capitalized at sentence beginning. True for this item?

---

*[msg/json/de.json, line 22 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQfvR1bYosRJAfPVrK:-KKQfvR1bYosRJAfPVrL:-1496218817) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L22)):*
> ```JSON
> 	"DELETE_BLOCK": "Block löschen",
> 	"DELETE_X_BLOCKS": "Block %1 löschen",
> 	"DELETE_ALL_BLOCKS": "Alle %1 Bausteine löschen?",
> ```

Should be "Blöcke" for consistency with other uses of "Block" translations.

---

*[msg/json/de.json, line 34 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQgEZmkDozC1Sqjmtp:-KKQgEZmkDozC1Sqjmtq:-2033510975) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L34)):*
> ```JSON
> 	"REDO": "Wiederholen",
> 	"CHAT": "Chatte mit unserem Mitarbeiter durch Eingeben von Text in diesen Kasten!",
> 	"AUTH": "Bitte autorisiere diese App zum Aktivieren der Speicherung deiner Arbeit und zum Teilen.",
> ```

Very awkward translation. Would replace this with "...um Deine Arbeit speichern und teilen zun k"onnen."

---

*[msg/json/de.json, line 35 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQgJCVw7he0mah58ez:-KKQgJCVw7he0mah58f-:-109191146) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L35)):*
> ```JSON
> 	"CHAT": "Chatte mit unserem Mitarbeiter durch Eingeben von Text in diesen Kasten!",
> 	"AUTH": "Bitte autorisiere diese App zum Aktivieren der Speicherung deiner Arbeit und zum Teilen.",
> 	"ME": "Ich",
> ```

Only capitalized when first word in sentence. True here?

---

*[msg/json/de.json, line 42 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQZdYUei7ixXFSPUHc:-KKQZdYUei7ixXFSPUHd:1257898077) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L42)):*
> ```JSON
> 	"RENAME_VARIABLE_TITLE": "Alle \"%1\" Variablen umbenennen in:",
> 	"COLOUR_PICKER_HELPURL": "https://de.wikipedia.org/wiki/Farbe",
> 	"COLOUR_PICKER_TOOLTIP": "Erzeugt eine Farbe aus der Palette.",
> ```

"Wählt" (selects) is probably better for the colour picker than "Creates".

---

*[msg/json/de.json, line 44 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQ_CrD7thSUK-bQcKZ:-KKQ_CrD7thSUK-bQcK_:-499318459) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L44)):*
> ```JSON
> 	"COLOUR_PICKER_TOOLTIP": "Erzeugt eine Farbe aus der Palette.",
> 	"COLOUR_RANDOM_TITLE": "zufällige Farbe",
> 	"COLOUR_RANDOM_TOOLTIP": "Erzeugt eine Farbe nach dem Zufallsprinzip.",
> ```

Ditto

---

*[msg/json/de.json, line 56 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQ_V2poNUNjGB4xcgT:-KKQ_V2poNUNjGB4xcgU:-1470917496) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L56)):*
> ```JSON
> 	"COLOUR_BLEND_COLOUR2": "und Farbe 2",
> 	"COLOUR_BLEND_RATIO": "im Verhältnis",
> 	"COLOUR_BLEND_TOOLTIP": "Vermischt 2 Farben mit konfigurierbaren Farbverhältnis (0.0 - 1.0).",
> ```

'konfigurierbarem' to make it singular

---

*[msg/json/de.json, line 64 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQ_ljHP3642VngsFqU:-KKQ_ljHP3642VngsFqV:2032378736) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L64)):*
> ```JSON
> 	"CONTROLS_WHILEUNTIL_OPERATOR_WHILE": "wiederhole solange",
> 	"CONTROLS_WHILEUNTIL_OPERATOR_UNTIL": "wiederhole bis",
> 	"CONTROLS_WHILEUNTIL_TOOLTIP_WHILE": "Führt die Anweisung solange aus wie die Bedingung wahr ist.",
> ```

Shorten to be more clear: "Führt die Anweisung aus solange die Bedingung wahr ist."

---

*[msg/json/de.json, line 65 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQ_wfmLDq7zrFrm1Gz:-KKQ_wfmLDq7zrFrm1H-:1726766106) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L65)):*
> ```JSON
> 	"CONTROLS_WHILEUNTIL_OPERATOR_UNTIL": "wiederhole bis",
> 	"CONTROLS_WHILEUNTIL_TOOLTIP_WHILE": "Führt die Anweisung solange aus wie die Bedingung wahr ist.",
> 	"CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL": "Führt die Anweisung solange aus wie die Bedingung unwahr ist.",
> ```

Better, avoid implied double negation: "Führt die Anweisung aus bis Bedingung wahr ist."

("until condition is true" is a more direct equivalent of the loop than "while condition is false").

---

*[msg/json/de.json, line 67 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQaGp_kjNkNfMenzsb:-KKQaGp_kjNkNfMenzsc:297383475) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L67)):*
> ```JSON
> 	"CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL": "Führt die Anweisung solange aus wie die Bedingung unwahr ist.",
> 	"CONTROLS_FOR_HELPURL": "https://de.wikipedia.org/wiki/For-Schleife",
> 	"CONTROLS_FOR_TOOLTIP": "Zählt die Variable \"%1\" von einem Startwert bis zu einem Zielwert und führt für jeden Wert eine Anweisung aus.",
> ```

change "Zielwert" to "Endwert"

("end value" rather than "target value").

---

*[msg/json/de.json, line 71 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQakYKLvxGU7CHABiF:-KKQakYKLvxGU7CHABiG:1394278940) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L71)):*
> ```JSON
> 	"CONTROLS_FOREACH_HELPURL": "https://de.wikipedia.org/wiki/For-Schleife",
> 	"CONTROLS_FOREACH_TITLE": "für jeden Wert %1 aus der Liste %2",
> 	"CONTROLS_FOREACH_TOOLTIP": "Führt eine Anweisung für jeden Wert in der Liste aus und setzte dabei die Variable \"%1\" auf den aktuellen Listenwert.",
> ```

"setzte" typo, should be "setzt"

---

*[msg/json/de.json, line 74 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQauNGcICw6cI1YkkE:-KKQauNH8_dweEK0_QK2:1859434340) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L74)):*
> ```JSON
> 	"CONTROLS_FLOW_STATEMENTS_HELPURL": "https://de.wikipedia.org/wiki/Kontrollstruktur",
> 	"CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK": "die Schleife abbrechen",
> 	"CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE": "sofort bei nächstem Schleifendurchlauf fortfahren",
> ```

"bei" -> "mit"

---

*[msg/json/de.json, line 78 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQbCDCOPyXv7yx62hu:-KKQbCDCOPyXv7yx62hv:591195990) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L78)):*
> ```JSON
> 	"CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE": "Diese Anweisung abbrechen und mit dem nächsten Schleifendurchlauf fortfahren.",
> 	"CONTROLS_FLOW_STATEMENTS_WARNING": "Warnung: Dieser Block sollte nur in einer Schleife verwendet werden.",
> 	"CONTROLS_IF_TOOLTIP_1": "Führt eine Anweisung aus, wenn eine Bedingung wahr ist.",
> ```

Might be better to use "falls" ("if"), rather than "wenn" ("if" & "when").

---

*[msg/json/de.json, line 89 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQbKlGQlsGjY8Zn9zb:-KKQbKlHAseREHTCNIQN:841125387) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L89)):*
> ```JSON
> 	"CONTROLS_IF_ELSE_TOOLTIP": "Eine sonst-Bedingung hinzufügen. Führt eine Anweisung aus, falls keine Bedingung zutrifft.",
> 	"LOGIC_COMPARE_HELPURL": "https://de.wikipedia.org/wiki/Vergleich_%28Zahlen%29",
> 	"LOGIC_COMPARE_TOOLTIP_EQ": "Ist wahr, wenn beide Werte gleich sind.",
> ```

As above, here and below "wenn" -> "falls"

---

*[msg/json/de.json, line 111 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQbRdA-gCYTl3Pw6oB:-KKQbRdA-gCYTl3Pw6oC:-1897304442) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L111)):*
> ```JSON
> 	"LOGIC_TERNARY_IF_TRUE": "wenn wahr",
> 	"LOGIC_TERNARY_IF_FALSE": "wenn unwahr",
> 	"LOGIC_TERNARY_TOOLTIP": "Überprüft eine Bedingung \"prüfe\". Wenn die Bedingung wahr ist, wird der \"wenn wahr\" Wert zurückgegeben, andernfalls der \"wenn unwahr\" Wert",
> ```

"wenn" -> "falls"

---

*[msg/json/de.json, line 149 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQbXRlFeq27-0A0TRz:-KKQbXRlFeq27-0A0TS-:-105660991) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L149)):*
> ```JSON
> 	"MATH_CHANGE_HELPURL": "https://de.wikipedia.org/wiki/Inkrement_und_Dekrement",
> 	"MATH_CHANGE_TITLE": "erhöhe %1 um %2",
> 	"MATH_CHANGE_TOOLTIP": "Addiert eine Zahl auf \"%1\".",
> ```

"auf" -> "zu"

---

*[msg/json/de.json, line 159 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQbg0ouf9DCC37jGqm:-KKQbg0ouf9DCC37jGqn:1801976692) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L159)):*
> ```JSON
> 	"MATH_ONLIST_TOOLTIP_SUM": "Ist die Summe aller Zahlen in einer Liste.",
> 	"MATH_ONLIST_OPERATOR_MIN": "Minimalwert der Liste",
> 	"MATH_ONLIST_TOOLTIP_MIN": "Ist die kleinst Zahl in einer Liste.",
> ```

Typo: "kleinste"

---

*[msg/json/de.json, line 169 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQbmwfjoJt2l1E5H_d:-KKQbmwfjoJt2l1E5H_e:675410446) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L169)):*
> ```JSON
> 	"MATH_ONLIST_TOOLTIP_MODE": "Findet die Werte mit dem häufigstem Vorkommen in der Liste.",
> 	"MATH_ONLIST_OPERATOR_STD_DEV": "Standardabweichung der Liste",
> 	"MATH_ONLIST_TOOLTIP_STD_DEV": "Ist die Standardabweichung aller Werte in der Liste",
> ```

Missing period.

---

*[msg/json/de.json, line 178 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQc1pKQec7SBdHy2GR:-KKQc1pKQec7SBdHy2GS:-986945041) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L178)):*
> ```JSON
> 	"MATH_CONSTRAIN_TOOLTIP": "Begrenzt eine Zahl auf den Wertebereich zwischen zwei anderen Zahlen (inklusiv).",
> 	"MATH_RANDOM_INT_HELPURL": "https://de.wikipedia.org/wiki/Zufallszahlen",
> 	"MATH_RANDOM_INT_TITLE": "ganzzahliger Zufallszahl zwischen %1 und %2",
> ```

Typo: "ganzzahlige" (no "r")

---

*[msg/json/de.json, line 179 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQbtZEVmo8s6dzdS1t:-KKQbtZEVmo8s6dzdS1u:-1264770217) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L179)):*
> ```JSON
> 	"MATH_RANDOM_INT_HELPURL": "https://de.wikipedia.org/wiki/Zufallszahlen",
> 	"MATH_RANDOM_INT_TITLE": "ganzzahliger Zufallszahl zwischen %1 und %2",
> 	"MATH_RANDOM_INT_TOOLTIP": "Erzeugt einen ganzzahligen Zufallszahl zwischen zwei Zahlen (inklusiv).",
> ```

Grammar: "eine ganzzahlige"

---

*[msg/json/de.json, line 189 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQcQgK8c7Q_bmj6ZOh:-KKQcQgLbQFB_zkArBZt:-1869846494) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L189)):*
> ```JSON
> 	"TEXT_JOIN_TOOLTIP": "Erstellt einen Text durch das Verbinden von mehreren Textelementen.",
> 	"TEXT_CREATE_JOIN_TITLE_JOIN": "verbinden",
> 	"TEXT_CREATE_JOIN_TOOLTIP": "Hinzufügen, entfernen und sortieren von Elementen.",
> ```

Why does JOIN include "entfernen" (remove) and "sortieren" (sort)?

---

*[msg/json/de.json, line 195 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQcaIRejcR5rA4NxW2:-KKQcaIRejcR5rA4NxW3:1973066494) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L195)):*
> ```JSON
> 	"TEXT_APPEND_TOOLTIP": "Text an die Variable \"%1\" anhängen.",
> 	"TEXT_LENGTH_TITLE": "Länge von %1",
> 	"TEXT_LENGTH_TOOLTIP": "Die Anzahl von Zeichen in einem Text. (inkl. Leerzeichen)",
> ```

Move period to end of string, after ")"

---

*[msg/json/de.json, line 197 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQcePEkU61ezHpEk02:-KKQcePEkU61ezHpEk03:-1572237714) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L197)):*
> ```JSON
> 	"TEXT_LENGTH_TOOLTIP": "Die Anzahl von Zeichen in einem Text. (inkl. Leerzeichen)",
> 	"TEXT_ISEMPTY_TITLE": "%1 ist leer",
> 	"TEXT_ISEMPTY_TOOLTIP": "Ist wahr, wenn der Text keine Zeichen enthält ist.",
> ```

'wenn'->'falls'

---

*[msg/json/de.json, line 212 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQckc5-WINuA_PnaDZ:-KKQckc5-WINuA_PnaD_:-1354732286) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L212)):*
> ```JSON
> 	"TEXT_CHARAT_RANDOM": "nehme zufälligen Buchstaben",
> 	"TEXT_CHARAT_TAIL": "",
> 	"TEXT_CHARAT_TOOLTIP": "Extrahiert einen Buchstaben von einer spezifizierten Position.",
> ```

"spezifizierten" -> "bestimmten"; same meaning, much simpler word.

---

*[msg/json/de.json, line 216 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQd10szgxOw9gCqKAF:-KKQd10szgxOw9gCqKAG:-1392079207) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L216)):*
> ```JSON
> 	"TEXT_GET_SUBSTRING_HELPURL": "http://publib.boulder.ibm.com/infocenter/lnxpcomp/v8v101/index.jsp?topic=%2Fcom.ibm.xlcpp8l.doc%2Flanguage%2Fref%2Farsubex.htm",
> 	"TEXT_GET_SUBSTRING_INPUT_IN_TEXT": "im Text",
> 	"TEXT_GET_SUBSTRING_START_FROM_START": "nehme Teil vom #ten Buchstaben",
> ```

"ab #tem" (means "from", rather than "of", which would imply piece of the character). Note change of "n" to "m", which is intentional and necessary.

---

*[msg/json/de.json, line 217 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQd6unyCnWKs7DkwqO:-KKQd6unyCnWKs7DkwqP:1375779879) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L217)):*
> ```JSON
> 	"TEXT_GET_SUBSTRING_INPUT_IN_TEXT": "im Text",
> 	"TEXT_GET_SUBSTRING_START_FROM_START": "nehme Teil vom #ten Buchstaben",
> 	"TEXT_GET_SUBSTRING_START_FROM_END": "nehme Teil vom #ten Buchstaben von hinten",
> ```

"ab #tem"

---

*[msg/json/de.json, line 218 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQd9X4I-ZQUwmSgyMn:-KKQd9X4I-ZQUwmSgyMo:1971151978) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L218)):*
> ```JSON
> 	"TEXT_GET_SUBSTRING_START_FROM_START": "nehme Teil vom #ten Buchstaben",
> 	"TEXT_GET_SUBSTRING_START_FROM_END": "nehme Teil vom #ten Buchstaben von hinten",
> 	"TEXT_GET_SUBSTRING_START_FIRST": "nehme Teil vom ersten Buchstaben",
> ```

"ab erstem"

---

*[msg/json/de.json, line 244 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQdRJWwfxn44Dory31:-KKQdRJWwfxn44Dory32:1943513727) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L244)):*
> ```JSON
> 	"LISTS_CREATE_WITH_INPUT_WITH": "erzeuge Liste mit",
> 	"LISTS_CREATE_WITH_CONTAINER_TITLE_ADD": "Liste",
> 	"LISTS_CREATE_WITH_CONTAINER_TOOLTIP": "Hinzufügen, entfernen und sortieren von Elementen.",
> ```

Text says, "add, remove, sort elements", which seems rather different from "CREATE"

---

*[msg/json/de.json, line 245 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQdWqVDQIle_EjScAu:-KKQdWqVDQIle_EjScAv:-1357019685) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L245)):*
> ```JSON
> 	"LISTS_CREATE_WITH_CONTAINER_TITLE_ADD": "Liste",
> 	"LISTS_CREATE_WITH_CONTAINER_TOOLTIP": "Hinzufügen, entfernen und sortieren von Elementen.",
> 	"LISTS_CREATE_WITH_ITEM_TOOLTIP": "Ein Element zur Liste hinzufügen.",
> ```

Text says, "add to list", not "CREATE"

---

*[msg/json/de.json, line 252 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQdaL_rjoOp2VBP22b:-KKQdaL_rjoOp2VBP22c:-1897304442) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L252)):*
> ```JSON
> 	"LISTS_LENGTH_TOOLTIP": "Die Anzahl von Elementen in der Liste.",
> 	"LISTS_ISEMPTY_TITLE": "%1 ist leer",
> 	"LISTS_ISEMPTY_TOOLTIP": "Ist wahr, wenn die Liste leer ist.",
> ```

"wenn" -> "falls"

---

*[msg/json/de.json, line 257 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQdflsLgKwAkJpRKLA:-KKQdflsLgKwAkJpRKLB:69182723) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L257)):*
> ```JSON
> 	"LISTS_INDEX_OF_FIRST": "suche erstes Auftreten von",
> 	"LISTS_INDEX_OF_LAST": "suche letztes Auftreten von",
> 	"LISTS_INDEX_OF_TOOLTIP": "Sucht die Position (index) eines Elementes in der Liste. Gibt 0 zurück, falls kein Element gefunden wurde.",
> ```

Capitalize "Index"

---

*[msg/json/de.json, line 277 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQe-X8IFP0BV58D6ro:-KKQe-X8IFP0BV58D6rp:1182000492) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L277)):*
> ```JSON
> 	"LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST": "Extrahiert und entfernt das letzte Element aus der Liste.",
> 	"LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM": "Extrahiert und entfernt ein zufälliges Element aus der Liste.",
> 	"LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START": "Entfernt das #1te Element von der Liste.",
> ```

"von" -> "aus"

---

*[msg/json/de.json, line 278 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQeHIbq6hP37kz16aV:-KKQeHIbq6hP37kz16aW:1182620151) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L278)):*
> ```JSON
> 	"LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM": "Extrahiert und entfernt ein zufälliges Element aus der Liste.",
> 	"LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START": "Entfernt das #1te Element von der Liste.",
> 	"LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END": "Entfernt das #1te Element von Ende der Liste.",
> ```

"von" -> "vom"

---

*[msg/json/de.json, line 279 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQeKPmWyaNdrI3DzUP:-KKQeKPmWyaNdrI3DzUQ:-530955648) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L279)):*
> ```JSON
> 	"LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START": "Entfernt das #1te Element von der Liste.",
> 	"LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END": "Entfernt das #1te Element von Ende der Liste.",
> 	"LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST": "Entfernt das erste Element von der Liste.",
> ```

"aus"

---

*[msg/json/de.json, line 280 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQeLDC8SIAyt1TMCjG:-KKQeLDC8SIAyt1TMCjH:-530955648) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L280)):*
> ```JSON
> 	"LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END": "Entfernt das #1te Element von Ende der Liste.",
> 	"LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST": "Entfernt das erste Element von der Liste.",
> 	"LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST": "Entfernt das letzte Element von der Liste.",
> ```

"aus"

---

*[msg/json/de.json, line 291 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQe_rkM-DdWD5-XXz0:-KKQe_rkM-DdWD5-XXz1:1009635067) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L291)):*
> ```JSON
> 	"LISTS_SET_INDEX_TOOLTIP_SET_LAST": "Setzt das letzte Element in der Liste.",
> 	"LISTS_SET_INDEX_TOOLTIP_SET_RANDOM": "Setzt ein zufälliges Element in der Liste.",
> 	"LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START": "Fügt das Element an der angegebenen Position in der Liste ein.  #1 ist die erste Element.",
> ```

second "der" -> "die" and "die" -> "das"

---

*[msg/json/de.json, line 292 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQf7HKgtimAxfXl2Dd:-KKQf7HKgtimAxfXl2De:820398345) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L292)):*
> ```JSON
> 	"LISTS_SET_INDEX_TOOLTIP_SET_RANDOM": "Setzt ein zufälliges Element in der Liste.",
> 	"LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START": "Fügt das Element an der angegebenen Position in der Liste ein.  #1 ist die erste Element.",
> 	"LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END": "Fügt das Element an der angegebenen Position in der Liste ein.  #1 ist das letzte Element.",
> ```

second "der" -> "die"

---

*[msg/json/de.json, line 312 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQfT7VmJSucPCn3uYo:-KKQfT7W-4uZvfo6gaCF:-223022523) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L312)):*
> ```JSON
> 	"LISTS_SORT_TYPE_NUMERIC": "numerisch",
> 	"LISTS_SORT_TYPE_TEXT": "alphabetisch",
> 	"LISTS_SORT_TYPE_IGNORECASE": "alphabetisch, Schreibung ignorieren",
> ```

"Schreibung" -> "Großschreibung"

---

*[msg/json/de.json, line 350 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQfc0OU7arzQ1pOgml:-KKQfc0OU7arzQ1pOgmm:319954244) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L350)):*
> ```JSON
> 	"PROCEDURES_HIGHLIGHT_DEF": "Markiere Funktionsblock",
> 	"PROCEDURES_CREATE_DO": "Erzeuge \"Aufruf %1\"",
> 	"PROCEDURES_IFRETURN_TOOLTIP": "Gibt den zweiten Wert zurück und verlässt die Funktion, wenn der erste Wert wahr ist.",
> ```

"wenn"->"falls"

---

*[msg/json/de.json, line 352 \[r1\]](https://reviewable.io:443/reviews/google/blockly/421#-KKQfg1oOnEXQPOLn7Ec:-KKQfg1oOnEXQPOLn7Ed:1342570832) ([raw file](https://github.com/google/blockly/blob/4057ddda2544c5b0e1f8c0022d451e75114964b5/msg/json/de.json#L352)):*
> ```JSON
> 	"PROCEDURES_IFRETURN_TOOLTIP": "Gibt den zweiten Wert zurück und verlässt die Funktion, wenn der erste Wert wahr ist.",
> 	"PROCEDURES_IFRETURN_HELPURL": "http://c2.com/cgi/wiki?GuardClause",
> 	"PROCEDURES_IFRETURN_WARNING": "Warnung: Dieser Block darf nur innerhalb eines Funktionsblock genutzt werden."
> ```

"Funktionsblocks" (append "s")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/421#-:-KKQgPZkHnNGMHgFzPq6:114746692)*

**Comment by zgtm** [comment]
> We pull all of our translations through translate wiki and we don't have a good way to maintain changes directly.

You've got to be joking …


Thanks for the rest of the comments, though! They seem to be all correct.

It would probably would be more according to the style guides to translate all blocks as "Baustein", however.

As for the colour picker: I've understood that the blocks description describe what the block does, not what the programmer nor the "program user" does. So in my opinion it would be the programmer, who "picks" a colour and the block would then "create" the picked colour. But that's probably up to interpretation.

**Comment by zgtm** [comment]
Ok, I've added most of the changes you mentioned to the pull request now, to have everything in one place.


> Only capitalized at sentence beginning. True for this item?
> Only capitalized when first word in sentence. True here?

Yes, these are capitalised in the original strings as well.


> Why does JOIN include "entfernen" (remove) and "sortieren" (sort)?
> Text says, "add, remove, sort elements", which seems rather different from "CREATE"
> Text says, "add to list", not "CREATE"

Here, the variable name seems to give a bad description of the string. The strings are translations matching the original strings.

**Comment by zgtm** [comment]
> We pull all of our translations through translate wiki and we don't have a good way to maintain changes directly.
Would it be possible for me to write an convert/import script of some sort, to reintegrate these changes to translate wiki directly?

**Comment by RoboErikG** [comment]
Sorry for the slow update. I checked with @NeilFraser and he says he can merge this change and then push the translations back to translate wiki. I'm not sure when he'll have time to do it, though.

**Comment by NeilFraser** [comment]
Let's start an attempt at doing an upstream import to Translatewiki.  I'll take this opportunity to modify the 0/1-based indexing tooltips at the same time since they also need to be pushed.  Then we can merge with master, send a warning email to Translatewiki detailing all the records they need to accept.  Finally, we need to be on the lookout for a sync from Translatewiki in the near future that undoes all these changes, since they are used to being the origin.

Let's see what happens...

**Pull request merged**
