### PR TITLE
Add a singleton id generator util

### PR DESCRIPTION
**Pull request by samelhusseini**
This is very similar to closure's id generator. 

It's a great way to get a unique id for any components, just call
``Blockly.utils.IdGenerator.getInstance().getNextUniqueId()``

Similar to closure's https://github.com/google/closure-library/blob/master/closure/goog/ui/idgenerator.js
(We just use the single prefix for blockly)

### CODE REVIEW

**Comment by RoboErikG** [comment]
For clarification, is this for naming dom elements uniquely? For UUIds in general there's already Blockly.utils.genUid.

**Comment by samelhusseini** [comment]
This is for generating unique DOM ids. Although, I can't think of a reason we couldn't use UUIDs instead (except that they're long).

**Comment by RoboErikG** [comment]
I guess I was asking is there a reason to have the blockly prefix or can we just reuse the existing UID generator? Is this being used to make ids that would appear alongside other named dom elements when inspecting a page or is this only used in code?

If it's generally useful, lgtm. If it's just what Closure was using I'd prefer we switch to the existing genUid method.

**Comment by samelhusseini** [comment]
Yep, I get the concern. I hadn't seen that method, and this is me just doing what closure does, but looking at this more, here are my thoughts: 

These ids that the id generator generates end up in the dom and are referred to by aria attributes.
HTML4 limitation here restricts ids to the following set:  ASCII letters, digits, '_', '-' and '.'
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

Blockly.utils.genUid.soup_ has a much wider set than that, so we'd have to adapt that to make this work. 

In addition, since this ends up in the dom. It will make debugging easier if we the id is legible, and not some UUID. 

My thoughts are we need this, but I think we can move the Blockly.utils.genUid into this idGenerator file and add comments to indicate the difference between
``genUid`` and ``getNextUniqueId``.

**Comment by RoboErikG** [comment]
genUid is a public API, so I think we'll need to leave it where it is. As a followup I'd move this next to genUid, but this PR is fine for now so we can get the toolbox in.

**Comment by RoboErikG** [comment]
Err, typed too fast, this file is already in utils, so just explaining the difference is good.

**Pull request merged**
