### PR TITLE
feat: add added the ability to customize the color of  for each blocks

### PR DESCRIPTION
**Pull request by Grougalorasalar**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Added the ability to customize the color of field_labels for each block. 
### Proposed Changes

Override applyColour for field_label and add colourFieldLabel in BlockStyle interface.

### Reason for Changes

This provides a wider range of customization options, using colors such as white or yellow with `field_labels` written in black, for example. If the block is disabled, the text color is white.

### Test Coverage

Change tests in theme_test.js file for include colourFieldLabel in expectedOutput. 

### Documentation

Update BlockStyle (add explanation of colourFieldLabel)  and FieldLabe (add explanation of applyColour ) .

### CODE REVIEW

**Comment by BeksOmega** [comment]
Hello! I think you can do this with our current css selectors:

```css
/* replace geras-renderer.classic-theme with your theme and renderer */
.geras-renderer.classic-theme .blocklyDisabled .blocklyText {
  fill: #000;
}
```

Does that solve your use-case?

**Comment by Grougalorasalar** [comment]
Yes, but if I would a black block and white block I need white text for the first block and black text for the second block. The goal of the PR is to have a large color palette for blocks, making them more legible by changing the text color. However, we could used this : https://www.w3.org/WAI/WCAG21/Techniques/general/G18 for automatic adaption text color but we have less possibilities color for the texts blocks.

**Comment by BeksOmega** [comment]
> Yes, but if I would a black block and white block I need white text for the first block and black text for the second block. The goal of the PR is to have a large color palette for blocks, making them more legible by changing the text color. However, we could used this : https://www.w3.org/WAI/WCAG21/Techniques/general/G18 for automatic adaption text color but we have less possibilities color for the texts blocks.

That makes sense! But I think in general as a library we want to move away from doing styling changes in JavaScript and instead have people use CSS. This allows the browser to better optimize repaints, and makes our API more maintainable.

If we applied a css class to the block that was the block's [block-style](https://developers.google.com/blockly/guides/configure/web/appearance/themes#block_style) name, do you think you could achieve what you want with CSS?

**Comment by BeksOmega** [comment]
> > Yes, but if I would a black block and white block I need white text for the first block and black text for the second block. The goal of the PR is to have a large color palette for blocks, making them more legible by changing the text color. However, we could used this : https://www.w3.org/WAI/WCAG21/Techniques/general/G18 for automatic adaption text color but we have less possibilities color for the texts blocks.
> 
> That makes sense! But I think in general as a library we want to move away from doing styling changes in JavaScript and instead have people use CSS. This allows the browser to better optimize repaints, and makes our API more maintainable.
> 
> If we applied a css class to the block that was the block's [block-style](https://developers.google.com/blockly/guides/configure/web/appearance/themes#block_style) name, do you think you could achieve what you want with CSS?

Heya @Grougalorasalar Still definitely interested in your thoughts on this!

**Pull request closed without merging**
