### PR TITLE
Move ordinal in block 'text_getSubstring'

### PR DESCRIPTION
**Pull request by zgtm**
On updating the block 'text_getSubstring', the ordinal string 'ORDINAL1' is moved when the corresponding corresponding input field is moved so that the ordinal string does not end up at the end of the block.

## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

None

### Proposed Changes

Reordering the ordinal sign in the block to the right place, even after selecting different entries in the block input fields. Here in German:

image

### Reason for Changes

In languages with ordinal sign, the ordinal sign ends up on the wrong place in this block, if you first select "get substring from first letter" and then select "get substring from letter #". Here in German:

image

### Test Coverage

Tested on:
Desktop Chrome
Desktop Firefox

### CODE REVIEW

**Comment by zgtm** [comment]
Is it necessary or helpful for me to create an issue for this as well?

**Comment by AnmAtAnm** [comment]
Can you also look at the `text_charat` block?

**Comment by AnmAtAnm** [comment]
For context for English speakers, if we set `Blockly.Msg.ORDINAL_NUMBER_SUFFIX = 'th'`:

screen shot 2018-02-23 at 10 03 34 am

**Comment by zgtm** [comment]
> Can you also look at the text_charat block? I ask because of known ordinal problems (#1411) in translation. We don't use the English ordinals, which means we don't test these features very often.

The `text_charat` block works fine for me, I think #1411 is a translation issue.

> I verified it works okay with the equivalent list_sublist block (I think that is its name).

Yes, that's where I took the patch from.

Actually, one could also think of replacing https://github.com/google/blockly/blob/develop/blocks/text.js#L290-L295
with 
https://github.com/google/blockly/blob/develop/blocks/lists.js#L748-L750
which I think is a bit more comprehensive.

**Pull request merged**
