### PR TITLE
Fix code generation for procedures (PHP, Python).

### LINKED ISSUE #1219: Blockly->Demos->Code error generating Python/PHP code for functions
To recreate:
- visit demos/code/index.html, and then put a function in the workspace.
- check the generated code for Python and PHP. It's empty.

The error is: 
`ReferenceError: workspace is not defined`

 and it happens in these lines: https://github.com/google/blockly/blob/master/generators/python/procedures.js#L38 and https://github.com/google/blockly/blob/master/generators/php/procedures.js#L37

block.workspace instead of workspace seems to fix the issue on both generators.

### PR DESCRIPTION
**Pull request by marisaleung**
Fixes #1219

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Some thoughts
1) does this mean I need to rebuild and push new compressed + uncompressed generator files to master?
2) why did the generator tests pass?

**Comment by marisaleung** [comment]
1. Yes I believe we do need to push new compressed + uncompressed generator files to master, so that they use the workspace from the block and not a global one if a global one even exists.
2. The generator tests passed because a global workspace existed and it was using that.

**Comment by rachel-fenichel** [comment]
One last question: do the other generators have the same problem?

**Comment by marisaleung** [comment]
Just checked all generator files and no others have this problem with workspace.

**Comment by Tech-engine** [comment]
changing 
variables = workspace.getAllVariables(); 
to
variables = block.workspace.getAllVariables();   alone   in procedure.js
doesn't  worked for me

a quick fix would be to do above + replacing

d=a.workspace.getAllVariables()      with     d=workspace.getAllVariables()
on line 50 ( php_compressed.js)
Worked for me

**Comment by marisaleung** [comment]
@Tech-engine does it still not work when you rebuild the compressed generator files? That is something we haven't updated yet.

**Comment by Tech-engine** [comment]
Yes , just change
variables = workspace.getAllVariables();
to
variables = block.workspace.getAllVariables();  in procedure.js (both for python and php)

and run build.py
I have test and it works.Thank you

**Pull request merged**
