### PR TITLE
Add Workspace Factory to Blockly Factory Tab

### PR DESCRIPTION
**Pull request by evd2014**
Add Workspace Factory to tab in Blockly Factor. Main changes in index.html, factory.css, AppController.js. Mostly moving code from workspacefactory.html and style.css for workspace factory.

blocklyfactory with workspacefactory

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/538)

### CODE REVIEW

**Comment by evd2014** [comment]
@picklesrus @vicng @rachel-fenichel @quachtina96

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/538#-:-KOvK5p2yN41dw0q2nNS:b82qq12)*

**Comment by vicng** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/app_controller.js, line 530 \[r1\]](https://reviewable.io:443/reviews/google/blockly/538#-KOvy-Gn5ouH6tyXNJFU:-KOvy-Gn5ouH6tyXNJFV:b1vqic6) ([raw file](https://github.com/google/blockly/blob/04370d85bdfa3a233a989bb1c70d80236120a63b/demos/blocklyfactory/app_controller.js#L530)):*
> ```JavaScript
>  * @private
>  */
> AppController.prototype.initWorkspaceFactory_ = function() {
> ```

Can all these new methods be defined in WorkspaceFactoryController? It's adding a lot of logic to AppController, that I don't think it needs to know about.

---

*[demos/blocklyfactory/app_controller.js, line 541 \[r1\]](https://reviewable.io:443/reviews/google/blockly/538#-KOvx_YoRV9uz6OJw0sV:-KOvx_YoRV9uz6OJw0sW:baljsx5) ([raw file](https://github.com/google/blockly/blob/04370d85bdfa3a233a989bb1c70d80236120a63b/demos/blocklyfactory/app_controller.js#L541)):*
> ```JavaScript
>   this.addWorkspaceFactoryEventListeners_();
>   this.assignWorkspaceFactoryClickHandlers_();
> ```

Nit: Remove empty line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/538)*

**Comment by picklesrus** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/app_controller.js, line 49 \[r1\]](https://reviewable.io:443/reviews/google/blockly/538#-KOw56tePl-k9YLnF5fP:-KOw56tfeLo4Wab75Q_l:b-ebq6bv) ([raw file](https://github.com/google/blockly/blob/04370d85bdfa3a233a989bb1c70d80236120a63b/demos/blocklyfactory/app_controller.js#L49)):*
> ```JavaScript
>   this.blockLibraryController.populateBlockLibrary();
> 
>   // Create empty workspace for configuring workspace.
> ```

I was expecting this to be in workspace factory specific code too since it is specific to the workspace factory tab (I think it is at least)

---

*[demos/blocklyfactory/app_controller.js, line 530 \[r1\]](https://reviewable.io:443/reviews/google/blockly/538#-KOvy-Gn5ouH6tyXNJFU:-KOw3u8jqo7v_v2gIZ8R:b-8t8b48) ([raw file](https://github.com/google/blockly/blob/04370d85bdfa3a233a989bb1c70d80236120a63b/demos/blocklyfactory/app_controller.js#L530)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Can all these new methods be defined in WorkspaceFactoryController? It's adding a lot of logic to AppController, that I don't think it needs to know about.
</details>
+1 I was expecting this kind of stuff to be in the WorkspaceFactoryController and just  called from here. 

---

*[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 328 \[r1\]](https://reviewable.io:443/reviews/google/blockly/538#-KOw3_Ie-Gy6o3UgHUYU:-KOw3_Ie-Gy6o3UgHUYV:b13nsqn) ([raw file](https://github.com/google/blockly/blob/04370d85bdfa3a233a989bb1c70d80236120a63b/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L328)):*
> ```JavaScript
>   this.previewWorkspace.dispose();
>   // TODO(evd2014): Remove call to remove child after CL to fix dispose
>   // is submitted to develop.
> ```

This is now merged so you should be able to sync and remove this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/538)*

**Comment by quachtina96** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/index.html, line 180 \[r1\]](https://reviewable.io:443/reviews/google/blockly/538#-KOwqAh31j-knPNUI9oX:-KOwqAh4jAeMq9_Zu4yg:bgv5rdr) ([raw file](https://github.com/google/blockly/blob/04370d85bdfa3a233a989bb1c70d80236120a63b/demos/blocklyfactory/index.html#L180)):*
> ```HTML
>     <tr>
>       <td width="50%" height="5%">
>         <table width=100% height=100%>
> ```

does this need the width and height to be set to 100% here even though its already specified in the css? 

---

*[demos/blocklyfactory/index.html, line 204 \[r1\]](https://reviewable.io:443/reviews/google/blockly/538#-KOwqKhVu7YatgC9ygNi:-KOwqKhVu7YatgC9ygNj:b-2guby3) ([raw file](https://github.com/google/blockly/blob/04370d85bdfa3a233a989bb1c70d80236120a63b/demos/blocklyfactory/index.html#L204)):*
> ```HTML
>       </td>
>       <td>
>         <table id="blockFactoryPreview" width=100% height=100%>
> ```

same here

---

*[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 250 \[r1\]](https://reviewable.io:443/reviews/google/blockly/538#-KOwqTTOqAL50OoQuMFG:-KOwqTTOqAL50OoQuMFH:boe7r34) ([raw file](https://github.com/google/blockly/blob/04370d85bdfa3a233a989bb1c70d80236120a63b/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L250)):*
> ```JavaScript
>   this.view.markShadowBlocks(this.model.getShadowBlocksInWorkspace
>         (this.toolboxWorkspace.getAllBlocks()));
>   this.toolboxWorkspace.cleanUp_();
> ```

should this be calling the public workspace.cleanUp method?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/538)*

**Comment by evd2014** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/app_controller.js, line 49 \[r1\]](https://reviewable.io:443/reviews/google/blockly/538#-KOw56tePl-k9YLnF5fP:-KOzou8lvGMVkDOdWCUr:bnz7fmk) ([raw file](https://github.com/google/blockly/blob/04370d85bdfa3a233a989bb1c70d80236120a63b/demos/blocklyfactory/app_controller.js#L49)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> I was expecting this to be in workspace factory specific code too since it is specific to the workspace factory tab (I think it is at least)
</details>
Moved most of this into the controller constructor so that the constructor takes the name of the DOM elements (so that it doesn't know how the page is set up) and injects the workspaces. This will also change once the CL for the options object is incorporated. 

---

*[demos/blocklyfactory/app_controller.js, line 530 \[r1\]](https://reviewable.io:443/reviews/google/blockly/538#-KOvy-Gn5ouH6tyXNJFU:-KOzkU3kmLQ7i3X6ZAwu:b-f3e1bd) ([raw file](https://github.com/google/blockly/blob/04370d85bdfa3a233a989bb1c70d80236120a63b/demos/blocklyfactory/app_controller.js#L530)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> +1 I was expecting this kind of stuff to be in the WorkspaceFactoryController and just  called from here. 
</details>
Moved all of initWorkspaceFactory into a namespace FactoryInit in the workspacefactory folder that takes a reference to a controller and does all of the initialization. Katelyn and I talked about it and while it doesn't make sense to have all of this code living in AppController, it also shouldn't really live in FactoryController since it's specific to initialization. 

---

*[demos/blocklyfactory/app_controller.js, line 541 \[r1\]](https://reviewable.io:443/reviews/google/blockly/538#-KOvx_YoRV9uz6OJw0sV:-KOzgtoZApunhmvp3Xx-:b-896fix) ([raw file](https://github.com/google/blockly/blob/04370d85bdfa3a233a989bb1c70d80236120a63b/demos/blocklyfactory/app_controller.js#L541)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Nit: Remove empty line
</details>
Done.

---

*[demos/blocklyfactory/index.html, line 180 \[r1\]](https://reviewable.io:443/reviews/google/blockly/538#-KOwqAh31j-knPNUI9oX:-KOzeqgeiUYSQp7R6WHA:b-3uapjh) ([raw file](https://github.com/google/blockly/blob/04370d85bdfa3a233a989bb1c70d80236120a63b/demos/blocklyfactory/index.html#L180)):*
<details><summary><i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>
> does this need the width and height to be set to 100% here even though its already specified in the css? 
</details>
Removed (don't recall changing those??)

---

*[demos/blocklyfactory/index.html, line 204 \[r1\]](https://reviewable.io:443/reviews/google/blockly/538#-KOwqKhVu7YatgC9ygNi:-KOzetHHUdT9Xhq_Csnd:bv8f9nw) ([raw file](https://github.com/google/blockly/blob/04370d85bdfa3a233a989bb1c70d80236120a63b/demos/blocklyfactory/index.html#L204)):*
<details><summary><i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>
> same here
</details>
Also removed

---

*[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 250 \[r1\]](https://reviewable.io:443/reviews/google/blockly/538#-KOwqTTOqAL50OoQuMFG:-KOzhF98jHALtSOwzY4k:b-a2ujfl) ([raw file](https://github.com/google/blockly/blob/04370d85bdfa3a233a989bb1c70d80236120a63b/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L250)):*
<details><summary><i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>
> should this be calling the public workspace.cleanUp method?
</details>
Changed.

---

*[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 328 \[r1\]](https://reviewable.io:443/reviews/google/blockly/538#-KOw3_Ie-Gy6o3UgHUYU:-KOzkHyzEMfllflES89o:bss4a2b) ([raw file](https://github.com/google/blockly/blob/04370d85bdfa3a233a989bb1c70d80236120a63b/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L328)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> This is now merged so you should be able to sync and remove this.
</details>
Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/538)*

**Comment by quachtina96** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/workspacefactory/wfactory_init.js, line 287 \[r2\]](https://reviewable.io:443/reviews/google/blockly/538#-KPEJf5JMDN8c9GVcISs:-KPEJf5JMDN8c9GVcISt:b-qrf9xs) ([raw file](https://github.com/google/blockly/blob/c9cc5e9c5074bcc80ac0b1e66f1d289909e4abc1/demos/blocklyfactory/workspacefactory/wfactory_init.js#L287)):*
> ```JavaScript
> 
> /**
>  * Add event listeners for worokspace factory.
> ```

nit typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/538)*

**Comment by evd2014** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/workspacefactory/wfactory_init.js, line 287 \[r2\]](https://reviewable.io:443/reviews/google/blockly/538#-KPEJf5JMDN8c9GVcISs:-KPEMKMFlbqgHAV0RhxQ:bt2vr1b) ([raw file](https://github.com/google/blockly/blob/c9cc5e9c5074bcc80ac0b1e66f1d289909e4abc1/demos/blocklyfactory/workspacefactory/wfactory_init.js#L287)):*
<details><summary><i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>
> nit typo
</details>
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/538)*

**Comment by quachtina96** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 4 of 4 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/538#-:-KPEMmRdrLXnx1wt1zEm:bnfp4nl)*

**Comment by vicng** [comment]
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/factory.css, line 385 \[r3\]](https://reviewable.io:443/reviews/google/blockly/538#-KPFrGi72IvsfBR3VgbF:-KPFrGi8pcgYefI3NpcU:b-vtpnd0) ([raw file](https://github.com/google/blockly/blob/690e0af5237abf6ff37f5b51e64cbf0bd2d02647/demos/blocklyfactory/factory.css#L385)):*
> ```CSS
> /* Change color of dropdown links on hover */
> .dropdown-content a:hover {
>   background-color: #f1f1f1
> ```

Missing ;

---

*[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 45 \[r3\]](https://reviewable.io:443/reviews/google/blockly/538#-KPFs1ZLlMLcU-iX00JP:-KPFs1ZLlMLcU-iX00JQ:b34e594) ([raw file](https://github.com/google/blockly/blob/690e0af5237abf6ff37f5b51e64cbf0bd2d02647/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L45)):*
> ```JavaScript
>  * @param {!string} previewDiv Name of div to inject preview workspace in.
>  */
> FactoryController = function(toolboxName, toolboxDiv, previewDiv) {
> ```

FactoryController isn't a good name since there are two factories now. Would it be a lot of work to rename to WorkspaceFactoryController in this CL?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/538)*

**Comment by evd2014** [comment]
Just rebased off of develop to get rid of merge conflicts with develop. 

---

Review status: 1 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/factory.css, line 385 \[r3\]](https://reviewable.io:443/reviews/google/blockly/538#-KPFrGi72IvsfBR3VgbF:-KPFssQ3WVsl-FhnFjLj:b-896fix) ([raw file](https://github.com/google/blockly/blob/690e0af5237abf6ff37f5b51e64cbf0bd2d02647/demos/blocklyfactory/factory.css#L385)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Missing ;
</details>
Done.

---

*[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 45 \[r3\]](https://reviewable.io:443/reviews/google/blockly/538#-KPFs1ZLlMLcU-iX00JP:-KPFstDqRxR-qEqKvdyD:b186uik) ([raw file](https://github.com/google/blockly/blob/690e0af5237abf6ff37f5b51e64cbf0bd2d02647/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L45)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> FactoryController isn't a good name since there are two factories now. Would it be a lot of work to rename to WorkspaceFactoryController in this CL?
</details>
This CL actually has an outdated version of FactoryController, so I agree that it makes sense to rename FactoryController (and probably the model, view, and generator), but it would probably make sense to do so in a later CL once I can do include the new changes. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/538#-:-KPFscNHqT3K1aAkN4g-:bqwnkof)*

**Comment by carlosperate** [comment]
This looks quite interesting, any short description to better describe what it does?

**Comment by evd2014** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 45 \[r3\]](https://reviewable.io:443/reviews/google/blockly/538#-KPFs1ZLlMLcU-iX00JP:-KPJV6W6USrsqpINc9VI:b-6rpksx) ([raw file](https://github.com/google/blockly/blob/690e0af5237abf6ff37f5b51e64cbf0bd2d02647/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L45)):*
<details><summary><i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>
> This CL actually has an outdated version of FactoryController, so I agree that it makes sense to rename FactoryController (and probably the model, view, and generator), but it would probably make sense to do so in a later CL once I can do include the new changes. 
</details>
Made a new CL for this: https://reviewable.io/reviews/google/blockly/553#-

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/538)*

**Comment by evd2014** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 45 \[r3\]](https://reviewable.io:443/reviews/google/blockly/538#-KPFs1ZLlMLcU-iX00JP:-KPJVDYsfS-n8MSRp23n:bwc8u4l) ([raw file](https://github.com/google/blockly/blob/690e0af5237abf6ff37f5b51e64cbf0bd2d02647/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L45)):*
<details><summary><i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>
> Made a new CL for this: https://reviewable.io/reviews/google/blockly/553#-
</details>
And after this CL, I'll submit another CL updating app_controller.js and wfactory_init.js to reflect changes made to workspace factory (including the two tabs for editing, the options object, and changing the names of the workspace factory classes) since there will be so many changes that I think it would make sense to have them in a separate CL at this point. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/538)*

**Comment by evd2014** [comment]
Blockly Factory is a developer tool (currently in progress) allowing developers to edit their blocks (like in Block Factory), but also to save and retrieve their blocks from local storage and export them to files. Blockly Factory will also provide a UI allowing developers to set up their workspace (Workspace Factory), including configuring their toolbox, setting any blocks to be automatically loaded to the workspace, and configuring the options object for the Blockly inject call. This CL is incorporating Workspace Factory into Blockly Factory. 

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/538#-:-KPJYHdXaDx5_KzDAFrq:b-92ihzo)*

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/538#-:-KPKO0npunxOWPqP9ek3:bnfp4nl)*

**Pull request merged**
