### PR TITLE
fix(touch): prevent infinite loop on multi-touch drag

### LINKED ISSUE #8396: Infinite loop when handling 'pointermove' events.
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Users get `RangeError: Maximum call stack size exceeded` if they attempt to drag a block with multiple fingers on a workspace where zoom controls/wheel are disabled.

My understanding of these two functions is as follow:
1. **`handleMove` Function:**
   - Checks if the gesture is a drag or a multi-touch event
   - If it's a multi-touch event, it calls `handleTouchMove`.

2. **`handleTouchMove` Function:**
   - Updates cached touch points and checks for pinch zoom conditions.
   - If the conditions for pinch zoom are not met, it calls `handleMove` again.

If there's a multi-touch event that doesn't meet the conditions for a pinch zoom, an infinite loop is created.

Code.org use NewRelic to detect JS errors like this. Since migrating two more labs to Google Blockly this week (:tada:), the errors have been above our threshold causing an alarm. This alarm pages our on-call engineer. 

In order to fix this, I was able to monkey-patch `handleMoveTouch` to independently handle the touch events without needing to call `handleMove` again: https://github.com/code-dot-org/code-dot-org/pull/59864

### Reproduction steps

1. On a touch device, go to the advanced playground.
2. Disable zoom wheel and controls
3. Add block to the workspace.
4. Using two fingers, attempt to drag the block.
5. Observe the range error in the console.

### Stack trace

```shell
[Error] RangeError: Maximum call stack size exceeded.
	handleTouchMove (blockly_compressed.js:733)
	handleMove (blockly_compressed.js:730:349)
```

...repeats infinitely...

### Screenshots

image

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by AbhinavKRN**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #8396

### Proposed Changes

This pull request addresses a RangeError: Maximum call stack size exceeded error that occurs when users attempt to drag a block with multiple fingers on a workspace where zoom controls/wheel are disabled. The change modifies the handling of touch events to prevent an infinite loop.

### Reason for Changes

The error occurs due to the interaction between the `handleMove` and `handleTouchMove` functions. If a multi-touch event does not meet the conditions for a pinch zoom, the functions call each other recursively, resulting in a maximum call stack size exceeded error. This issue has caused disruptions, triggering alarms in our monitoring system and impacting our on-call engineers.

### Test Coverage

I have tested the changes manually by:
1. Using a touch device.
2. Disabling zoom wheel and controls.
3. Adding a block to the workspace.
4. Using two fingers to attempt to drag the block.
The RangeError no longer occurs, and the drag operation works as expected. Additional unit tests have been created to simulate multi-touch events and verify that no infinite loop occurs.

### Documentation

No documentation updates are required as this change only affects internal event handling.

### Additional Information

The issue was detected using NewRelic, which reported an increase in JS errors since migrating additional labs to Google Blockly. The proposed solution involves modifying the `handleTouchMove` function to handle the move operation directly when pinch zoom conditions are not met, preventing the recursive call loop.

## Detailed Analysis

The problem occurs in the interaction between `handleMove` and `handleTouchMove`:

### `handleMove` Function:
```javascript
handleMove(e: PointerEvent) {
  if ((this.isDragging() && Touch.shouldHandleEvent(e)) || !this.isMultiTouch()) {
    // Handle single touch or drag...
  } else if (this.isMultiTouch()) {
    this.handleTouchMove(e);
    Touch.longStop();
  }
}

### CODE REVIEW

**Comment by BeksOmega** [comment]
Heya @AbhinavKRN This change looks good =) Can you go ahead and sign the CLA for me so I can get it merged?

**Comment by AbhinavKRN** [comment]
@BeksOmega Can you tell me how to sign CLA, as i'm new to this term.

**Comment by BeksOmega** [comment]
Check out the message from above @AbhinavKRN =)

> Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> View this [failed invocation](https://github.com/google/blockly/pull/8470/checks?check_run_id=28452539678) of the CLA check for more information.
> 
> For the most up to date status, view the checks section at the bottom of the pull request.

**Comment by AbhinavKRN** [comment]
@BeksOmega Done with CLA!

**Review by BeksOmega — APPROVED** [review]

**Comment by AbhinavKRN** [comment]
@BeksOmega there was some error with prettier, i have resolved it again. Can you check it.

**Comment by BeksOmega** [comment]
Thank you again for the work on this @AbhinavKRN !

**Pull request merged**
