### PR TITLE
Explicit list of variables

### PR DESCRIPTION
**Pull request by rachel-fenichel**

### CODE REVIEW

**Comment by carlosperate** [comment]
Just general though, since this feature will break all custom generators (even if it requires very small changes), how is it going to be documented on merge to master?

**Comment by rachel-fenichel** [comment]
Can you give an example of how this will break custom generators?  I think the API for accessing variables is exactly the same.

**Comment by carlosperate** [comment]
I'm on holiday, so cannot really check properly, and I could have been
wrong, but if I remember correctly there is a small change in this PR that
affects every single generator. So even if it's a small thing like a
function call, unless the old interface is kept "deprecated", then custom
generators will break on upstream merge.
On 6 Jul 2016 19:59, "rachel-fenichel" <notifications@github.com> wrote:

Can you give an example of how this will break custom generators? I think
the API for accessing variables is exactly the same.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/google/blockly/pull/467#issuecomment-230854095>, or mute
the thread
<https://github.com/notifications/unsubscribe/AD_sTqwruOVf4S3ATq2vWP0T9Kf-QSMQks5qS-0OgaJpZM4JDeXl>
.

**Comment by NeilFraser** [comment]
I think Carlos may be referring to this change:
-  var variables = Blockly.Variables.allVariables(workspace);
+  var variables = workspace.variableList;
A change to each language generator (not a change to each block generator).  So if someone has written a Cobol generator there may be an issue.

What happens if the above change is not made in a generator?  Will it still function?  I don't see Blockly.Variables.allVariables being deleted, so I'm unsure what would happen.

**Comment by rachel-fenichel** [comment]
Got it.

If you didn't make that change in a generator, you would end up with the full list of variables that are in use on the workspace (since Blockly.Variables.allVariables is unchanged aside from a null check).  I think this is non-breaking, and also means that the generated code would not include a bunch of (possibly unused) variables.

**Comment by rachel-fenichel** [comment]
Could do that.  We still need a function that does precisely what allVariables does, even if it has a different name, to pick up new variables when creating blocks from XML.

But do we want to pollute the generated code with unused variable declarations?

**Comment by rachel-fenichel** [comment]
@carlosperate #472 has our resolution for this, if you're interested.  allVariables now returns workspace.variableList, and allUsedVariables does what allVariables used to do.  Calling the new allVariables with a block instead of a workspace will get you a nice message telling you what to fix.

**Comment by NeilFraser** [comment]
Thanks for clarifying the behaviour of an unmodified generator under the new system.  This (very slightly suboptimal) behaviour seems totally fine to me.  I'd tend to weigh code complexity and maintainability as more important than a few transient unused generated variables in rare cases.    But entirely up to you which way you wish to proceed.

**Pull request merged**
