### PR TITLE
feat: rename blocklyTreeLabel to blocklyToolboxCategoryLabel

### LINKED ISSUE #8350: Rename the `blocklyTreeLabel` CSS class to `blocklyToolboxCategoryLabel`
Rename any references to `blocklyTreeLabel` to `blocklyToolboxCategoryLabel`. 

This change should be made against the `rc/v12.0.0` branch. This should be marked as a breaking change.

To work on this issue, comment below asking to be assigned.

### PR DESCRIPTION
**Pull request by siddharthbaleja7**
BREAKING CHANGE: The CSS class `blocklyTreeLabel` has been renamed to `blocklyToolboxCategoryLabel`.

## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #8350

### Proposed Changes

This pull request renames the CSS class `blocklyTreeLabel` to `blocklyToolboxCategoryLabel` throughout the codebase. This change ensures consistency with the new naming convention and improves clarity in the CSS class usage.

### Reason for Changes

The class `blocklyTreeLabel` was renamed to better reflect its purpose and to align with the updated naming conventions in the codebase. This renaming is part of an effort to improve code readability and maintain consistency across the project.

### Test Coverage

Tested manually by running the existing test suite and verifying that no tests failed. The change was checked in various browsers to ensure that the CSS updates do not affect the functionality of the Blockly interface.

### Documentation

Documentation and comments referring to the old class name `blocklyTreeLabel` have been updated to reflect the new class name `blocklyToolboxCategoryLabel`.

### Additional Information

N/A

### CODE REVIEW

**Comment by siddharthbaleja7** [comment]
@BeksOmega Can you please review this PR?

**Comment by siddharthbaleja7** [comment]
@BeksOmega Can you please review this PR?

**Comment by siddharthbaleja7** [comment]
@BeksOmega Can you please review this PR?

**Comment by BeksOmega** [comment]
Heya @siddharthbaleja7 I try to review daily. Please do not ping repeatedly.

**Review by BeksOmega — CHANGES_REQUESTED** [review]
Hello, a few things before I review this in-dept!

Firstly, please remove the changes to the package-lock file.

Secondly, please rebase this to be against the `rc/v12.0.0` branch. To rebase onto the rc/v12.0.0 branch, you can follow these steps.


1. **Fetch the latest changes from `rc/v12.0.0`:**

   ```bash
   git fetch upstream rc/v12.0.0
   ```

2. **Checkout your branch:**

   ```bash
   git checkout [your-branch-name]
   ```

3. **Start an interactive rebase:**

   ```bash
   git rebase -i upstream/rc/v12.0.0
   ```

4. **In the editor that opens, identify the commits that aren't yours.** These are likely the ones at the top of the list. 

5. **Change the word `pick` to `drop` for each commit you want to remove.** 

6. **Save and close the editor.**

8. **Force push your changes to your branch:** Note that force pushing is a dangerous operation because it overwrites commit history, so if you dropped the wrong commits you could lose work.

   ```bash
   git push -f origin [your-branch-name]
   ```

Once you've done this, the PR should be on the correct branch.

Let me know if you have any questions or run into any issues!

**Pull request closed without merging**
