### PR TITLE
Master to develop 07 31 17

### PR DESCRIPTION
**Pull request by rachel-fenichel**
Merging master into develop before another release.

@marisaleung please check that I have the right variables code.
@RoboErikG please sanity check.

### CODE REVIEW

**Comment by picklesrus** [comment]
Why does this mention stuff from march?

**Comment by RoboErikG** [comment]
Shouldn't this be a pull request against develop? Also, functions are broken in this PR.

**Comment by marisaleung** [comment]
Functions are fixed in this PR:
https://github.com/google/blockly/pull/1238

**Comment by rachel-fenichel** [comment]
Changed to develop.

**Comment by rachel-fenichel** [comment]
And I cherry-picked in marisa's change.  PTAL.

**Pull request merged**
