### PR TITLE
Remove last FieldLabel call and fix adding dummy inputs to json

### LINKED ISSUE #4575: Block.interpolate_ calls the FieldLabel constructor directly instead of through the registry
**Describe the bug**

The `interpolate_` function in block.js [calls](https://github.com/google/blockly/blob/master/core/block.js#L1684) `new Blockly.FieldLabel(element)` instead of using `Blockly.FieldRegistry.fromJson.

All other fields are created through the registry.

This is only in the case where there is a bare string in the block definition, which is then interpreted as a label.

For consistency, and in case someone provides their own implementation of field label, we should use the registry.

Found by looking at missing requires.

**Expected behavior**

All fields are instantiated through the registry.

**Additional context**

Desired fix: call `fieldRegistry.fromJson`, passing in an object that has the correct information. I think it would need to have the contents of `element` as `'text'` and `'label'` as `'type'`.

### PR DESCRIPTION
**Pull request by BeksOmega**
## The basics

- [X] I branched from develop
- [X] My pull request is against develop
- [X] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Closes #4575 

### Proposed Changes

1) Changes input.insertFieldAt to use the field registry.
2) Fixes last dummy inputs only being added for fields where the key is prefixed with 'field_'

Changes are kept in separate commits to make reviewing easier =)

### Reason for Changes

1) Using the registry allows people to override the default field for strings, as referenced in #4575 
2) Not all fields are prefixed with 'field_' but we should add the last dummy input regardless.

### Test Coverage

Most of the tests were already written :D But for insertFieldAt I made a test to make sure if field_label gets overwritten in the registry, the new field gets used. And for interpolation I added a test that fields prefixed with input_ also force dummy inputs to be created.

Again, I went through and checked all of the core blocks and test blocks to make sure they get created correctly.

Tested on:
 * Desktop Chrome

### Documentation

N/A

### Additional Information

N/A

### CODE REVIEW

**Comment by BeksOmega** [comment]
Weird, it looks like the build never ran.

**Comment by maribethb** [comment]
> Weird, it looks like the build never ran.

Sorry, forgot to update you. We are having issues with Travis, but on Monday if the problems persist I will manually run the build on your PR and then merge it for you.

**Review by maribethb — APPROVED** [review]

**Comment by maribethb** [comment]
Hey @BeksOmega we have GitHub Actions set up now to replace travis. Could you either rebase or merge from develop so that it pulls in the new workflow stuff (should have a folder `.github/workflows` after the merge) so that the automated tests will run on this PR? Thanks, and sorry for the hassle! 

(I tried to rebase your pr myself but didn't want to overwrite your commits)

**Comment by BeksOmega** [comment]
Cool should be gtg now! And don't every worry about overwriting my commits hehe, just do whatever is easiest for you. If it's easiest for you to rebase, go right ahead. Or if it's easiest for me to rebase, I'm always happy to =)

**Pull request merged**
