### PR TITLE
feat: Add the block's type as a CSS class to the block's root SVG (#8268)

### PR DESCRIPTION
**Pull request by ga-fleury**
Fixes: #8268 

**feat: Add the block's type as a CSS class to the block's root SVG (#8268)**

### CODE REVIEW

**Review by BeksOmega — APPROVED** [review]
This looks great! Thank you for the fix =) I'll get this merged once CI passes.

**Comment by BeksOmega** [comment]
@ga-fleury , looks like some of the tests are failing. You can run them locally with `npm run test:mocha:interactive`. Can you take a look and try to figure out what's up?

**Review by BeksOmega — CHANGES_REQUESTED** [review]
Marking this as changes requested

**Comment by ga-fleury** [comment]
@BeksOmega Seems like the `BlockSvg` class is receiving empty `prototypeName` values somewhere, which means they wouldn't receive a CSS class. Adding a empty string check solves the issue, Should we pass a default class name when the value is empty?

**Comment by BeksOmega** [comment]
> @BeksOmega Seems like the `BlockSvg` class is receiving empty `prototypeName` values somewhere, which means they wouldn't receive a CSS class. Adding a empty string check solves the issue (see below), Should we pass a default class name when the value is empty?
> 
> ```
>     if(prototypeName) {
>       dom.addClass(this.svgGroup_, prototypeName)
>     }
> ```

Yeah that LGTM! Thanks for digging into this :D

Normally I would say we should fix the tests instead, but there are other places where we're checking `if (prototypeName)`, so better to be cautious. One you send in the fix I'll give this another look!

**Comment by ga-fleury** [comment]
@BeksOmega just pushed changes

**Review by BeksOmega — CHANGES_REQUESTED** [review]
Can you run the same formatting fixes you did on the other PRs?

**Pull request closed without merging**
