### PR TITLE
Fixing operator precedence in Lua and and adding test.

### LINKED ISSUE #3566: Lua codegen of lists_getIndex block has problems with list literals
When a _lists_getIndex_ block has a list input that is not a variable, but a literal like _lists_create_with_, the generated Lua code looks like ```{'foo', 'bar'}[1]```. That's not valid Lua according to the interpreter I'm working with and two other online interpreters I tested (repl.it and tutorialspoint). Wrapping the literal in parentheses makes the interpreters happy: ```({'foo', 'bar'})[1]```.

Maybe _lists_create_with_ should always wrap the list literal in parens or _lists_getIndex_ should have different operator precedent rules?

lua_list_example

### PR DESCRIPTION
**Pull request by moniika**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

#3566

### Proposed Changes

Fixes error in operator in 

### Reason for Changes

Incorrect precedence resulted in cases where Blockly generated code with syntax errors.

### Test Coverage

Ran generator tests.

### CODE REVIEW

**Comment by moniika** [comment]
@seldomU

**Comment by rachel-fenichel** [comment]
Travis should be running tests for this.  The generator tests are supposed to check the generated code against a golden file for the given language--and this should have required an update to the golden files as a result.

**Comment by rachel-fenichel** [comment]
Do you know why travis isn't running the tests?

**Comment by moniika** [comment]
> Do you know why travis isn't running the tests?

It appears to have been an issue with Travis/Github communication.
Likely this:
https://www.traviscistatus.com/incidents/rx6fhs3wqcln?u=49rdxf5zfpg9

Travis has run now though, so issue may be resolved.

**Comment by seldomU** [comment]
This fixes my problem.

**Pull request merged**
