### PR TITLE
feat: add `blocklyLabelField` css class to label field

### PR DESCRIPTION
**Pull request by surajguduru**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes [Issue #8315](https://github.com/google/blockly/issues/8315)

### Proposed Changes

This pull request adds a `blocklyLabelField` CSS class to label fields in the `FieldLabel` class by modifying the `initView` method to call `dom.addClass` with `this.fieldGroup_` and `blocklyLabelField`.

### Reason for Changes

This change helps in applying specific styles to label fields, allowing better customization and theming of Blockly components.

### Test Coverage

I tested these changes manually by creating and manipulating label fields in the Blockly playground. Additionally, I verified that the `blocklyLabelField` class is applied correctly in different scenarios.

### Documentation

No additional documentation is needed for this PR.

### Additional Information

No additional information.

### CODE REVIEW

**Comment by surajguduru** [comment]
Hey @BeksOmega Please review this !!

**Comment by surajguduru** [comment]
Hey @gonfunko Please review this !!

**Comment by surajguduru** [comment]
Hiya @BeksOmega  @gonfunko  I have made the required changes. Please review the changes and let me know !

**Review by BeksOmega — APPROVED** [review]
This looks great thank you for the fixes! Once CI passes I'll get this merged =)

**Pull request merged**
