### PR TITLE
Remove calls to svgResize that don't seem to do anything.

### PR DESCRIPTION
**Pull request by picklesrus**
@NeilFraser Do you know why these calls to svgResize are are here?
I can't find a time when removing them causes problems and it feels like I've tested a bunch of cases... but you often just know these things.

### CODE REVIEW

**Comment by NeilFraser** [comment]
I'm noticing some resize glitches appearing already (not including this PR).  For example:
https://blockly-demo.appspot.com/static/demos/graph/index.html
Blockly is the wrong size until the window is resized.  Another (more subtle) example is:
https://blockly-demo.appspot.com/static/demos/code/index.html
The 'Blocks' tab is out of alignment until the window is resized.

Also, this line is definitely wrong:
https://github.com/google/blockly/blob/master/core/block_svg.js#L276
That's a static method.  'this' is the window.  As chance would have it most Blockly apps (at least the demos) define a global 'workspace' property which that line coincidentally hits.  Maybe we need:
      Blockly.asyncSvgResize(Blockly.selected.workspace);

**Comment by picklesrus** [comment]
Huh, interesting. Do you know when those bugs were introduced?

I think we're suffering a bit from svgResize being a heavy hammer that gets called a lot. IIUC, it really does two big things:
A. handles resizing the workspace when the blockly div hasn't changed size (e.g. when a new block is placed and we want to grow/shrink to fit)
B. Handles resizing when the blockly div changes size (e.g. a window resize or when blockly is first loaded)

B means we need to do A also, but there are times when we do B just to get the functionality for A.  The bugs you noticed make me more suspicious that this works by mistake sometimes :) What do you think about splitting it up and making it more explicit?  i.e. only do the div resizing on resize events? Then the other part (namely what currently happens when workspace_svg calls scrollbar.resize() in its own resize method:https://github.com/google/blockly/blob/master/core/workspace_svg.js#L312) would be exposed separately and we'd only call that when blocks are placed, moved, etc.

And for full disclosure of my motivations:
Not trying to do B when we only need A is also a perf win since we wouldn't stop for a layout re-calculation when we call div.offsetHeight/Width in the middle of handling an event.

**Comment by NeilFraser** [comment]
Sounds good to me.

**Comment by picklesrus** [comment]
Note about the graph one: It explicitly sets a height in pixels rather than a % https://github.com/google/blockly/blob/master/demos/graph/index.html#L50

Then it adds its own resize handler to change the width later on resize: https://github.com/google/blockly/blob/master/demos/graph/index.html#L329

Maybe we stopped firing a resize event recently? But it seems like this is more a problem with the demo than with underlying blockly? I'd probably fix it by changing index.html to either fire its own resize event or to set width in init they way it is set in resize rather than to 400px. Thoughts?

**Comment by NeilFraser** [comment]
Sounds good to me.

**Comment by picklesrus** [comment]
Closing this in favor of  PR #386. That does a refactor of resizing and fixing both bugs you pointed out.

**Pull request closed without merging**
