### PR TITLE
Fix potential issue with naming and merged changes from techplexengineer to ensure headless works

### PR DESCRIPTION
**Pull request by Immortalin**

### CODE REVIEW

**Comment by carlosperate** [comment]
I haven't tried it yet, but I've been running Blockly with the closure library on node (not installed using npm), and I am a bit wary that this might break my current implementation. Are my worries unfounded? I probably won't be able to test it properly until the weekend, and I could report back then, but I wanted to ask here as well just in case.

**Comment by Immortalin** [comment]
@carlosperate I don't think it would affect anything. The "remove google-closure-library support" commit was because I originally added code to deal with the [closure library naming issue](https://github.com/google/closure-library/pull/604). I removed the code because it was too much of a hack and made build.py brittle. It is simply easier to fork the closure library and change the name in package.json. This is in part due to my poor coding skills. It would be great however if you can actually fix it and add support for multiple closure library names.

**Comment by NeilFraser** [comment]
For reference, I have zero Node.js expertise.  When I get a plausible-looking patch related to this I'll just check that it doesn't break the browser experience, then accept it.

**Comment by Immortalin** [comment]
I don't have any node.js experience either....

**Comment by carlosperate** [comment]
Indeed this turned out to be problematic for my specific (corner) case. I am server the closure library and blockly statically through nodejs (by using electron), so the `isNodeJS` flag is set to true, but the code executed for node fails in multiple places. I'll look into it this weekend, but any help would be welcomed.

**Comment by Immortalin** [comment]
@carlosperate I will take a look at it later

**Comment by carlosperate** [comment]
Added a very simple extension to the `isNodeJS` identification, hopefully it should not break pure nodejs implementations, but since I don't have anything with closure implemented in node (a very little experice with node in general) I am unable to test.

Can somebody using blockly and closure in node test it?

**Pull request merged**
