### PR TITLE
Blockly Factory: Alert if Unsaved Changes in Block Factory

### PR DESCRIPTION
**Pull request by quachtina96**
Alerts users when 

- they want to create a block and they've made changes to the block they are currently on.
screen shot 2016-08-24 at 4 39 30 pm

- they want to switch from the block factory tab to a different tab, but they have unsaved changes.
screen shot 2016-08-24 at 4 39 44 pm

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/594)

### CODE REVIEW

**Comment by quachtina96** [comment]
@evd2014 @picklesrus @vicng

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/594#-:-KQ1S5g2V9TksAnGvGBo:b6cau0p)*

**Comment by picklesrus** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[demos/blocklyfactory/app_controller.js, line 309 \[r1\]](https://reviewable.io:443/reviews/google/blockly/594#-KQ1uN06j2KEuaStNrgx:-KQ1uN06j2KEuaStNrgy:bjglv5l) ([raw file](https://github.com/google/blockly/blob/284df3426664a1acbc95fc2a302db93bfcd2bad0/demos/blocklyfactory/app_controller.js#L309)):*
> ```JavaScript
> 
>   // Warn user if they have unsaved changes when leaving Block Factory.
>   if (this.lastSelectedTab == AppController.BLOCK_FACTORY &&
> ```

should this happen before the keyEventsEnabled stuff above?

---

*[demos/blocklyfactory/app_controller.js, line 313 \[r1\]](https://reviewable.io:443/reviews/google/blockly/594#-KQ1uBpwZiQEoCS_KlPe:-KQ1uBpx-XQzScF6lulI:bfju24f) ([raw file](https://github.com/google/blockly/blob/284df3426664a1acbc95fc2a302db93bfcd2bad0/demos/blocklyfactory/app_controller.js#L313)):*
> ```JavaScript
>     if (!BlockFactory.isStarterBlock() && !this.savedBlockChanges()) {
>       if (!confirm('You have unsaved changes in Block Factory.')) {
>         // If the user doesn't wnat to switch tabs with unsaved changes,
> ```

typo: want

---

*[demos/blocklyfactory/factory.js, line 253 \[r1\]](https://reviewable.io:443/reviews/google/blockly/594#-KQ1unJrJu-1IgXOizzW:-KQ1unJstSK058EDqPQy:b-d9o3l3) ([raw file](https://github.com/google/blockly/blob/284df3426664a1acbc95fc2a302db93bfcd2bad0/demos/blocklyfactory/factory.js#L253)):*
> ```JavaScript
>     return false;
>   }
>   if (rootBlock.getFieldValue('NAME').trim().toLowerCase() != 'math_foo') {
> ```

is math_foo the right name here? didn't you change it above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/594)*

**Comment by quachtina96** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/app_controller.js, line 309 \[r1\]](https://reviewable.io:443/reviews/google/blockly/594#-KQ1uN06j2KEuaStNrgx:-KQ2dntVTYQ0JF-Aroot:b-m6f40s) ([raw file](https://github.com/google/blockly/blob/284df3426664a1acbc95fc2a302db93bfcd2bad0/demos/blocklyfactory/app_controller.js#L309)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> should this happen before the keyEventsEnabled stuff above?
</details>
Yes, moved!

---

*[demos/blocklyfactory/app_controller.js, line 313 \[r1\]](https://reviewable.io:443/reviews/google/blockly/594#-KQ1uBpwZiQEoCS_KlPe:-KQ2dqtrPXgSEqi06pkv:b-896fix) ([raw file](https://github.com/google/blockly/blob/284df3426664a1acbc95fc2a302db93bfcd2bad0/demos/blocklyfactory/app_controller.js#L313)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> typo: want
</details>
Done.

---

*[demos/blocklyfactory/factory.js, line 253 \[r1\]](https://reviewable.io:443/reviews/google/blockly/594#-KQ1unJrJu-1IgXOizzW:-KQ2flm1Yzs77PVmGcX-:b2xxlwx) ([raw file](https://github.com/google/blockly/blob/284df3426664a1acbc95fc2a302db93bfcd2bad0/demos/blocklyfactory/factory.js#L253)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> is math_foo the right name here? didn't you change it above?
</details>
I changed this to make the code cleaner. math_foo was the right name, but for consistency's sake i've changed it to block_type. the change to block_type is in a separate CL (the next one)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/594)*

**Comment by picklesrus** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/594#-:-KQ35nkBND3hdQZ_i_Mb:bnfp4nl)*

**Comment by quachtina96** [comment]
Ready to merge! 

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/594#-:-KQ3semDCPSQFdY39nUY:bsg4o6s)*

**Pull request merged**
