### PR TITLE
[zelos] Don't add next notch in a statement input if the connection block doesn't have a next connection

### PR DESCRIPTION
**Pull request by samelhusseini**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Fixes https://github.com/google/blockly/issues/3546

### Proposed Changes

Create a custom zelos statement input that checks if the last connected block in a statement input's stack has a next connection and if not, doesn't add a next notch.

### Reason for Changes

Zelos rendering.

### Test Coverage

Tested the break out of loop block in a repeat, if and procedure statement in the zelos renderer.

Screen Shot 2020-01-07 at 2 41 37 PM

Tested on:

### CODE REVIEW

**Comment by alschmiedt** [comment]
Found this when playing with the feature: 
Screen Shot 2020-01-08 at 7 50 41 PM
It looks like it is only the last statement input that is having the problem. I tried it in develop and it seems fine so I think it is because of this change.

**Comment by samelhusseini** [comment]
Yep, that was fixed in https://github.com/google/blockly/pull/3565. I just hadn't merged that back into this PR, but can do now.

**Comment by petervanderwalt** [comment]
> Screen Shot 2020-01-07 at 2 41 37 PM

@samelhusseini which theme is this?  Looks nice and flat compared to default theme 

image

**Comment by BeksOmega** [comment]
Hello @petervanderwalt !

This is using the [zelos renderer](https://developers.google.com/blockly/guides/configure/web/appearance/renderers#built-in) (which controls the shape of the block) with the [modern theme](https://www.npmjs.com/package/@blockly/theme-modern) (which controls the colors of the block.

In the future, please direct questions like this to the [developer forum](https://groups.google.com/g/blockly)! We try to make sure the github is just projec-tracking stuff :P Appreciate the question though!

**Comment by petervanderwalt** [comment]
Thank you, and sorry!

**Pull request merged**
