### PR TITLE
Blockly Factory: Rename WorkspaceFactory Classes

### PR DESCRIPTION
**Pull request by evd2014**
Rename FactoryController to WorkspaceFactoryController, FactoryModel to WorkspaceFactoryModel, and FactoryView to WorkspaceFactoryView to distinguish between Block Factory and Workspace Factory.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/553)

### CODE REVIEW

**Comment by evd2014** [comment]
@picklesrus @vicng @quachtina96

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/553#-:-KPJUw3uvgKW5pZcT70A:bvyui8)*

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/553#-:-KPKO6SQ3DCstvrZusK9:bnfp4nl)*

**Comment by quachtina96** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/553#-:-KPKUuUNhhjfArTytGhS:bnfp4nl)*

**Comment by picklesrus** [comment]
This LGTM, too, but needs to be synced.

**Pull request merged**
