### PR TITLE
Update to webdriverio v5; fix resulting test breakages

### LINKED ISSUE #2117: Update geckodriver to latest
We currently get a specific version rather than latest, and our version is out of date.
https://github.com/google/blockly/blob/master/tests/scripts/get_geckdriver.sh

### LINKED ISSUE #2118: Remove enforced delays from generator tests
The automated generator tests pause for a long time to let each processing step happen in the page.  I think it's only necessary for the file loads (and not for the code generation) but need to confirm that.

### LINKED ISSUE #2283: Update webdriverio to 5.4
Webdriverio released a major new version with breaking changes.  

[More info](https://webdriver.io/blog/#how-to-upgrade-to-v5).

### PR DESCRIPTION
**Pull request by rachel-fenichel**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Fixes #2283 
Fixes #2117
Fixes #2118

### Proposed Changes

- update webdriverio to v5
- switch to async/await syntax in our testing files--v5 doesn't support chaining
- update geckodriver--the older version didn't work with newer webdriverio

### Reason for Changes

Webdriverio v5 had some pretty significant changes: https://webdriver.io/blog/2018/12/19/webdriverio-v5-released.html

I want to get to v5 for two reasons: first, so that we don't get completely stale and second, because it looks like running mocha tests on travis will be easier with v5.  Now that both Abby and Beka are writing those tests regularly, I want them to run on all PRs.  This is a step in that direction.

### Test Coverage
Generator tests and jsunit tests pass.  I also checked to make sure I could make them fail.

### CODE REVIEW

**Comment by RoboErikG** [comment]
any idea why the generator tests are failing?

**Comment by rachel-fenichel** [comment]
Not sure--I kicked off a rebuild to try one more time, then will try cleaning up and rerunning npm install locally to see if I can repro.

**Comment by rachel-fenichel** [comment]
Hm this looks like a problem I've had before with firefox on travis/geckodriver not working.

**Comment by rachel-fenichel** [comment]
Looks like the fix was to explicitly say I wanted to firefox addon.  I thought I didn't need that based on the travis [docs](https://docs.travis-ci.com/user/firefox), but it's working now.

**Pull request merged**
