### PR TITLE
Changed workspace metrics depending on flyout metrics

### PR DESCRIPTION
**Pull request by evd2014**
Changed workspace metrics to depend on flyout metrics in the same way that the workspace metrics depend on the toolbox metrics. Reduces some of the special cases in placing the trashcan and zoom controls. Also a step towards solving the problem of being able to scroll blocks over a single flyout of blocks. 

scroll blocks

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/576)

### CODE REVIEW

**Comment by evd2014** [comment]
@rachel-fenichel

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/576#-:-KP_L_4ppOoVNLRHpwsk:b-iauaw3)*

**Comment by picklesrus** [comment]
:lgtm:  But @rachel-fenichel should look too since coordinates are tricky :)

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/576#-:-KPnlLTOUIuocYffYvbD:b-40u73a)*

**Comment by rachel-fenichel** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[core/blockly.js, line 450 \[r1\]](https://reviewable.io:443/reviews/google/blockly/576#-KPnqwDU4ycaqlWd_blF:-KPnqwDVvX5PHdSFsqfY:b148eg) ([raw file](https://github.com/google/blockly/blob/d94bf96604d10c945dc5310ff8304575f8c4ef44/core/blockly.js#L450)):*
> ```JavaScript
>     }
>   } else if (this.flyout_) {
>     if (this.toolboxPosition == Blockly.TOOLBOX_AT_TOP ||
> ```

Can use this.horizontalLayout instead.  (Which appears to be defined on workspace instead of workspaceSvg.  Which makes no sense.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/576)*

**Comment by evd2014** [comment]
Fixed a bug I created in flyout.js that was causing stuff to render properly but have a lot of weird console messages and deleted another unnecessary case in trashcan and zoom that were causing them to be placed incorrectly when the toolbox was at the bottom. All fixed now!

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[core/blockly.js, line 450 \[r1\]](https://reviewable.io:443/reviews/google/blockly/576#-KPnqwDU4ycaqlWd_blF:-KPoX78R6wfxJ8EUTHUC:bs7wubq) ([raw file](https://github.com/google/blockly/blob/d94bf96604d10c945dc5310ff8304575f8c4ef44/core/blockly.js#L450)):*
<details><summary><i>Previously, rachel-fenichel wrote…</i></summary>
> Can use this.horizontalLayout instead.  (Which appears to be defined on workspace instead of workspaceSvg.  Which makes no sense.)
</details>
Done! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/576#-:-KPoX8ej2DPYhHC9myRi:bxwoxkz)*

**Comment by evd2014** [comment]
Rebased off of develop to move my changes from blockly.js into workspace_svg.js

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/576#-:-KPormIbFRBQbx3bR8sD:bshd6f3)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/576#-:-KPtBEqBoa96C0c1ibP6:bnfp4nl)*

**Comment by picklesrus** [comment]
Do you mind syncing your branch and testing one last time? Coordinate changes tend to be finicky. Happy to help with the testing!  Then I'll merge.

**Comment by picklesrus** [comment]
Something changed so that this doesn't work anymore.  I've patched it to my own branch and will take it over and figure out what happened. Closing this PR.

**Pull request closed without merging**
