### PR TITLE
Adding automatically-generated variable lists to the accessible toolbox.

### PR DESCRIPTION
**Pull request by CoryDCode**
Also fixing a bug with the core-only uncompressed file not finding its own directory.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/1149)

### CODE REVIEW

**Comment by RoboErikG** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[accessible/toolbox-modal.service.js, line 77 at r1](https://reviewable.io:443/reviews/google/blockly/1149#-KldsSXyFnXJLmTBpP68:-KldsSXzQQ6Wrl9WVYKr:b-2fyh64) ([raw file](https://github.com/google/blockly/blob/9734332a17e42652a430fdde1165ab8ce0d27fed/accessible/toolbox-modal.service.js#L77)):*
> ```JavaScript
>           var tmpWorkspace = new Blockly.Workspace();
>           var custom = categoryElt.attributes.custom
>           if (custom && custom.value == Blockly.VARIABLE_CATEGORY_NAME) {
> ```

Why doesn't this use the dynamic flyouts APIs? https://developers.google.com/blockly/guides/configure/web/toolbox#dynamic_categories

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/1149)*

**Comment by CoryDCode** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[accessible/toolbox-modal.service.js, line 77 at r1](https://reviewable.io:443/reviews/google/blockly/1149#-KldsSXyFnXJLmTBpP68:-Klt6_xZeyRit1kHtL7l:b6rf4f7) ([raw file](https://github.com/google/blockly/blob/9734332a17e42652a430fdde1165ab8ce0d27fed/accessible/toolbox-modal.service.js#L77)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Why doesn't this use the dynamic flyouts APIs? https://developers.google.com/blockly/guides/configure/web/toolbox#dynamic_categories
</blockquote></details>

RegisterToolboxCategoryCallbacks is on WorkspaceSvg. Since WorkspaceSvg is not instantiated in headless Blockly, I can't properly utilize it. It probably shouldn't be there, but for now, I can't use that stuff without a refactor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/1149)*

**Comment by RoboErikG** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[accessible/toolbox-modal.service.js, line 77 at r1](https://reviewable.io:443/reviews/google/blockly/1149#-KldsSXyFnXJLmTBpP68:-Klt7eMnoJ1ufAfSkg3X:bh8jvpn) ([raw file](https://github.com/google/blockly/blob/9734332a17e42652a430fdde1165ab8ce0d27fed/accessible/toolbox-modal.service.js#L77)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

RegisterToolboxCategoryCallbacks is on WorkspaceSvg. Since WorkspaceSvg is not instantiated in headless Blockly, I can't properly utilize it. It probably shouldn't be there, but for now, I can't use that stuff without a refactor.
</blockquote></details>

Add a TODO to rewrite this once Issue #1153 is fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/1149#-:-Klt7noRBWIbjkiG0503:bnfp4nl)*

**Comment by CoryDCode** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[accessible/toolbox-modal.service.js, line 77 at r1](https://reviewable.io:443/reviews/google/blockly/1149#-KldsSXyFnXJLmTBpP68:-KltyJ4S5X0i6jRlMzf8:b-896fix) ([raw file](https://github.com/google/blockly/blob/9734332a17e42652a430fdde1165ab8ce0d27fed/accessible/toolbox-modal.service.js#L77)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Add a TODO to rewrite this once Issue #1153 is fixed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/1149)*

**Pull request merged**
