### PR TITLE
Mouse zooming

### PR DESCRIPTION
**Pull request by carloslfu**
Ability to do zooming with the mouse wheel. This is useful for large programs, i hope your suggestions.

screen1
screen2
zooming

### CODE REVIEW

**Comment by carlosperate** [comment]
I started playing with this and it seems to be working great, will definitely use a function like this

Ideally, I think that zooming with the scroll wheel should be a feature to be activated with the Blockly.inject arguments (https://developers.google.com/blockly/installation/overview), while still allowing to edit zoom options programmatically using the Blockly.zoom functions. Would you mind adding that in?

**Comment by carloslfu** [comment]
Thanks, I'll add zooming to the Blockly.inject arguments. The variables that you can change are:
 * Is zooming enabled?:
Blockly.mainWorkspace.zooming = true;

 * Current scale speed:
Blockly.mainWorkspace.scaleSpeed = 1.2;

 * Current minimum scale:
Blockly.mainWorkspace.minScale = 0.3;

 * Current maximum scale:
Blockly.mainWorkspace.maxScale = 3;

and the function Blockly.zoomReset() for reset the view.

**Comment by carloslfu** [comment]
I have added the options to Blockly.inject:
zoom: is zooming enabled?, true by default
zoomOptions:
{
     maxScale: maximum zooming,3 by defult ,
     minScale:  minimum zooming,0.3 by defult ,
     scaleSpeed: factor to zooming in or out in each mouse wheel event, 1.2 by default
}

**Comment by carlosperate** [comment]
I just wanted to point out that I find this feature quite useful, even if it is not active by default (I was planning to check the screen resolution programmatically set a zoom level and have buttons to zoom in and out, not so much the scrollwheel).
@NeilFraser would this pull request be considered for merge if the conflicts were resolved?

**Comment by brianpmarks** [comment]
Just another comment that our users would find this feature very useful over at trinket.io. We've had teachers request this so their students can better see their programs as they get more complicated. (We also would lean towards implementing buttons to zoom in and out rather than relying on the scrollwheel but both options are nice.)

**Comment by yoderjen** [comment]
I would also like to see zooming implemented.  It would be really useful for large projects.  Ideally both buttons and mousewheel could do it, but if there is only one we'd prefer mousewheel.

**Comment by victoralex** [comment]
i believe i've found an issue with this patch
untitled-1

The scroll on the bottom (horizontally to in some cases) does not take into account the objects' size, thus the user cannot scroll more.

However, when zooming out or in more, the calculation is correct. So this applies only to some zoom levels. I believe that either the scrollbars or the workspace area are wrongly calculated.

**Comment by carloslfu** [comment]
Some things has changed in the last months in Blockly and this pull is outdated. There are many things to keep in mind for this feature:

- Text input fields needs to be implemented in pure svg for a coherent zooming.
- Dropdown field should be implemented in pure svg.
- Zomming like google maps (buttons, mousewheel and touch gestures).

Now I am experimenting with a svg based text input. I will make a rebase of this pull for a simple zooming (implement buttons and mousewheel) and solve some issues.

**Comment by victoralex** [comment]
Thank you for the quick reply.

You believe the non-SVG implementations are what is leading to this situation? Do you have a quick fix to increase the working area or the scrollbars area?

**Comment by carlosperate** [comment]
Hi Carlos, 
Glad to hear you are planning to update the request, even if it does not get merged into master (we never heard from @NeilFraser) I'll be happy to test it as I'm interested to implement it in my project as well :)

**Comment by starfishmod** [comment]
I too would be interested especially as I keep having to write my own
select box using standard components as the built select box never seems to
scroll properly with really long lists.

Is anyone but me considering making a semi official fork of Blockly so we
can get some of these features in? Like what the io.js guys did with
node.js?

On 12 June 2015 at 08:52, Carlos <notifications@github.com> wrote:

> Hi Carlos,
> Glad to hear you are planning to update the request, even if it does not
> get merged into master (we never heard from @NeilFraser
> <https://github.com/NeilFraser>) I'll be happy to test it as I'm
> interested to implement it in my project as well :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/blockly/pull/44#issuecomment-111298663>.
>



-- 
Regards

Andrew

**Comment by carloslfu** [comment]
Hi victor (@victoralex).

I have committed a quick fix for this issue.

**Comment by carloslfu** [comment]
Hi @starfishmod.

That's a good idea, I'm also considering making an alternate repository. This should maintain compatibility with the official repository and could merge many experimental features.

**Comment by alloplastic** [comment]
Hi, Carlos.

I'm interested in this feature, too.  I just merged this PR with the latest Blockly code and have it mostly working... in case that saves you some time.  I'm new to Blockly, so my conflict resolution may not have been ideal.

     https://github.com/alloplastic/blockly-choreo/tree/workspace_scaling

The main problem I couldn't resolve is that blocks snap back to their start position after being dragged.

Thanks for creating this feature.  I think visual programming can be more than a learning tool, but only if it's easy to navigate the code.

Sheldon

**Comment by carloslfu** [comment]
Thanks Sheldon(@alloplastic) .

Hi all. I made a new clean and updated PR for this feature in which I added buttons, see #125.

**Comment by NeilFraser** [comment]
Closing on the basis that PR #125 supercedes this.  (Yell at me if I'm wrong.)

**Pull request closed without merging**
