### PR TITLE
Remove unnecessary restriction on variable names.

### PR DESCRIPTION
**Pull request by NeilFraser**
This restriction prevented variables from acquiring the name of an existing procedure.  However, this restriction was ineffective since there was no corresponding check on procedure names.  Moreover, there is no need for this restriction, since the generators were designed to handle name collisions.

Besides, the concept of error messages is antithetical to Blockly's goals.

### CODE REVIEW

**Comment by NeilFraser** [comment]
Question: Are there Android or iOS implications to this message removal?

**Comment by AnmAtAnm** [comment]
Not an issue on Android.

**Comment by rachel-fenichel** [comment]
The generator code already renames as needed so that there aren't conflicts.

**Comment by rachel-fenichel** [comment]
LGTM.  @vicng are there iOS implications here?

**Comment by vicng** [comment]
Nope, no implications with iOS -- this restriction was never added.

**Comment by rachel-fenichel** [comment]
LGTM, approval.

**Pull request merged**
