### PR TITLE
Parse separators in xml in always-open flyouts

### LINKED ISSUE #463: Toolbox separator between blocks
Hi, i have an issue when i want to create a separation between blocks in the toolbar, i have a simple toolbar with a separation tag that blockly ignore:

ember-blockly 2016-06-30 15-24-10

but in the documentation seems to be valid that code: https://developers.google.com/blockly/guides/configure/web/toolbox#separators

What am I doing wrong?

Thanks

### PR DESCRIPTION
**Pull request by rachel-fenichel**
Fixes #463

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/531)

### CODE REVIEW

**Comment by picklesrus** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/flyout.js, line 665 \[r1\]](https://reviewable.io:443/reviews/google/blockly/531#-KOli_aRZoxDd9yZWrZb:-KOli_aRZoxDd9yZWrZc:b-dblfpu) ([raw file](https://github.com/google/blockly/blob/3998ecec3af164bca19469680c9b748611e26377/core/flyout.js#L665)):*
> ```JavaScript
>         if (!isNaN(newGap) && lastBlock) {
>           var oldGap = parseInt(lastBlock.getAttribute('gap'));
>           var gap = isNaN(oldGap) ? newGap : oldGap + newGap;
> ```

I'm kind of confused by how this attribute works to make things smaller.  If I wanted a smaller than 24 gap, would I need to set it to a negative number (assuming that the last block had the default of 24 set)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/531)*

**Comment by rachel-fenichel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/flyout.js, line 665 \[r1\]](https://reviewable.io:443/reviews/google/blockly/531#-KOli_aRZoxDd9yZWrZb:-KOlklFny4uZjcXRIL_8:b-yvk40d) ([raw file](https://github.com/google/blockly/blob/3998ecec3af164bca19469680c9b748611e26377/core/flyout.js#L665)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> I'm kind of confused by how this attribute works to make things smaller.  If I wanted a smaller than 24 gap, would I need to set it to a negative number (assuming that the last block had the default of 24 set)?
</details>
I had assumed previously that it was just the number in the gap attribute, but looking at the parsing code in the toolbox, it appears to be implemented as an additive thing right now.  https://github.com/google/blockly/blob/master/core/toolbox.js#L344

I'm down to change it to be replacing instead of adding in both cases.  I was just aiming for consistency here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/531)*

**Comment by picklesrus** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/flyout.js, line 665 \[r1\]](https://reviewable.io:443/reviews/google/blockly/531#-KOli_aRZoxDd9yZWrZb:-KOlnVaej6KMDTh3SVDC:bol115x) ([raw file](https://github.com/google/blockly/blob/3998ecec3af164bca19469680c9b748611e26377/core/flyout.js#L665)):*
<details><summary><i>Previously, rachel-fenichel wrote…</i></summary>
> I had assumed previously that it was just the number in the gap attribute, but looking at the parsing code in the toolbox, it appears to be implemented as an additive thing right now.  https://github.com/google/blockly/blob/master/core/toolbox.js#L344
> 
> I'm down to change it to be replacing instead of adding in both cases.  I was just aiming for consistency here.
</details>
Ah, I see.  Should we consolidate that logic if consistency is the goal?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/531)*

**Comment by RoboErikG** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/flyout.js, line 665 \[r1\]](https://reviewable.io:443/reviews/google/blockly/531#-KOli_aRZoxDd9yZWrZb:-KOlo79wIAHvEDVNw3eR:b-al1t23) ([raw file](https://github.com/google/blockly/blob/3998ecec3af164bca19469680c9b748611e26377/core/flyout.js#L665)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> Ah, I see.  Should we consolidate that logic if consistency is the goal?
</details>
The spec is for it to replace the gap, not modify it. https://developers.google.com/blockly/guides/configure/web/toolbox#separators

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/531)*

**Comment by rachel-fenichel** [comment]
Updated with replace instead of modify.  PTAL.

**Comment by picklesrus** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/531#-:-KOpHwylNnmWjvxrWhse:bnfp4nl)*

**Pull request merged**
