### PR TITLE
Fixes bad Breton translation that misses positional specifier

### PR DESCRIPTION
**Pull request by vicng**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/1353)

### CODE REVIEW

**Comment by vicng** [comment]
This is my best guess as to where the specifier should be based on [Babelfish translator](http://www.bablefishfx.com/english-to-breton-translator/) (Google doesn't even support this language!):

arreet = Repeated
div wech = Once a day

**Comment by rachel-fenichel** [comment]
Please chat with @NeilFraser about translation--I don't want to make a habit of pushing translation changes from the Blockly side if we can find a cleaner way, like full edit access on translatewiki.

**Comment by vicng** [comment]
This isn't a translation, but a fix for a missing specifier. Doing it all from translatewiki requires a force-push (an operation that we don't control?).

**Comment by rachel-fenichel** [comment]
Changing the translation files still counts as a translation from the perspective of managing builds/releases.

Normally translations only come from translatewiki, and they get pushed directly to master.  They send us updates very regularly--more often than we rebuild them, certainly.  

If we have a problem and can't push from develop to master I can still do a simple rebuild of the files from master to update all the msg/js/*.js files.

When I do a release I start by pulling files from master into develop.  If all of the changes have come from translatewiki and we have no cherrypicks against master, this just pulls translation changes into develop.  If any translation changes originated in develop, I have to keep track of them to make sure that they don't get overwritten.  Then when pushing back from develop to master I have to track those changes again.  Translatewiki periodically pulls our msj/json/*.json files in, as far as I know, but they generally don't need to because all changes to the .json files should be originating upstream in translatewiki.

I agree that there's an issue with the translation, and if we have to we can fix it this way, but this is not the first one of these that I've handled recently.  It would be better to have full edit access at translatewiki and let the changes come in when they push, which is regularly.

**Comment by vicng** [comment]
I see. 

@NeilFraser is it possible to get full write access for translatewiki? If not, could you detail their push/pull process, so we can figure out how to avoid our manual fixes from being overwritten?

**Comment by NeilFraser** [comment]
Go ahead and commit this, but keep an eye on it over the coming weeks.  If TranslateWiki revert it, then make the change again, and notify them.

**Comment by rachel-fenichel** [comment]
I'll merge it, but more broadly I'd like a better process for handling these than trying to remember what changed while doing releases.

**Pull request merged**
