### PR TITLE
Fix checkbox delete bug.

### PR DESCRIPTION
**Pull request by marisaleung**
Fixes https://github.com/LLK/scratch-blocks/issues/956

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/1181)

### CODE REVIEW

**Comment by marisaleung** [comment]
We plan to consolidate the many workspace binds in this issue: https://github.com/google/blockly/issues/1179

**Comment by rachel-fenichel** [comment]
This looks fine as code but I cannot for the life of me understand how it fixes the checkboxes.

**Comment by RoboErikG** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/1181#-:-Kn6a2gU0MZsGaZEpGts:bnfp4nl)*

**Comment by marisaleung** [comment]
In short, flyout was using flyout's workspace to call delete. Which is bad, because then it finds and deletes only blocks in the flyout. Which means two things:
1. It doesn't delete blocks in the workspace. It only deletes blocks in the flyout.
2. It doesn't delete the checkbox in the flyout (because the checkbox is not a block with the variable inside). And refreshToolbox is not called because the flyout workspace doesn't have a toolbox, only the main workspace does.

So by binding these calls to the main workspace both problems are solved. 
1. The blocks are found in the main workspace and deleted.
2. The toolbox is refreshed, which means the checkbox is deleted.

**Comment by rachel-fenichel** [comment]
Okay, SGTM.

**Pull request merged**
