### PR TITLE
feat: add blocklyImageField CSS class to image fields

### LINKED ISSUE #8314: Add a `blocklyImageField` CSS class to image fields
In the `FieldImage` class modify the `initView` method to call `dom.addClass` with the `this.fieldGroup_` and `'blocklyImageField'`.

This change should be made against the `rc/v12.0.0` branch.

To work on this issue, comment below asking to be assigned.

### PR DESCRIPTION
**Pull request by vexora-0**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves #8314 

Fixes image fields

### CODE REVIEW

**Comment by BeksOmega** [comment]
Heya @vexora-0 can you sign the CLA? After that's done I can start reviewing this!

**Comment by vexora-0** [comment]
hey @BeksOmega can you review my pull request.

**Review by BeksOmega — APPROVED** [review]
This looks great! Thank you for the changes :D Once this passes CI I'll get it merged!

**Review by BeksOmega — CHANGES_REQUESTED** [review]
Ah actually, this is on the wrong branch :/ Can you rebased this onto `rc/v12.0.0`? If you've never done a rebase before I can give you the commands.

**Comment by vexora-0** [comment]
> t reviewin

the please give me the commands

**Pull request closed without merging**
