### PR TITLE
fixed bug that is showing browser's context menu when you right-click…

### PR DESCRIPTION
**Pull request by takaokouji**
… in workspace on Raspbian(Raspberry Pi)/Chromium.

### CODE REVIEW

**Comment by takaokouji** [comment]
I tested Raspbian on Raspberry Pi 2 with Chromium.

**Comment by NeilFraser** [comment]
Interesting.  Does the browser's context menu always appear on right-click, or is in just when clicking on certain things?  Your patch seems to only suppress the menu when clicking on an editor.

**Comment by takaokouji** [comment]
I tested Raspberry Pi 2 / Raspbian (debian version: 7.8)

Before patched:

 * free space in workspace: show browser's and blockly's context menu.
 * on instruction block in workspace: above-mention.
 * free space in toolbox: don't show both context menu.
 * on instruction block in toolbox: above-mention.
 * on text input field: show only browser's context menu.

After patched:

 * free space in workspace: show only blockly's context menu.
 * on instruction block in workspace: above-mention.
 * free space in toolbox: don't show both context menu.
 * on instruction block in toolbox: above-mention.
 * on text input field: show only browser's context menu.

**Comment by takaokouji** [comment]
My idea in this patch was from 17961f7f58a9a9f8c549d5073fd437a6adc810d0 .
It's "Support multiple Blockly instances.", and it's included  below.

```Diff
-  Blockly.bindEvent_(Blockly.WidgetDiv.DIV, 'contextmenu', null,
-                     Blockly.onContextMenu_);
```

I thought it's bug :smile_cat: , so I created this patch.

**Comment by rachel-fenichel** [comment]
Closed as very old--click handling has changed significantly.  Feel free to ping if you are still seeing the same problem and want to make a new PR.

**Pull request closed without merging**
