### PR TITLE
initial autocompletion support for input text field

### PR DESCRIPTION
**Pull request by marianoguerra**
hi, this is a PR to start the discussion about adding autocompletion support to FieldTextInput.

it adds an extra argument to the constructor which if set is a function that will be called to get the values to use as suggestion for autocompletion.

On first html input change it will lazily create a goog.ui.ac.AutoComplete https://google.github.io/closure-library/api/class_goog_ui_ac_AutoComplete.html and populate it with the result of calling the autocomplete callback provided on construction, if not provided nothing will be created.

I opened the PR to get feedback on the way it was added and on style. Also I think it would make sense to have an example of this feature, should I create a new demo under the demos folder?

### CODE REVIEW

**Comment by iapyeh** [comment]
awesome

**Comment by marianoguerra** [comment]
I forgot to mention, to make this feature display correctly a css file must be included (autocomplete.css from closure-library) how should that be handled? do we leave it to the end user?

**Comment by carlosperate** [comment]
Don't leave it to the user, as it is not a straight forward enough requirement and would also need additional documentation. You could do what blockly currently does and inject the CSS directly into the DOM.

**Comment by marianoguerra** [comment]
@carlosperate hi, is this an personal observation or a blockly one? I mean, do I have to implement it in order to get the PR merged?

regarding injecting the CSS, the required CSS is from google-closure, how should I do it? import the css into the blockly repo?

**Comment by carlosperate** [comment]
It was a personal observation. About the css, I assume you are referring to having to include a css like [this file](https://github.com/google/closure-library/blob/28d9db61f5dc639c010be74e4d61682121d2dbd7/closure/goog/css/autocomplete.css). I personally don't have any experience using closure outside of blockly, so I am not quite sure how to automatically import it during the build process, but I would not add anything from closure into the blockly repository as closure itself is a build dependency and you'd run with synchronisation issues.

**Comment by rachel-fenichel** [comment]
Closing as very old.  Feel free to ping if you're interested in updating it to work with new code.

**Pull request closed without merging**
