### PR TITLE
Basic object oriented programming support

### PR DESCRIPTION
**Pull request by LunicLynx**
Hello Neil, Hello Blockly contributters,

i tried to implement basic object oriented support and some blocks to support this.
There is still a lot missing, but i wanted to put it out there and let you have a look, and get some feedback. Please let me know if you are at all interested in oop support.

I also tried to keep the impact on the existing codebase as little as possible. Biggest problem could be the renaming of the method renameVar to changeVar.

Well, let me know what you think or need me todo to get this into the project.

Thanks
Flo

### CODE REVIEW

**Comment by LunicLynx** [comment]
Rebased on latest

**Comment by LunicLynx** [comment]
Rebased on latest

**Comment by codestar12** [comment]
This looks really cool, I'm actually trying to add some OOP function to my fork right now to access object instance variables. would this allow you to declare instance variables and and/modify variables from a selection menu?

**Comment by LunicLynx** [comment]
For defined types yes. But you would probably need something like the block editor to build types on the fly, i did not do that because i get the type definitions via a XHR request.

You can defines Types like this:

```
Blockly.Types.types = [{
  name: 'myObject',
  fields: [{
    name: 'field1',
    type: 'boolean'
  },{
    name: 'field1',
    type: 'string'
  },{
    name: 'field1',
    type: 'number'
  }]
}];
```

**Comment by LunicLynx** [comment]
I signed it!

**Comment by eudoxos** [comment]
What's the status of this merger, anyone looking at the branch conflict? The functionality looks very promising.

**Comment by LunicLynx** [comment]
I would update the branch of there is a chance to get it merged. I only did this oop implementation for a prototype.

**Comment by rachel-fenichel** [comment]
This is a big enough feature that we wouldn't merge it without a clear path forward to completing it, which I don't currently see.  There's a lot of work between the prototype and the full implementation.

We are moving toward supporting typed variables.  Variable creation and deletion is now explicit, and the next step would be to add a way to set the type of a variable on creation and use use that for the type check on output and input connections for the relevant blocks.

**Comment by carlosperate** [comment]
> Variable creation and deletion is now explicit ...

Is that in upstream blockly as well? Can the old behaviour be maintained?

**Comment by rachel-fenichel** [comment]
See https://groups.google.com/d/msg/blockly/4g-jvqrydLg/S1csbFioBQAJ for a full write-up.

**Comment by carlosperate** [comment]
Thanks!

**Comment by Suhail-ahammed** [comment]
is this feature implemented?

**Pull request closed without merging**
