### PR TITLE
Added missing require(..) statements and fixed some compiler warnings.

### PR DESCRIPTION
**Pull request by MarkusBordihn**
Adjusted build.py to find required dependencies for missing require(...) statements.

### CODE REVIEW

**Comment by MarkusBordihn** [comment]
Merged latest change, got some Warning messages but they could be Windows specific:
>
python .\build.py
Warning: Description preceding definition of synonym CONTROLS_WHILEUNTIL_INPUT_DO.
Warning: Description preceding definition of synonym CONTROLS_FOR_INPUT_DO.
Warning: Description preceding definition of synonym CONTROLS_FOREACH_INPUT_DO.
Warning: Description preceding definition of synonym CONTROLS_IF_MSG_THEN.
Warning: Description preceding definition of synonym CONTROLS_IF_ELSEIF_TITLE_ELSEIF.
Warning: Description preceding definition of synonym CONTROLS_IF_ELSE_TITLE_ELSE.
Warning: Description preceding definition of synonym MATH_CHANGE_TITLE_ITEM.
Warning: Description preceding definition of synonym TEXT_CREATE_JOIN_ITEM_TITLE_ITEM.
Warning: Description preceding definition of synonym TEXT_APPEND_VARIABLE.
Warning: Description preceding definition of synonym LISTS_CREATE_WITH_ITEM_TITLE.
Warning: Description preceding definition of synonym LISTS_INDEX_OF_INPUT_IN_LIST.
Warning: Description preceding definition of synonym LISTS_GET_INDEX_HELPURL.
Warning: Description preceding definition of synonym LISTS_GET_INDEX_INPUT_IN_LIST.
Warning: Description preceding definition of synonym LISTS_SET_INDEX_INPUT_IN_LIST.
Warning: Description preceding definition of synonym LISTS_GET_SUBLIST_INPUT_IN_LIST.
Warning: Description preceding definition of synonym PROCEDURES_DEFRETURN_TITLE.
Created file: .\msg/json/\en.json
Created file: .\msg/json/\qqq.json
Error reading .\msg\json\en.json
Traceback (most recent call last):
  File "i18n\create_messages.py", line 149, in <module>
    main()
  File "i18n\create_messages.py", line 65, in main
    source_defs = read_json_file(os.path.join(os.curdir, args.source_lang_file))
  File "C:\Users\mbordihn\Documents\GitHub\blockly\i18n\common.py", line 64, in read_json_file
    raise InputError(filename, str(e))
common.InputError: .\msg\json\en.json: Expecting property name enclosed in double quotes: line 9 column 1 (char 176)
('Error running i18n/create_messages.py: ', CalledProcessError())
SUCCESS: blockly_uncompressed.js
SUCCESS: blockly_compressed.js
Size changed from 3010 KB to 947 KB (31%).
SUCCESS: blocks_compressed.js
Size changed from 3166 KB to 1022 KB (32%).
SUCCESS: javascript_compressed.js
Size changed from 72 KB to 41 KB (57%).
SUCCESS: python_compressed.js
Size changed from 63 KB to 31 KB (49%).
SUCCESS: php_compressed.js
Size changed from 63 KB to 33 KB (52%).
SUCCESS: dart_compressed.js
Size changed from 67 KB to 35 KB (53%).
SUCCESS: lua_compressed.js
Size changed from 62 KB to 30 KB (48%).
>

**Comment by carlosperate** [comment]
Just to point out that I am getting the same issue building on windows:

```
Error reading .\msg\json\en.json
Traceback (most recent call last):
  File "i18n\create_messages.py", line 149, in <module>
    main()
  File "i18n\create_messages.py", line 65, in main
    source_defs = read_json_file(os.path.join(os.curdir, args.source_lang_file))
  File "C:\workspace\git\blockly\ardublockly\blockly\i18n\common.py", line 64, in read_json_file
    raise InputError(filename, str(e))
common.InputError: .\msg\json\en.json: Expecting property name enclosed in double quotes: line 9 column 1 (char 176)
('Error running i18n/create_messages.py: ', CalledProcessError())
```

**Comment by MarkusBordihn** [comment]
Recompiled the code on Mac OS which works fine.

**Comment by MarkusBordihn** [comment]
@NeilFraser 
Please let me know if you have any questions to these changes?

**Comment by MarkusBordihn** [comment]
This fix is needed to allow #288 or #395.

**Comment by NeilFraser** [comment]
The addition of goog.requires in the block definition files means that blocks_compressed.js will end up with all of Blockly in it.  Our goal is to have blockly_compressed.js with all the core in it, and blocks_compressed.js (and python_compressed.js, and others) as optional add-ons.

I incorporated half of the changes in the first version of this PR, but most of what remains breaks the existing developer workflow.  Remember that the vast majority of developers of Blockly-based applications are not running on a sophisticated build platform such as google3.  That's why we use an online, zero dependancies, and provide precompiled binaries.

**Comment by MarkusBordihn** [comment]
In general this is not a problem, if every file has the correct goog. statements.
You could use advance compiler options like "dependency_mode=STRICT" and "entry_point=Blockly.Blocks" to eliminate unneeded code and with "externs" you could exclude them complete.

At the moment the closure compiler is not really able to understand all dependencies correctly and so you are not able to use the advanced compilation options.

I have done this for some local tests with the local closure compiler.

Most of these advanced features are not avaible for the webservice, thats the reason why they are not included here.

**Comment by RoboErikG** [comment]
Out of curiosity, what's the benefit of making all these changes? The
current build system works pretty well and doesn't require advanced options.

**Comment by MarkusBordihn** [comment]
Is your question, what is the benefit of having correct structured code which is correctly understood by the closure compiler ?

The current build system is not really the problem, even it is use some hacks and outdated functions like "calcdeps.py".
See https://developers.google.com/closure/library/docs/calcdeps

Some of the benefits of fixing the current code:
- Less warning messages (at the moment over 80 depending on your compiler settings)
- Better code quality (easy detection for dead or unused code)
- Better integration in other closure based projects (not talking about the projects which are using only the precompiled .js files)
- Support for the "ADVANCED_OPTIMIZATIONS" compiler option
See https://developers.google.com/closure/compiler/docs/compilation_levels#advanced_optimizations

**Comment by jart** [comment]
I'm late to the game, and no one asked me for my opinion, so I'll do my best to be respectful. But I just want to voice a little support for @MarkusBordihn's opinions on code health.

Using ADVANCED compilation mode and being disciplined about the use of `goog.require` and `goog.forwardDeclare` are both very important. If these two things are not done together, type checking goes poof. You lose most of the benefits of using Closure.

Being disciplined about requires is easy if you use Emacs. Just install [js2-closure](https://github.com/jart/js2-closure). It pretty much automates it like you'd expect from Eclipse.

**Pull request closed without merging**
