### PR TITLE
dragging beetween different workspaces

### PR DESCRIPTION
**Pull request by macherel**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Test Coverage

Tested on:

### CODE REVIEW

**Comment by macherel** [comment]
Here's some code I write trying to drag blocks between workspaces.
My first attempt (in comment) was to create a new block in the new workspace, delete the old one and create a new dragging event.
Not having found how to do, I decide to change the current block and the current blockDragger object to adapt it to the new workspace.

**Comment by rachel-fenichel** [comment]
Hi @macherel,

Please read the style guide and make sure your code conforms to it.  In particular, your code needs to work on IE11.

**Comment by macherel** [comment]
Some code was rewritten specificly for IE because of a lack of standard functionality in IE.
I suggest using some polyfill to simplify the written code.

I'm not satisfied with the solution I proposed but the written code is uglier without polyfill

**Comment by rachel-fenichel** [comment]
Unfortunately this code cannot be accepted in its current form.  It leaves a lot of Blockly in a broken state at the end of the drag.  To make this change you'll need to consider all of the state that you're modifying when moving the block around.  Here are some problems I see with the current code:

- Most drag-related code is intended to be called in start/end pairs.  For instance, a call to start a block drag must be matched by a call to end the block drag.  The drag-ending code cleans up loose ends, returns all CSS to its default state, etc.  

- Moving a block between workspaces by changing its `workspace` property is also problematic.  A block has more than one reference to its workspace--for instance, all connections store a pointer to the source block's workspace's connection DB.  This is set at connection construction.  The way you're moving blocks doesn't change that.

- What if there is already a block in the target workspace with the ID of one of the dragging blocks?  It gets overwritten in the DB but may still have references lying around; it is definitely still visible.

**Comment by macherel** [comment]
I agree with all the comments and that's why I was not satisfied with my code 
I share your point of view and I first tried to programmatically stop the current drag and create a new block in the new workspace on which we could programmatically start a new drag.

The problem is that I did not find the way to programmatically manage drag events. It is possible to stop the current drag by disposing the current dragging block but I have not found a way to restart the drag on the new block.

**Pull request closed without merging**
