### PR TITLE
November 2017 merge to master

### LINKED ISSUE #1369: Race condition when loading messages
These lines all trigger errors in Blockly Games when compiled:

https://github.com/google/blockly/blob/master/blocks/math.js#L507
https://github.com/google/blockly/blob/master/blocks/loops.js#L282
https://github.com/google/blockly/blob/master/blocks/loops.js#L286

The issue is that the properties on Blockly.Msg may not be loaded yet, and these dynamic tooltips are set to undefined.  The compiled test in Blockly does not suffer from this issue, presumably due to minor differences in the order files are loaded.

### PR DESCRIPTION
**Pull request by rachel-fenichel**
**Bugs fixed in this release (not all bugs were present on master):**

- #1352 (Spelling error in index.html)
- #1365 (Multiple setWarningText() calls while dragging only work on the last call)
- #1366 (Break block doesn’t show warning when it isn’t inside a loop)
- #1368 (Bad use of typeof)
- #1369 (Race condition when loading messages)
- #1373 (Events can sometimes be dropped from the event queue)
- #1386 (Regression in message handling in the code demo)
- #1399 (in build.py self.do_compile (line 274) not returning valid JSON)
- #1404 (Can’t use uncompressed Blockly from the filesystem after updating the compressed library)
- #1416 (Permanent connection hints after failed connection)
- #1417 (Block bumping is gone)
- #1421 (Text/Number/Angle inputs offscreen in RTL)
- #1444 (text_charat mutator is unable to load generator tests)
- #1447 (Can’t add inputs to function in Toolbox demo)
- #1448 (Step interpreter demo: Child blocks scatter when set block disconnected from parent)

**Release notes:**

- Fixes bad Breton translation that misses positional specifier
- Add Google Analytics info to new codelab files
- Do not assume an indentation of 2 spaces in function blocks
- Convert compile demo to a unit test
- Fix indentation for function blocks with return statements
- Minor improvements to block rendering performance
- Fix indentation for function blocks with return statements
- Don’t share the warning text PID map between blocks
- Move some context menu options into contextmenu.js
- Fix typo in mixin name
- Don’t check typeof == undefined in variable deserialization
- Fix #1369: resource loading order constraints, interpolation tokens in message expansionFix code demo in IE if Blockly is compiled harder
- Add JSDoc for blockId, varId, workspaceId, group, and recordUndo
- Update templates to minimize checkboxes and use HTML comments
- Fix logic bugs in event coalescing
- Restore translations
- Reenable compressed builds
- Switch compile to HTTPS
- Remove unnecessary restriction on variables names
- Allow external code to load new audio
- Check workspace.isDragging() instead of Blockly.dragMode_
- Get rid of highlighting when releasing the drag would delete instead
- Use variabletype instead of variableType to avoid serialization problems
- Fix text input widget position in RTL
- Use msg references in block JSON for text_charat
- Terminology: “background button” -> “mat” in the flyout
- Right-align flyout buttons in RTL
- Lint and style fixes
- Enable eslint on travis
- Stop blocks from exploding (cherry-picked)
- Fix broken mutator for text_charat (cherry-picked)

### Test Coverage

Tested on:
- [ ] Desktop:
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] Opera
  - [ ] IE 10+
  - [ ] IE 11
  - [ ] EDGE

- [ ] Smartphone/Tablet/Chromebook (please complete the following information):
  - [ ] Android
  - [ ] iOS

- [ ] Generators

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Cherry-picked in #1449 and rebuilt.

**Comment by microsoftsam** [comment]
There's something funky going on with disabled blocks and Edge 16 (Only). I don't think this is a regression, but investigating.. 

Here's what it looks like: 
edge16disabled

**Comment by microsoftsam** [comment]
Edge issue repro's on Blockly playground in Edge 16, so not a regression. This looks like an Edge bug, I'll let the team know about it.

**Comment by microsoftsam** [comment]
So IE 11 is broken in this release. I tracked it down, and this commit https://github.com/google/blockly/commit/4262b090028e680aee094ec0087bcf8acaf9fab8 changed element.parentNode to element.parentElement in WorkspaceSvg.getParentSvg
In IE11 parentElement is undefined for SVG elements whereas element.parentNode is.

**Comment by NeilFraser** [comment]
With respect to parentElement, that's my fault.  I had checked the docs for IE when making that change, but missed that it wasn't available for SVG.  Reverting to parentNode is fine, it will add a compiler warning, but there are about 700 of them so one more won't do us any harm.

Thanks @microsoftsam

**Comment by rachel-fenichel** [comment]
Cherry-picked in #1451, rebuilt, and pushed back up to my github.io site.

@NeilFraser are you reverting to parentNode, or should I do that?

**Pull request merged**
