### PR TITLE
Fix warnings related to connections.

### PR DESCRIPTION
**Pull request by samelhusseini**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Fix 47 compiler warnings related to connections.

### Proposed Changes

All visibility changes.

Renamed connection. ``x_`` to ``x`` and made it package.
Renamed connection. ``y_`` to ``y`` and made it package.
Renamed connection.``checkType_`` to ``checkType`` and made it package.
Renamed connection.``tighten_`` to ``tighten`` and made it package.
Renamed connection.``lastConnectionInRow_`` to ``lastConnectionInRow`` and made it package.
Renamed block.``moveConnections_`` to ``moveConnections`` and made it package.

Changed ``connection.makeConnection_`` from private to protected.
Changed ``connection.connect_`` from private to protected.

### Test Coverage

Tested on:

### CODE REVIEW

**Comment by BeksOmega** [comment]
Just to give you a heads up, I have a PR in the works that changes x & y to a Blockly.utils.Coordinate and moves it to the RenderedConnection. This is good (^-^)b, I just didn't want to be stepping on toes.

**Comment by samelhusseini** [comment]
That sounds good @BeksOmega, just make sure you use the right visibility :D

**Comment by rachel-fenichel** [comment]
Most of these look fine.

The `checkType` rename may cause problems because it's a function that developers are likely to use in their mutators.  I suggest making the change but leaving behind a deprecated `checkType_` function that we can delete in a few releases.

**Comment by samelhusseini** [comment]
Sounds good. Should I ``console.warn``.

**Comment by rachel-fenichel** [comment]
Yup, `console.warn` is fine.

**Comment by samelhusseini** [comment]
Done.

**Pull request merged**
