### PR TITLE
dragging between different workspaces

### PR DESCRIPTION
**Pull request by macherel**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [ ] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves
Allow to move blocks from one workspace to another using drag/drop

### Proposed Changes
When dragging a block, if the mouse is over another workspace
* copy the block to the new workspace,
* stop dragging old block (dispatch mouseup event)
* dispose the old block
* start dragging the new block (dispatch mousedown and mousemove events)

### Test Coverage

Tested on:
* Desktop Chrome
* Desktop Firefox

* Windows Internet Explorer 11

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
I will leave it to Rachel to determine if this is how we want to approach this problem.

Please review [the style guide](https://developers.google.com/blockly/guides/modify/web/style-guide) and correct the code. The included ESLint rules should help you identify problems.

**Comment by macherel** [comment]
About ESLint rules (more particularly indent.callexpression), it appears to be inconsistent with the rules that are verified by Travis.

**Comment by rachel-fenichel** [comment]
Travis runs with the rules in our .eslintrc.

**Comment by macherel** [comment]
There's no rule for indent.callexpression in .eslintrc and default value is "1"
Before my last commit, my code respect this rule but Travis job fails. I had to change indentation to pass CI (as it was explained in the Travis errors).
Apart from that, I didn't see any other styling errors

**Comment by rachel-fenichel** [comment]
The rule for callexpression:  https://github.com/google/blockly/blob/develop/.eslintrc#L20

"Apart from that, I didn't see any other styling errors."
- Horizontal whitespace: https://google.github.io/styleguide/jsguide.html#formatting-horizontal-whitespace
- Line wrap at 80 characters
- Line breaking: https://google.github.io/styleguide/jsguide.html#formatting-where-to-break

Some of these are things that you can see by looking at the style of the surrounding code, without even reading the style guide.

**Comment by macherel** [comment]
Thank you for your feedback
My branch was not up to date from upstream branch.
Concerning horizontal whitespace, I propose to add ```"keyword-spacing": ["error"]``` to eslintrc
And line wrap isset to 120 in eslintrc

**Pull request closed without merging**
