### PR TITLE
Blockly Factory: Resize Workspaces in Workspace Factory

### PR DESCRIPTION
**Pull request by evd2014**
Makes the height of the workspaces in workspace factory resizable. Also improves the scrolling for the workspace factory options (before, it was possible for some options to sometimes get stuck underneath). Also hides Block Factory so that it can't be seen when the screen jumps down when selecting a color for a category. Also enables scrolling for workspace factory and the exporter if necessary (only needed if screen is very small).

screen shot 2016-08-24 at 3 46 22 pm

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/593)

### CODE REVIEW

**Comment by evd2014** [comment]
@picklesrus @quachtina96

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/593#-:-KPyj6eCZ68xR6yPY7sY:badbw0l)*

**Comment by quachtina96** [comment]
2 nit comments, otherwise :lgtm:  :)

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/factory.css, line 422 \[r1\]](https://reviewable.io:443/reviews/google/blockly/593#-KQ1ZkKGMk8AgK_BtLwo:-KQ1ZkKHjeVEA0ZyqBea:b-w8bqk3) ([raw file](https://github.com/google/blockly/blob/7c5e258a9a0dfe169e1219e51d370f299cc4b78b/demos/blocklyfactory/factory.css#L422)):*
> ```CSS
> }
> 
> #createHeader {
> ```

blank CSS?

---

*[demos/blocklyfactory/factory.css, line 430 \[r1\]](https://reviewable.io:443/reviews/google/blockly/593#-KQ1ZpZi7wKPJSpQ8Nng:-KQ1ZpZi7wKPJSpQ8Nnh:b-10o17o) ([raw file](https://github.com/google/blockly/blob/7c5e258a9a0dfe169e1219e51d370f299cc4b78b/demos/blocklyfactory/factory.css#L430)):*
> ```CSS
>   padding-bottom: 10px;
>   width: 35%;
>   height: 77%;
> ```

alphabetize

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/593#-:-KQ1_7P6SjsX0EsAgoYB:b9ae1ih)*

**Comment by evd2014** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/factory.css, line 422 \[r1\]](https://reviewable.io:443/reviews/google/blockly/593#-KQ1ZkKGMk8AgK_BtLwo:-KQ2EijnOm3aSRzi4m-l:b-896fix) ([raw file](https://github.com/google/blockly/blob/7c5e258a9a0dfe169e1219e51d370f299cc4b78b/demos/blocklyfactory/factory.css#L422)):*
<details><summary><i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>
> blank CSS?
</details>
Done.

---

*[demos/blocklyfactory/factory.css, line 430 \[r1\]](https://reviewable.io:443/reviews/google/blockly/593#-KQ1ZpZi7wKPJSpQ8Nng:-KQ2EjJ0p4wiuoZ0KxmD:b-896fix) ([raw file](https://github.com/google/blockly/blob/7c5e258a9a0dfe169e1219e51d370f299cc4b78b/demos/blocklyfactory/factory.css#L430)):*
<details><summary><i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>
> alphabetize
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/593)*

**Comment by picklesrus** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/593#-:-KQ33fWvfM7IdLH13NN7:bnfp4nl)*

**Pull request merged**
