### PR TITLE
Blockly Factory: Generate Block Library Category in Workspace Factory

### PR DESCRIPTION
**Pull request by evd2014**
Generates and updates a "block library category" in workspace factory containing all the blocks in block library. This allows the user to be able to use blocks created in Block Factory and saved in their Block Library directly in the Workspace Factory editing workspace. The Block Library category is updated each time the user switches to the workspace factory tab in Blockly Factory. 

block library category

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/568)

### CODE REVIEW

**Comment by evd2014** [comment]
@picklesrus @vicng @quachtina96

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/568#-:-KPTmB4b0d87fHacEdL_:bvyui8)*

**Comment by picklesrus** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/568#-:-KPTrhj0Rqk3K33vnmYi:bnfp4nl)*

**Comment by quachtina96** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/568#-:-KPU_o4wJbKbtDUM2m7V:bnfp4nl)*

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/568#-:-KPUmmIcHrNXlvWUJPVZ:bnfp4nl)*

**Comment by picklesrus** [comment]
This now has conflicts. Let me know when they're fixed and I'll merge!

**Comment by evd2014** [comment]
Fixed!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/568#-:-KPUrdpksk67xu4FH8LD:bt2vr0y)*

**Pull request merged**
