### PR TITLE
Blockly Factory: Import Blocks to Workspace Factory

### PR DESCRIPTION
**Pull request by evd2014**
Allows the user to import blocks into workspace factory from a file containing block definitions in JSON or Javascript. Automatically generates a category for the imported blocks and adds it to the toolbox workspace so that the user can use these blocks in their toolbox or pre-loaded blocks. 

import blocks2

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/566)

### CODE REVIEW

**Comment by evd2014** [comment]
@picklesrus @vicng @quachtina96

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/566#-:-KPQ6tiySg_4sxByicPz:bvyui8)*

**Comment by quachtina96** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 31 \[r1\]](https://reviewable.io:443/reviews/google/blockly/566#-KPQC_BWk28DlRLdrfRM:-KPQC_BWk28DlRLdrfRN:bymm1un) ([raw file](https://github.com/google/blockly/blob/d1d941fc195985255ceb83bcf426c35126297dbc/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L31)):*
> ```JavaScript
>  */
> 
> goog.require('FactoryUtils');
> ```

in a separate CL it'd be good to have requires and provides on the workspace factory files to quickly and explicityly show dependencies.

---

*[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 184 \[r1\]](https://reviewable.io:443/reviews/google/blockly/566#-KPQBd4MYKHneXIw7Kuq:-KPQBd4MYKHneXIw7Kur:b2ytcp) ([raw file](https://github.com/google/blockly/blob/d1d941fc195985255ceb83bcf426c35126297dbc/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L184)):*
> ```JavaScript
> };
> 
> WorkspaceFactoryGenerator.prototype.defineBlocks = function(blockTypes) {
> ```

missing comment, also I would use a better name--getDefinedBlocks?

NOTE: if you change this you need to change your call to this in the controller's importBlocks func

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/566)*

**Comment by evd2014** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 31 \[r1\]](https://reviewable.io:443/reviews/google/blockly/566#-KPQC_BWk28DlRLdrfRM:-KPTPyZCtuYZGlTX-YX5:b-j96j0i) ([raw file](https://github.com/google/blockly/blob/d1d941fc195985255ceb83bcf426c35126297dbc/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L31)):*
<details><summary><i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>
> in a separate CL it'd be good to have requires and provides on the workspace factory files to quickly and explicityly show dependencies.
</details>
Agreed. On my list of things to do..

---

*[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 184 \[r1\]](https://reviewable.io:443/reviews/google/blockly/566#-KPQBd4MYKHneXIw7Kuq:-KPTPtMDHFZnauFCLIMy:b-c0lrsp) ([raw file](https://github.com/google/blockly/blob/d1d941fc195985255ceb83bcf426c35126297dbc/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L184)):*
<details><summary><i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>
> missing comment, also I would use a better name--getDefinedBlocks?
> 
> NOTE: if you change this you need to change your call to this in the controller's importBlocks func
</details>
Completely missed that, thanks! Added comment and changed name (in generator and in controller)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/566)*

**Comment by picklesrus** [comment]
:lgtm:  one nit

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 1122 \[r3\]](https://reviewable.io:443/reviews/google/blockly/566#-KPTqDMFgd5DDmz7Zj0Y:-KPTqDMGLCSLdffehJUP:b-z2dxkd) ([raw file](https://github.com/google/blockly/blob/be7236fa4d12483b702a2ee740463214ad389699/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L1122)):*
> ```JavaScript
>   // Read the file asynchronously.
>   reader.readAsText(file);
> ```

remove extra line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/566#-:-KPTq_GmLTh8uHalRQ5a:btsx5f2)*

**Comment by evd2014** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 1122 \[r3\]](https://reviewable.io:443/reviews/google/blockly/566#-KPTqDMFgd5DDmz7Zj0Y:-KPU0JWbK9Ikv9PIk17A:bt2vr1b) ([raw file](https://github.com/google/blockly/blob/be7236fa4d12483b702a2ee740463214ad389699/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L1122)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> remove extra line.
</details>
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/566)*

**Comment by quachtina96** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/566#-:-KPUQDJzHZ0R8Evs25H-:bnfp4nl)*

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/566#-:-KPUmNrO4r9FnpiCo352:bnfp4nl)*

**Pull request merged**
