### PR TITLE
Add basic package.json for npm support.

### PR DESCRIPTION
**Pull request by Kaworru**
This basic package.json file will allow the integration with the nodejs package manager npm.

More infos:
https://docs.npmjs.com/files/package.json

If need we could also publish this to the npm repositories under https://www.npmjs.com/.

### CODE REVIEW

**Comment by carlosperate** [comment]
Does npm work on a "push for each release" kind of cycle, doesn't it? How is that going to work with Blockly that works on a "rolling release" on master?

**Comment by Kaworru** [comment]
Its depend on the implementation, if you use the github repro url for your npm config, then it will use the latest files like:
...
  "dependencies": {
    "blockly-src": "https://github.com/google/blockly/tarball/master"
  }
...

If you want to publish this to the global npm repository it would be on an "push for each release".
But for my usecase having this file on the github repro URL would be enough, so there is no need for me to have it pushed to the npm repro.

I added  "private": true to the package.json to make sure that nobody is pushing this to the npm repro.

**Comment by mogmios** [comment]
It might be worth the effort of pushing to npm. A lot more people will take the time to use libraries that work as standard packages. Not only are they easier to use but they feel more mature which is often a requirement for a work environment.


Thanks,
Michael McGlothlin

**Comment by Kaworru** [comment]
Agree, but to get the library working as standard packages, there is some more work to do.
This is the first step to be able to get the current source code over npm and gitHub.

There are already some simple npm integrations with an static library like:
https://www.npmjs.com/package/node-blockly
https://www.npmjs.com/package/blockly

**Comment by NeilFraser** [comment]
Pulling this request so that it may be tested.  I know nothing about node.js, so look forward to seeing a "hello world" demo of Blockly.

carlosperate has a good point.  Does this file need to be updated by build.py?

**Comment by Kaworru** [comment]
No this file don't needs to be updated by the build.py.

Technical it works the following way (like an BUILD file):
* You define this git repro URL as dependencies for your project.
* npm will automatic download the package.json and the defined files (in this case all) to store them in an seperate module folder, so you have an 1:1 copy of the current source.
* Depending on advance definitions of the package.json file you would be able to test, lint or compile the code with simple commands like "npm run lint", "npm run test", "npm run build" or to integrate the code in your existing projects.

As soon I have finalized my integration (1-2 weeks), I will create an additional pull request with such advanced options.

As long you don't upload any bundle to the npm repro and use the git url like in my example above you will always get the latest code.

**Comment by carlosperate** [comment]
Would there be an issue with that in that there is no way to know which version of Blockly somebody is getting when the do `npm install blockly`? I ask regarding the fact that this way all versions would be set to 1.0.0?

Say "user a" npm installs blockly globally today. Then tomorrow Blockly updates the codebase with a new feature, and "user b" creates a project using this feature. If after that "user a" does an `npm install` of all the "user b" project dependencies, wouldn't that cause an issue? as the "version 1.0.0" from "user a" (installed globally) is not the same as the "version 1.0.0" that "user b" used in his project?

**Comment by Kaworru** [comment]
Each modul has his own "node_modules" folder with their needed dependencies.
So it is no problem to have different versions of the same library for different modules.

If an user wants to update their files they would use "npm update" which automatically downloads the latest version for all packages.

The version number is more relevant if you push an package to the npm repro so that you could get a special version, but this is not possible on GibHub only.

Does Blockly has any specific version number for each build ?
I checked some of the source code and don't found any version number on it.
If Blockly has any internal version number it could be updated in the package.json file for an better overview.
But as long this file will be only used over GitHub I see no real reason for it.

**Comment by carlosperate** [comment]
Blockly does not have any version number, it's a rolling release on master, but the build file could simply just "add 1" to whatever is on the json file if necessary. This only makes sense if each "blockly compilation" end ups pushing the package to npm, in this case we are talking about doing this almost on a daily basis. I'm not familiar enough with npm to tell if there is any advantages to this.

**Pull request merged**
