### PR TITLE
Fix css for comment text on Chrome

### PR DESCRIPTION
**Pull request by leanhvu1989**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

https://github.com/google/blockly/issues/1382
### Proposed Changes
Change CSS of class blocklyCommentTextarea

Change CSS of class blocklyCommentTextarea by adding property "overflow" is "hidden"
### Test Coverage

Tested on:
Desktop Chrome
Desktop Firefox

### CODE REVIEW

**Comment by leanhvu1989** [comment]
I signed it!

**Comment by AnmAtAnm** [comment]
Thanks for pointing this out.  I've created issue #1690 to track it.

My gut says the contents should scroll if there isn't enough room, rather than just cut off. Since workspace comments may also be affected, I'll let @rachel-fenichel reply.

**Comment by leanhvu1989** [comment]
@AnmAtAnm: this pull will resolve 2 issues:
- Comment text disappears
- UI freeze when comment is a long text (https://github.com/mit-cml/appinventor-sources/issues/1022)

**Comment by rachel-fenichel** [comment]
Hi @leanhvu1989,

We've incorporated this change into #1687, which just landed.  Thanks for investigating.

**Pull request closed without merging**
