### PR TITLE
fix: Remove references to getFastTextWidth (#8277)

### PR DESCRIPTION
**Pull request by ga-fleury**
Fixes: #8277

**feat: Remove references to getFastTextWidth (#8277)**

### CODE REVIEW

**Review by BeksOmega — APPROVED** [review]
This looks great! Thank you for the fixes =) I'll get this merged once CI passes.

For future peoples: Pulled this down and did some performance profiling, and impacts were minimal. On a 1k Scatter, self-time for `getTextWidth` was `0.3%`.

**Comment by BeksOmega** [comment]
Looks like formatting is failing, you can run `npm run format` and commit the changes to fix it.

**Review by BeksOmega — CHANGES_REQUESTED** [review]
Marking this as changes requested

**Comment by BeksOmega** [comment]
Heya @ga-fleury Are you still interested in working on this?

**Comment by ga-fleury** [comment]
@BeksOmega format changes commited!

**Review by BeksOmega — APPROVED** [review]
Thank you again for your work on this!

**Pull request merged**
