### PR TITLE
Remove rogue line breaks in translated messages.

### PR DESCRIPTION
**Pull request by NeilFraser**

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
image

**Comment by AnmAtAnm** [comment]
Do we need to correct TranslateWiki upstream?

**Comment by NeilFraser** [comment]
I've no idea.  Suggest we just watch what happens in the next couple of pushes from them.  If they revert it, then yes.

**Comment by rachel-fenichel** [comment]
I manually edited all three.

**Pull request merged**
