### PR TITLE
gitignore the .idea directory which contains jetbrains artifacts

### PR DESCRIPTION
**Pull request by dwesty17**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

https://github.com/google/blockly/issues/3475

### Proposed Changes

Add `.idea` to `.gitignore`

### Reason for Changes

So that the `.idea` directory isn't accidentally committed/to make it easier for people who just JetBrains products to contribute to the repository.

### CODE REVIEW

**Comment by dwesty17** [comment]
@googlebot I signed it!

**Comment by BeksOmega** [comment]
I think this might fit better in your personal git exclude, since not everyone uses jetbrains IDE's. [Info about git excludes](https://help.github.com/en/github/using-git/ignoring-files#explicit-repository-excludes).

This is how I manage my .idea files and I think it works great. Do you think it could work for your situation?
--Beka

**Comment by dwesty17** [comment]
Cool! I actually didn't know that was a thing. This works for me.

I think it probably still makes sense to have given that it's a pretty popular IDE, in the same way that not everyone uses Macs, but `.DS_Store` is in most `.gitignore` files. Reduces friction for getting started ever so slightly.

Thanks for the info about `git excludes` though! I'll go ahead and close this out.

**Comment by NeilFraser** [comment]
I didn't know that was a thing either.  Which is why `*.komodoproject` is in Blockly's .gitignore (I'm a Komodo user).

**Comment by dwesty17** [comment]
Got it 🙂

**Pull request closed without merging**
