### PR TITLE
Fix jsdoc syntax

### PR DESCRIPTION
**Pull request by alschmiedt**
## The basics

- [ ] I branched from develop
- [ ] My pull request is against develop
- [ ] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Proposed Changes
Update:
@private {type} to be

@type {type} 
@private 

### Reason for Changes

Jsdocs are complaining

### Test Coverage

Tested on:

### CODE REVIEW

**Comment by samelhusseini** [comment]
Just for consistency I take it? Because the short hand syntax is valid.

**Comment by samelhusseini** [comment]
Out of curiously, what’s complaining?

**Comment by alschmiedt** [comment]
we are getting:
WARNING: The @private tag does not permit a value; the value will be ignored. File: basenode.js,

It's just a warning but we don't have any others so far so just thought best to fix.

**Comment by samelhusseini** [comment]
Just a note to cherry pick this back to develop :)

**Pull request merged**
