### PR TITLE
Add a dropdown field with a search box.

### PR DESCRIPTION
**Pull request by TechplexEngineer**
The addition of this field will alleviate finding of items in dropdown lists for larger programs. One use case is for programs with many variables. Changing the variables_get block to use this field would allow users to filter the list of variables, to find just the variable they need.

image

### CODE REVIEW

**Comment by TechplexEngineer** [comment]
I signed it!

**Comment by rachel-fenichel** [comment]
Hey there!

Rather than creating a completely new field for this, you can add it as an option in the constructor of FieldDropdown.  By default there should be no search box, and all options should be shown.  The developer could choose to enable the search box when creating the field.

@NeilFraser thoughts?

**Comment by joseluiz98** [comment]
Hey guys! Sorry to reopen a old issue.

This feature is available on Blockly?

**Comment by fayvaz** [comment]
I wonder if this feature is available on Blockly, too.

**Comment by rachel-fenichel** [comment]
We don't have this in blockly core, but have an open issue for writing a plugin to do it: https://github.com/google/blockly-samples/issues/199

**Pull request closed without merging**
