### PR TITLE
Integrate variable management into develop.

### PR DESCRIPTION
**Pull request by rachel-fenichel**
Followup work includes updating all documentation when this hits master.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/557)

### CODE REVIEW

**Comment by picklesrus** [comment]
Review status: 0 of 98 files reviewed at latest revision, 13 unresolved discussions.

---

*[core/block.js, line 199 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOSpNe4zf7Nv63KvpI:-KPOSpNfY6qY8VTLL3Fw:b-pbwet1) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/block.js#L199)):*
> ```JavaScript
>   if (!this.workspace) {
>     // Already deleted.
>     return;
> ```

I'm curious why we try and delete it again? 

---

*[core/flyout.js, line 721 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPObI9K-9M5lHFRRIDZ:-KPObI9LVWjUqN9kKSKH:b-4pixdz) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/flyout.js#L721)):*
> ```JavaScript
>  */
> Blockly.Flyout.prototype.layout_ = function(contents, gaps) {
>   this.workspace_.scale = this.targetWorkspace_.scale;
> ```

why set the scale here?   Change seems unrelated to variables, but then maybe this is to get the button to scale properly?  I vaguely remember having a conversation about this exact line of code just in a different place before :)

---

*[core/flyout.js, line 746 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOc2RRAbzpXaNBKkPG:-KPOc2RSKySspyXsSugE:bw1f6le) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/flyout.js#L746)):*
> ```JavaScript
>         cursorX += tab;
>       }
>       block.moveBy((this.horizontalLayout_ && this.RTL) ? -cursorX : cursorX,
> ```

This change seems unrelated too.

---

*[core/flyout.js, line 801 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOc_XdPW97zSF4RMNf:-KPOc_XdPW97zSF4RMNg:b-g89r03) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/flyout.js#L801)):*
> ```JavaScript
> 
>   for (var i = 0, button; button = this.buttons_[i]; i++) {
>     button.dispose();
> ```

what type is this list of buttons?  I wanted to take a quick look at what the dispose to make sure the event handler wasn't left around, but I don't know where to look. Thanks javascript.

---

*[core/flyout_button.js, line 103 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOeypPBXR2DWDmlNAX:-KPOeypPBXR2DWDmlNAY:b-7yykgs) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/flyout_button.js#L103)):*
> ```JavaScript
>   svgText.textContent = this.text_;
> 
>   this.width = svgText.getComputedTextLength() +
> ```

this only happens once on flyout creation, right? or is it every time the variable flyout category opens?  getComputedTextLength is now on my evil list...

---

*[core/flyout_button.js, line 107 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOfMUdKJsfOxyFuIlw:-KPOfMUe7HjjicS1D82A:b-ql9udw) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/flyout_button.js#L107)):*
> ```JavaScript
>   this.height = 20; // Can't compute it :(
> 
>   rect.setAttribute('width', this.width);
> ```

actually, if this were a div instead, would you still need to pre-calculate this width?  Maybe yes, because you need to calculate the width of the flyout?

---

*[core/flyout_button.js, line 152 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOfzHUlv0u6Z9_4yGD:-KPOfzHV2mHgW6NkA9Ve:b-ykokj8) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/flyout_button.js#L152)):*
> ```JavaScript
>     this.svgGroup_ = null;
>   }
>   this.workspace_ = null;
> ```

should targetWorkspace, text, position, and any other members be set to null?

---

*[core/variables.js, line 47 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOgeCZyEjtaNCWRWGc:-KPOgeCZyEjtaNCWRWGd:b-sowr0z) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/variables.js#L47)):*
> ```JavaScript
> Blockly.Variables.allUsedVariables = function(root) {
>   var blocks;
>   if (root instanceof Blockly.Block) {
> ```

how come you changed this?

---

*[core/variables.js, line 134 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOiIIgPhH4_3ngoTar:-KPOiIIgPhH4_3ngoTas:b-brnopo) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/variables.js#L134)):*
> ```JavaScript
>       block.setAttribute('type', 'variables_set');
>       if (Blockly.Blocks['math_change']) {
>         block.setAttribute('gap', 8);
> ```

why is the gap different for math_change vs the rest? Just because it isn't a standard setter so you want the visual separation?

---

*[core/variables.js, line 175 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOjMYwW63b41gqpiWd:-KPOjMYwW63b41gqpiWe:b44izkt) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/variables.js#L175)):*
> ```JavaScript
>     }
> 
>     for (var i = 0; i < variableList.length; i++) {
> ```

should this start at 1? IIUC, you did everything for the variable at index 0 in the if above. 

---

*[core/variables.js, line 309 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOjx43YePjgFCO9F2j:-KPOjx43YePjgFCO9F2k:b-c59hrr) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/variables.js#L309)):*
> ```JavaScript
>     workspace.variableList.splice(variableIndex, 1);
>   }
> ```

extra line

---

*[core/variables.js, line 322 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOkHGgma6Pz47d8qQC:-KPOkHGgma6Pz47d8qQD:b-qa6ub7) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/variables.js#L322)):*
> ```JavaScript
> Blockly.Variables.createVariable = function(workspace) {
>   var text = Blockly.Variables.promptName(Blockly.Msg.NEW_VARIABLE_TITLE, '');
>   // Since variables are case-insensitive, ensure that if the new variable
> ```

Should this comment be here?

---

*[core/workspace.js, line 121 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOl2EwyufBn9V2mlIz:-KPOl2Ex4W4ENqkmX94D:bfrhnda) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/workspace.js#L121)):*
> ```JavaScript
> Blockly.Workspace.prototype.addTopBlock = function(block) {
>   this.topBlocks_.push(block);
>   if (this.isFlyout) {
> ```

Is this here to catch cases like undo/redo, load from xml, etc where a variable is introduced to the workspace not through the create new variable button?  Maybe throw a comment in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/557)*

**Comment by rachel-fenichel** [comment]
Review status: 0 of 98 files reviewed at latest revision, 13 unresolved discussions.

---

*[core/block.js, line 199 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOSpNe4zf7Nv63KvpI:-KPPEcMYbtYxwOJvtvW1:b-yf59dd) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/block.js#L199)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> I'm curious why we try and delete it again? 
</details>
The case I ran into was when I had a block that used a variable as an input to another block that used a variable.  Variable deletion gets a list of uses and deletes each item in the list in turn.  
If I disposed of the outer block first, it would also dispose of the inner block.  Then I would go to the next block in my list of uses, and it would already have been disposed of.

---

*[core/flyout.js, line 721 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPObI9K-9M5lHFRRIDZ:-KPPI3oTrnjAdSwr-R1J:b7fkqui) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/flyout.js#L721)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> why set the scale here?   Change seems unrelated to variables, but then maybe this is to get the button to scale properly?  I vaguely remember having a conversation about this exact line of code just in a different place before :)
</details>
Yes, it's to get the button to scale properly.  The flyout button has access to the workspace it's in, but not the main workspace, and needs to know what size to be.

---

*[core/flyout.js, line 801 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOc_XdPW97zSF4RMNf:-KPPJl4VIOiMs32cVlpu:bxz524r) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/flyout.js#L801)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> what type is this list of buttons?  I wanted to take a quick look at what the dispose to make sure the event handler wasn't left around, but I don't know where to look. Thanks javascript.
</details>
It's a Blockly.FlyoutButton.  Will add an @type annotation ({!Array.<!Blockly.FlyoutButton>}) and an @private tag.

---

*[core/flyout_button.js, line 103 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOeypPBXR2DWDmlNAX:-KPPKfgnLR6MJ7v-KLLG:bjk1i1a) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/flyout_button.js#L103)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> this only happens once on flyout creation, right? or is it every time the variable flyout category opens?  getComputedTextLength is now on my evil list...
</details>
Every time the variable flyout category opens.

---

*[core/flyout_button.js, line 107 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOfMUdKJsfOxyFuIlw:-KPPKqsDesosO5EWto9d:bsvvnaq) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/flyout_button.js#L107)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> actually, if this were a div instead, would you still need to pre-calculate this width?  Maybe yes, because you need to calculate the width of the flyout?
</details>
I think I still would need to.  Why would a div stop that?

---

*[core/flyout_button.js, line 152 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOfzHUlv0u6Z9_4yGD:-KPPKuvoII0rZ45T2YAY:bcpufxt) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/flyout_button.js#L152)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> should targetWorkspace, text, position, and any other members be set to null?
</details>
Target workspace, yes.  The other two: I'm not sure.  I think GC will pick them up.

---

*[core/variables.js, line 47 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOgeCZyEjtaNCWRWGc:-KPPLNVaDvfJ9CDVvDk8:bmcevga) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/variables.js#L47)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> how come you changed this?
</details>
Because Neil commented that there was a better way, when I changed parallel code somewhere else.

---

*[core/variables.js, line 134 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOiIIgPhH4_3ngoTar:-KPPLUIp91rUiEU12rBW:b4chhui) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/variables.js#L134)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> why is the gap different for math_change vs the rest? Just because it isn't a standard setter so you want the visual separation?
</details>
Yup, just for visual emphasis.

---

*[core/variables.js, line 175 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOjMYwW63b41gqpiWd:-KPPLha8f5ennQfstWNf:b-w0wghc) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/variables.js#L175)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> should this start at 1? IIUC, you did everything for the variable at index 0 in the if above. 
</details>
The old variable category had one of each block for each variable; now there's one of each of the setters, and then one getter for each variable.  So the stuff above doesn't apply to any variable in particular.

---

*[core/variables.js, line 309 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOjx43YePjgFCO9F2j:-KPPMOIjwLqNDu7-VlYw:bss4a2b) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/variables.js#L309)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> extra line
</details>
Removed.

---

*[core/variables.js, line 322 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOkHGgma6Pz47d8qQC:-KPPMPDUR0jXTWJ1SX4L:br49abt) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/variables.js#L322)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> Should this comment be here?
</details>
No, but I think I also am not dealing with this case correctly.  Need to fix that.

---

*[core/workspace.js, line 121 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOl2EwyufBn9V2mlIz:-KPPMTXxobf3I7wTSTnP:b-a13ugm) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/workspace.js#L121)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> Is this here to catch cases like undo/redo, load from xml, etc where a variable is introduced to the workspace not through the create new variable button?  Maybe throw a comment in.
</details>
Yes, it is.  I'll add a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/557)*

**Comment by rachel-fenichel** [comment]
Review status: 0 of 98 files reviewed at latest revision, 13 unresolved discussions.

---

*[core/workspace.js, line 121 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOl2EwyufBn9V2mlIz:-KPPk--zVE0k1XkVaowi:bbq9uav) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/workspace.js#L121)):*
<details><summary><i>Previously, rachel-fenichel wrote…</i></summary>
> Yes, it is.  I'll add a comment.
</details>
Er no, not that at all.

I will put this in a comment, but:

This is for the (unlikely) case where you have a variable in a block in an always-open flyout.  It needs to be possible to edit the block in the flyout, which means the contents of the dropdown list needs to be correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/557)*

**Comment by picklesrus** [comment]
Review status: 0 of 98 files reviewed at latest revision, 13 unresolved discussions.

---

*[core/flyout_button.js, line 103 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOeypPBXR2DWDmlNAX:-KPTYZfzoiMoHo8pf5cA:b-i7b5su) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/flyout_button.js#L103)):*
<details><summary><i>Previously, rachel-fenichel wrote…</i></summary>
> Every time the variable flyout category opens.
</details>
Is it possible to set the width to null (or -1 or whatever) where you declare it as a member and then only call get computed length if you haven't set the width already?  I know opening the flyout isn't optimized yet and the whole page probably repaints already, but this will just solidify that more. 

Although, maybe zoom won't work then?

---

*[core/flyout_button.js, line 107 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOfMUdKJsfOxyFuIlw:-KPTZNy9cZQiWri1VLkI:br4re3l) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/flyout_button.js#L107)):*
<details><summary><i>Previously, rachel-fenichel wrote…</i></summary>
> I think I still would need to.  Why would a div stop that?
</details>
Yeah. ignore me on this one. I really meant <button>. The button can size itself properly during the normal layout pass, but the flyout would still need to know the width of the button so you'd probably just end up calling getBBox or something which has the same problem as getComputedTextLength.

---

*[core/variables.js, line 175 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOjMYwW63b41gqpiWd:-KPTgZ8mYQ4BdJ0_6QLt:b-opmlne) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/variables.js#L175)):*
<details><summary><i>Previously, rachel-fenichel wrote…</i></summary>
> The old variable category had one of each block for each variable; now there's one of each of the setters, and then one getter for each variable.  So the stuff above doesn't apply to any variable in particular.
</details>
Hmm, still don't quite understand, so different question: is the first variable in variableList always the one that goes in the math change by block?  I think what's throwing me is the createDomLine above where you pass variableList[0]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/557)*

**Comment by rachel-fenichel** [comment]
Review status: 0 of 98 files reviewed at latest revision, 13 unresolved discussions.

---

*[core/flyout_button.js, line 103 \[r1\]](https://reviewable.io:443/reviews/google/blockly/557#-KPOeypPBXR2DWDmlNAX:-KPTum-Pj3C1OUw96bMW:bp9dcrx) ([raw file](https://github.com/google/blockly/blob/eba075b5b6ba5f8b4d7cb3741773ce30532ec9ee/core/flyout_button.js#L103)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> Is it possible to set the width to null (or -1 or whatever) where you declare it as a member and then only call get computed length if you haven't set the width already?  I know opening the flyout isn't optimized yet and the whole page probably repaints already, but this will just solidify that more. 
> 
> Although, maybe zoom won't work then?
</details>
I think this is better put in the category of "flyout optimizations", since this is only for a single category, and left for another pass.  I suspect that in the process of improving this I would find another pile of changes to make in the flyout code, and I'd like that to be separate from this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/557)*

**Comment by picklesrus** [comment]
:lgtm:

---

Review status: 0 of 98 files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/557#-:-KPUneDzrHT6rcIv14pv:bnfp4nl)*

**Pull request merged**
