### PR TITLE
Remove flyout scrollbar background.

### PR DESCRIPTION
**Pull request by carlosperate**
A simple visual change to remove the white background of the flyout scrollbar.

This does not affect the background of the rest of scrollbars.

scrollbar

### CODE REVIEW

**Comment by NeilFraser** [comment]
Thanks for this.  How about going even further?  Check this out:
  https://blockly-demo.appspot.com/static/demos/code/index.html
What do you think?

**Comment by carlosperate** [comment]
Looks great, that's the way I have it on my fork as well (although I overwrote the class in a CSS file).

The only thing is that if somebody wants to keep the background colour, for whatever reason, their changes to the CSS class will still affect both workspace and flyout scrollbars.

**Comment by NeilFraser** [comment]
I've added seven new classes on various SVG elements, so CSS rules should now be easier to apply:
https://github.com/google/blockly/commit/1ca2fdc8445001981cfcf483181f24ae49325452
I've also darkened the flyout scrollbars a bit since they had less contrast than the workspace scrollbars:
https://github.com/google/blockly/commit/f2c9c89dd35a0d6854324d9c89d519382232c0ae

**Comment by carlosperate** [comment]
Perfect, thanks Neil!

**Pull request closed without merging**
