### PR TITLE
Blockly Factory: Workspace Factory UI

### PR DESCRIPTION
**Pull request by evd2014**
Made small UI changes to workspace factory including: 

- Changing help text for the "toolbox" and "workspace" tabs and style of tabs so that they appear separate from the workspace toolbox.

- Changing the "Clear Toolbox" button to "Clear" and having it clear all state (for both tabs instead of just the toolbox).

- Making options scrollable with a minimum height, and change text of "Standard Options" button to "Reset Options".

- Adding a border around the preview workspace to make it appear separate from the editing area. Changing help text for preview workspace in an attempt to clarify it's relationship to the custom workspace being created.

- Removed "Print Toolbox" button mainly used for debugging. 

- Fixed bug with event listeners for arrow keys so that categories can only be moved up or down when in workspace factory and editing the toolbox.

- Added a"Your Categories:" header to the category list to make it clearer when the user creates and selects their custom categories. 

screen shot 2016-08-22 at 11 09 49 am
screen shot 2016-08-22 at 11 10 06 am

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/577)

### CODE REVIEW

**Comment by evd2014** [comment]
@picklesrus @vicng @quachtina96

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/577#-:-KPnS3ff7i8WfRPAj4_0:bvyui8)*

**Comment by picklesrus** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/factory.css, line 262 \[r1\]](https://reviewable.io:443/reviews/google/blockly/577#-KPnny0sJZ7O3uuKMcpM:-KPnny0sJZ7O3uuKMcpN:b-nfmgn8) ([raw file](https://github.com/google/blockly/blob/0a241af55ae489a60ad4bcf9ca59f7ffb1ca599c/demos/blocklyfactory/factory.css#L262)):*
> ```CSS
> td.tabon {
>   background-color: #ccc;
>   border-bottom-color: #ccc !important;
> ```

I know you didn't add this here, but do you need the important?

---

*[demos/blocklyfactory/workspacefactory/wfactory_view.js, line 223 \[r1\]](https://reviewable.io:443/reviews/google/blockly/577#-KPnopXRobQS33nnyLnN:-KPnopXRobQS33nnyLnO:bjs3o94) ([raw file](https://github.com/google/blockly/blob/0a241af55ae489a60ad4bcf9ca59f7ffb1ca599c/demos/blocklyfactory/workspacefactory/wfactory_view.js#L223)):*
> ```JavaScript
>   }
>   if (newIndex < oldIndex) {  // Inserting before.
>     var row = table.insertRow(newIndex + 1);
> ```

These are +1 and +2 because you added the help row above?  Probably worth throwing a comment in here since it is a bit surprising.  Also, do you need to change the check above to reflect the +2s and +1s here? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/577)*

**Comment by evd2014** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/factory.css, line 262 \[r1\]](https://reviewable.io:443/reviews/google/blockly/577#-KPnny0sJZ7O3uuKMcpM:-KPoEBIc0yauAm3dPz8S:b-hh7njg) ([raw file](https://github.com/google/blockly/blob/0a241af55ae489a60ad4bcf9ca59f7ffb1ca599c/demos/blocklyfactory/factory.css#L262)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> I know you didn't add this here, but do you need the important?
</details>
Oops, not sure why that was ever added. Removed.

---

*[demos/blocklyfactory/workspacefactory/wfactory_view.js, line 223 \[r1\]](https://reviewable.io:443/reviews/google/blockly/577#-KPnopXRobQS33nnyLnN:-KPoEDzuevXpAKT2M_2v:b-quxzsg) ([raw file](https://github.com/google/blockly/blob/0a241af55ae489a60ad4bcf9ca59f7ffb1ca599c/demos/blocklyfactory/workspacefactory/wfactory_view.js#L223)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> These are +1 and +2 because you added the help row above?  Probably worth throwing a comment in here since it is a bit surprising.  Also, do you need to change the check above to reflect the +2s and +1s here? 
</details>
Yep, those were added for the help row. I added a comment about that. I don't need to change the check above because those indices are for the category list (not the tab numbers in the view). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/577)*

**Comment by vicng** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/app_controller.js, line 469 \[r2\]](https://reviewable.io:443/reviews/google/blockly/577#-KPoQYXcrdZ6iaPlsaCv:-KPoQYXcrdZ6iaPlsaCw:bl086ys) ([raw file](https://github.com/google/blockly/blob/797d85db808966e4cdb16105e5d98fcd8437d839/demos/blocklyfactory/app_controller.js#L469)):*
> ```JavaScript
> 
> /**
>  * Adds keydown event listener for workspace factory. Needs to be initialized
> ```

If you find yourself needing to make shortcuts like this, it usually is a sign of a <a href='https://en.wikipedia.org/wiki/Code_smell'>code smell</a> -- it means the design can be improved or refactored.

What if you added a boolean variable called "enableKeyboardEvents" to WorkspaceFactoryController? Then you could move this code to WFC (or WF init), and just update that variable when the tab switches.

---

*[demos/blocklyfactory/index.html, line 170 \[r2\]](https://reviewable.io:443/reviews/google/blockly/577#-KPoS4tx4keOLHpRiVHb:-KPoS4tx4keOLHpRiVHc:b-9v7tt2) ([raw file](https://github.com/google/blockly/blob/797d85db808966e4cdb16105e5d98fcd8437d839/demos/blocklyfactory/index.html#L170)):*
> ```HTML
>         <table id="categoryTable" style="width:auto">
>           <tr>
>             <td id="tab_help">Your categories will appear here</td>
> ```

Shouldn't this be outside the table? It makes the JS code more error prone (with the +1/+2 code)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/577)*

**Comment by vicng** [comment]
Also it might nice if the Preview border was thicker (maybe 40px top/bottom and 20px left/right) and if the preview section was the same height as the workspace section.

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/577#-:-KPoTBtLn-3Q5jamHB6H:b-ch7yw3)*

**Comment by evd2014** [comment]
Made the preview section the same height as the workspace section. Also played around with making the preview border thicker, and 40px for top/bottom and 20px left/right personally looked too unbalanced and thick, so I went somewhere in between: 


Also made some small bug fixes throughout as I tested more.

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/app_controller.js, line 469 \[r2\]](https://reviewable.io:443/reviews/google/blockly/577#-KPoQYXcrdZ6iaPlsaCv:-KPoirM-6GsD1WWLN2mb:b-8qt29v) ([raw file](https://github.com/google/blockly/blob/797d85db808966e4cdb16105e5d98fcd8437d839/demos/blocklyfactory/app_controller.js#L469)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> If you find yourself needing to make shortcuts like this, it usually is a sign of a <a href='https://en.wikipedia.org/wiki/Code_smell'>code smell</a> -- it means the design can be improved or refactored.
> 
> What if you added a boolean variable called "enableKeyboardEvents" to WorkspaceFactoryController? Then you could move this code to WFC (or WF init), and just update that variable when the tab switches.
> 
</details>
Good idea -- that makes things a lot more straightforward! Added a boolean to the controller for enableKeyEvents and update it when I switch tabs and use it in the event listener. 

---

*[demos/blocklyfactory/index.html, line 170 \[r2\]](https://reviewable.io:443/reviews/google/blockly/577#-KPoS4tx4keOLHpRiVHb:-KPog_0uAtDJGeoh7VmH:b38gubb) ([raw file](https://github.com/google/blockly/blob/797d85db808966e4cdb16105e5d98fcd8437d839/demos/blocklyfactory/index.html#L170)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Shouldn't this be outside the table? It makes the JS code more error prone (with the +1/+2 code)
</details>
Much better outside the table! Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/577#-:-KPokfWGmXu5Pkw9XQC5:btd50ry)*

**Comment by picklesrus** [comment]
Code is much cleaner now :)  Looks like there's a little leftover from a debugging session though - see comment below.

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 710 \[r4\]](https://reviewable.io:443/reviews/google/blockly/577#-KPopSgopjSgxi7wDeR5:-KPopSgpODNgLMqp4UIH:b7orp7g) ([raw file](https://github.com/google/blockly/blob/c5e9564956a4912e7a35483592d94f51ca321804/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L710)):*
> ```JavaScript
>         throw new Error("Unknown import mode: " + importMode);
>       }
>      // } catch(e) {
> ```

Why is this commented out?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/577#-:-KPopuDf46tC8hWhypJG:b-m97fv9)*

**Comment by evd2014** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 710 \[r4\]](https://reviewable.io:443/reviews/google/blockly/577#-KPopSgopjSgxi7wDeR5:-KPorO8VFpCEGAzGUH4E:b-cmpfhm) ([raw file](https://github.com/google/blockly/blob/c5e9564956a4912e7a35483592d94f51ca321804/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L710)):*
<details><summary><i>Previously, picklesrus wrote…</i></summary>
> Why is this commented out?
</details>
Oops. Uncommented!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/577)*

**Comment by vicng** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/app_controller.js, line 294 \[r5\]](https://reviewable.io:443/reviews/google/blockly/577#-KPow1d3kamxSWZeCXiE:-KPow1d4gtlr5Fd4sooz:b7tzhyg) ([raw file](https://github.com/google/blockly/blob/d977ebfe48f1c913c0081857aae1b91ee8f525dc/demos/blocklyfactory/app_controller.js#L294)):*
> ```JavaScript
> 
>   if (this.selectedTab == 'EXPORTER') {
>     // Disable key events in workspace factory.
> ```

You could do this in a one-liner:

`this.workspaceFactoryController.keyEventsEnabled = (this.selectedTab == 'WORKSPACE_FACTORY')`

Also, EXPORTER/BLOCK_FACTORY/WORKSPACE_FACTORY should be referenced as variables throughout this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/577)*

**Comment by quachtina96** [comment]
One nit suggestion, otherwise  :lgtm:  Also i really like the changes you made and agree the code is cleaner/more readable! woo!

---

Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/workspacefactory/wfactory_init.js, line 375 \[r5\]](https://reviewable.io:443/reviews/google/blockly/577#-KPs6OnBA3Ghhh03PgP2:-KPs6OnBA3Ghhh03PgP3:bd7v0df) ([raw file](https://github.com/google/blockly/blob/d977ebfe48f1c913c0081857aae1b91ee8f525dc/demos/blocklyfactory/workspacefactory/wfactory_init.js#L375)):*
> ```JavaScript
>     // Don't let arrow keys have any effect if not in Workspace Factory
>     // editing the toolbox.
>     if (!controller.keyEventsEnabled || controller.selectedMode
> ```

simplifying to "if (! (controller.keyEventsEnabled && controller.selectedMode == WorkspaceFactoryController.MODE_TOOLBOX))" makes it more explicit exactly what is needed to be listening for arrow keys

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/577#-:-KPs7eVxxaXywW9jnh2W:b-lpjx4w)*

**Comment by evd2014** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[demos/blocklyfactory/app_controller.js, line 294 \[r5\]](https://reviewable.io:443/reviews/google/blockly/577#-KPow1d3kamxSWZeCXiE:-KPs8wzD6_8c4tBvPo5x:bv8mx5p) ([raw file](https://github.com/google/blockly/blob/d977ebfe48f1c913c0081857aae1b91ee8f525dc/demos/blocklyfactory/app_controller.js#L294)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> You could do this in a one-liner:
> 
> `this.workspaceFactoryController.keyEventsEnabled = (this.selectedTab == 'WORKSPACE_FACTORY')`
> 
> Also, EXPORTER/BLOCK_FACTORY/WORKSPACE_FACTORY should be referenced as variables throughout this file.
</details>
Thanks! 

Added constants for the three tabs and referred to the constants instead of strings throughout the file. Changed how I have to initialize tabMap.

---

*[demos/blocklyfactory/workspacefactory/wfactory_init.js, line 375 \[r5\]](https://reviewable.io:443/reviews/google/blockly/577#-KPs6OnBA3Ghhh03PgP2:-KPsCOLGVPn__gotWQ7Y:b-896fix) ([raw file](https://github.com/google/blockly/blob/d977ebfe48f1c913c0081857aae1b91ee8f525dc/demos/blocklyfactory/workspacefactory/wfactory_init.js#L375)):*
<details><summary><i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>
> simplifying to "if (! (controller.keyEventsEnabled && controller.selectedMode == WorkspaceFactoryController.MODE_TOOLBOX))" makes it more explicit exactly what is needed to be listening for arrow keys
</details>
Done.

---

*[demos/blocklyfactory/workspacefactory/wfactory_view.js, line 223 \[r1\]](https://reviewable.io:443/reviews/google/blockly/577#-KPnopXRobQS33nnyLnN:-KPsCeMyUHJIgnX3INpp:b-mkdiyr) ([raw file](https://github.com/google/blockly/blob/0a241af55ae489a60ad4bcf9ca59f7ffb1ca599c/demos/blocklyfactory/workspacefactory/wfactory_view.js#L223)):*
<details><summary><i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>
> Yep, those were added for the help row. I added a comment about that. I don't need to change the check above because those indices are for the category list (not the tab numbers in the view). 
</details>
Actually was able to remove this entirely after moving the help row to just be an element above the table -- simplified the code nicely. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/577)*

**Comment by picklesrus** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/577#-:-KPsVdgNvNi1-dqZj8ez:bnfp4nl)*

**Pull request merged**
