### PR TITLE
fix!: Remove blocklyMenuItemHighlight CSS class in menuitem 

### PR DESCRIPTION
**Pull request by Arun-cn**
Fixes Remove blocklyMenuItemHighlight CSS class and use :hover CSS selector

## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes Remove blocklyMenuItemHighlight CSS class and use :hover CSS selector #8327 

### Proposed Changes
Remove the blocklyMenuItemHighlight CSS class from the [menu item](https://github.com/google/blockly/blob/f8025a1bdd12025ecb8830159509148ff27ad3c8/core/menuitem.ts#L73).
Use the [:hover CSS pseudo class](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover) in [css.ts](https://github.com/google/blockly/blob/f8025a1bdd12025ecb8830159509148ff27ad3c8/core/css.ts#L481).

### Additional Information
Please let me know, if any changes are needed.

### CODE REVIEW

**Review by BeksOmega — COMMENTED** [review]
I'm going to get #8339 merged first because I think that might create some conflicts here =)

**Comment by BeksOmega** [comment]
@Arun-cn could you rebase this ontop of the latest `rc/v12.0.0`? Let me know if you haven't done a rebase before! I can post the commands you need to run.

**Comment by Arun-cn** [comment]
ok please give me commands

**Comment by BeksOmega** [comment]
Here are the steps to rebase your branch @Arun-cn :

1. **Fetch the latest changes from `rc/v12.0.0`:**

   ```bash
   git fetch upstream rc/v12.0.0
   ```

2. **Checkout your branch:**

   ```bash
   git checkout [your-branch-name]
   ```

3. **Start a rebase:**

   ```bash
   git rebase upstream/rc/v12.0.0
   ```

8. **Resolve any conflicts that come up.** You will see things like `<<<<` `====` `>>>>` in your code, which indicate where there is a code conflict. Remove any of those, deduplicate the code, and make sure the finalized code looks correct.

9. **Continue the rebase, and repeat the previous step as necessary**

```bash
git rebase --continue
```

11. **Force push your changes to your branch:** Note that force pushing is a dangerous operation because it overwrites commit history, so if you dropped the wrong commits you could lose work.

   ```bash
   git push -f origin [your-branch-name]
   ```

Let me know if you have any questions or run into any issues!

**Pull request closed without merging**
